// hexdump-Os_plt.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

// 00001040: void strlen()
void strlen()
{
}

<anonymous> g_t1046 = <code>;
