// hexdump-O0.h
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (2FC code t02FC) (35C int32 dw035C) (360 int32 dw0360) (380 word32 dw0380) (384 word32 dw0384) (388 word32 dw0388) (38C int32 dw038C) (3B4 word32 dw03B4) (3B8 word32 dw03B8) (3BC word32 dw03BC) (3C0 int32 dw03C0) (3F4 word32 dw03F4) (3F8 int32 dw03F8) (11010 (ptr32 code) ptr11010))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_3: (fn void ((ptr32 code)))
	T_3 (in call_weak_fn : ptr32)
	T_4 (in signature of call_weak_fn : void)
Eq_43: (union "Eq_43" (int32 u0) (uint32 u1))
	T_43 (in r1_9 : Eq_43)
	T_52 (in g_dw03B8 + 0x39C<u32> - (g_dw03B4 + 0x398<u32>) : word32)
Eq_59: (union "Eq_59" (int32 u0) (uint32 u1))
	T_59 (in r1_9 >> 31<i32> : word32)
Eq_61: (union "Eq_61" (int32 u0) (uint32 u1))
	T_61 (in r1_9 >> 2<u32> : word32)
Eq_62: (union "Eq_62" (int32 u0) (uint32 u1))
	T_62 (in (r1_9 >>u 31<i32>) + (r1_9 >> 2<u32>) : word32)
Eq_93: (fn void ())
	T_93 (in deregister_tm_clones : ptr32)
	T_94 (in signature of deregister_tm_clones : void)
Eq_102: (fn void ())
	T_102 (in register_tm_clones : ptr32)
	T_103 (in signature of register_tm_clones : void)
Eq_117: (struct "Eq_117" (FFFFFF8C byte bFFFFFF8C))
	T_117 (in r2 + 1<32> + (fp - 8<32>) : word32)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in lr : (ptr32 code))
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: word32
T_3: (in call_weak_fn : ptr32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (fn T_6 (T_2)))
T_4: (in signature of call_weak_fn : void)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: 
T_5: (in lr : (ptr32 code))
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_6: (in call_weak_fn(lr) : void)
  Class: Eq_6
  DataType: void
  OrigDataType: void
T_7: (in 00000350 : ptr32)
  Class: Eq_7
  DataType: ptr32
  OrigDataType: ptr32
T_8: (in 0000035C : ptr32)
  Class: Eq_8
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_9 t0000)))
T_9: (in Mem0[0x0000035C<p32>:word32] : word32)
  Class: Eq_9
  DataType: int32
  OrigDataType: int32
T_10: (in 0x350<u32> + g_dw035C : word32)
  Class: Eq_10
  DataType: ptr32
  OrigDataType: ptr32
T_11: (in 00000360 : ptr32)
  Class: Eq_11
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_12 t0000)))
T_12: (in Mem0[0x00000360<p32>:word32] : word32)
  Class: Eq_12
  DataType: int32
  OrigDataType: int32
T_13: (in 0x350<u32> + g_dw035C + g_dw0360 : word32)
  Class: Eq_13
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_14 t0000)))
T_14: (in Mem0[0x00000350<p32> + Mem0[0x0000035C<p32>:word32] + Mem0[0x00000360<p32>:word32]:word32] : word32)
  Class: Eq_14
  DataType: word32
  OrigDataType: word32
T_15: (in 0<32> : word32)
  Class: Eq_14
  DataType: word32
  OrigDataType: word32
T_16: (in 0x350<u32> + g_dw035C + g_dw0360 != 0<32> : bool)
  Class: Eq_16
  DataType: bool
  OrigDataType: bool
T_17: (in lr_17 : word32)
  Class: Eq_17
  DataType: word32
  OrigDataType: word32
T_18: (in 00011010 : ptr32)
  Class: Eq_18
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_19 t0000)))
T_19: (in Mem0[0x00011010<p32>:word32] : word32)
  Class: Eq_19
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_20: (in r2_9 : ptr32)
  Class: Eq_20
  DataType: ptr32
  OrigDataType: ptr32
T_21: (in 00000388 : ptr32)
  Class: Eq_21
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_22 t0000)))
T_22: (in Mem0[0x00000388<p32>:word32] : word32)
  Class: Eq_22
  DataType: word32
  OrigDataType: word32
T_23: (in 00000372 : ptr32)
  Class: Eq_23
  DataType: ptr32
  OrigDataType: ptr32
T_24: (in g_dw0388 + 0x372<u32> : word32)
  Class: Eq_20
  DataType: ptr32
  OrigDataType: word32
T_25: (in 00000384 : ptr32)
  Class: Eq_25
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_26 t0000)))
T_26: (in Mem0[0x00000384<p32>:word32] : word32)
  Class: Eq_26
  DataType: word32
  OrigDataType: word32
T_27: (in 00000370 : ptr32)
  Class: Eq_27
  DataType: ptr32
  OrigDataType: ptr32
T_28: (in g_dw0384 + 0x370<u32> : word32)
  Class: Eq_28
  DataType: word32
  OrigDataType: word32
T_29: (in 00000380 : ptr32)
  Class: Eq_29
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_30 t0000)))
T_30: (in Mem0[0x00000380<p32>:word32] : word32)
  Class: Eq_30
  DataType: word32
  OrigDataType: word32
T_31: (in 0000036E : ptr32)
  Class: Eq_31
  DataType: ptr32
  OrigDataType: ptr32
T_32: (in g_dw0380 + 0x36E<u32> : word32)
  Class: Eq_28
  DataType: word32
  OrigDataType: word32
T_33: (in g_dw0384 + 0x370<u32> == g_dw0380 + 0x36E<u32> : bool)
  Class: Eq_33
  DataType: bool
  OrigDataType: bool
T_34: (in r3_13 : (ptr32 code))
  Class: Eq_34
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_35: (in 0000038C : ptr32)
  Class: Eq_35
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_36 t0000)))
T_36: (in Mem0[0x0000038C<p32>:word32] : word32)
  Class: Eq_36
  DataType: int32
  OrigDataType: int32
T_37: (in r2_9 + g_dw038C : word32)
  Class: Eq_37
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_38 t0000)))
T_38: (in Mem0[r2_9 + Mem0[0x0000038C<p32>:word32]:word32] : word32)
  Class: Eq_34
  DataType: (ptr32 code)
  OrigDataType: word32
T_39: (in 0<32> : word32)
  Class: Eq_34
  DataType: (ptr32 code)
  OrigDataType: word32
T_40: (in r3_13 == null : bool)
  Class: Eq_40
  DataType: bool
  OrigDataType: bool
T_41: (in pc_16 : word32)
  Class: Eq_41
  DataType: word32
  OrigDataType: word32
T_42: (in lr_19 : word32)
  Class: Eq_42
  DataType: word32
  OrigDataType: word32
T_43: (in r1_9 : Eq_43)
  Class: Eq_43
  DataType: Eq_43
  OrigDataType: (union (int32 u1) (uint32 u0))
T_44: (in 000003B8 : ptr32)
  Class: Eq_44
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_45 t0000)))
T_45: (in Mem0[0x000003B8<p32>:word32] : word32)
  Class: Eq_45
  DataType: word32
  OrigDataType: word32
T_46: (in 0000039C : ptr32)
  Class: Eq_46
  DataType: ptr32
  OrigDataType: ptr32
T_47: (in g_dw03B8 + 0x39C<u32> : word32)
  Class: Eq_47
  DataType: word32
  OrigDataType: word32
T_48: (in 000003B4 : ptr32)
  Class: Eq_48
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_49 t0000)))
T_49: (in Mem0[0x000003B4<p32>:word32] : word32)
  Class: Eq_49
  DataType: word32
  OrigDataType: word32
T_50: (in 00000398 : ptr32)
  Class: Eq_50
  DataType: ptr32
  OrigDataType: ptr32
T_51: (in g_dw03B4 + 0x398<u32> : word32)
  Class: Eq_51
  DataType: word32
  OrigDataType: word32
T_52: (in g_dw03B8 + 0x39C<u32> - (g_dw03B4 + 0x398<u32>) : word32)
  Class: Eq_43
  DataType: Eq_43
  OrigDataType: word32
T_53: (in r2_10 : ptr32)
  Class: Eq_53
  DataType: ptr32
  OrigDataType: ptr32
T_54: (in 000003BC : ptr32)
  Class: Eq_54
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_55 t0000)))
T_55: (in Mem0[0x000003BC<p32>:word32] : word32)
  Class: Eq_55
  DataType: word32
  OrigDataType: word32
T_56: (in 000003A0 : ptr32)
  Class: Eq_56
  DataType: ptr32
  OrigDataType: ptr32
T_57: (in g_dw03BC + 0x3A0<u32> : word32)
  Class: Eq_53
  DataType: ptr32
  OrigDataType: word32
T_58: (in 31<i32> : int32)
  Class: Eq_58
  DataType: int32
  OrigDataType: int32
T_59: (in r1_9 >> 31<i32> : word32)
  Class: Eq_59
  DataType: Eq_59
  OrigDataType: (union (int32 u1) (uint32 u0))
T_60: (in 2<u32> : uint32)
  Class: Eq_60
  DataType: uint32
  OrigDataType: uint32
T_61: (in r1_9 >> 2<u32> : word32)
  Class: Eq_61
  DataType: Eq_61
  OrigDataType: (union (int32 u1) (uint32 u0))
T_62: (in (r1_9 >>u 31<i32>) + (r1_9 >> 2<u32>) : word32)
  Class: Eq_62
  DataType: Eq_62
  OrigDataType: (union (int32 u1) (uint32 u0))
T_63: (in 1<i32> : int32)
  Class: Eq_63
  DataType: int32
  OrigDataType: int32
T_64: (in (r1_9 >>u 31<i32>) + (r1_9 >> 2<u32>) >> 1<i32> : word32)
  Class: Eq_64
  DataType: int32
  OrigDataType: int32
T_65: (in 0<32> : word32)
  Class: Eq_64
  DataType: int32
  OrigDataType: word32
T_66: (in (r1_9 >>u 31<i32>) + (r1_9 >> 2<u32>) >> 1<i32> == 0<32> : bool)
  Class: Eq_66
  DataType: bool
  OrigDataType: bool
T_67: (in r3_18 : (ptr32 code))
  Class: Eq_67
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_68: (in 000003C0 : ptr32)
  Class: Eq_68
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_69 t0000)))
T_69: (in Mem0[0x000003C0<p32>:word32] : word32)
  Class: Eq_69
  DataType: int32
  OrigDataType: int32
T_70: (in r2_10 + g_dw03C0 : word32)
  Class: Eq_70
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_71 t0000)))
T_71: (in Mem0[r2_10 + Mem0[0x000003C0<p32>:word32]:word32] : word32)
  Class: Eq_67
  DataType: (ptr32 code)
  OrigDataType: word32
T_72: (in 0<32> : word32)
  Class: Eq_67
  DataType: (ptr32 code)
  OrigDataType: word32
T_73: (in r3_18 == null : bool)
  Class: Eq_73
  DataType: bool
  OrigDataType: bool
T_74: (in r2_11 : ptr32)
  Class: Eq_74
  DataType: ptr32
  OrigDataType: ptr32
T_75: (in 000003F4 : ptr32)
  Class: Eq_75
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_76 t0000)))
T_76: (in Mem7[0x000003F4<p32>:word32] : word32)
  Class: Eq_76
  DataType: word32
  OrigDataType: word32
T_77: (in 000003D0 : ptr32)
  Class: Eq_77
  DataType: ptr32
  OrigDataType: ptr32
T_78: (in g_dw03F4 + 0x3D0<u32> : word32)
  Class: Eq_74
  DataType: ptr32
  OrigDataType: word32
T_79: (in 000003F0 : ptr32)
  Class: Eq_79
  DataType: ptr32
  OrigDataType: ptr32
T_80: (in Mem7[0x000003F0<p32>:word32] : word32)
  Class: Eq_80
  DataType: word32
  OrigDataType: word32
T_81: (in 000003CE : ptr32)
  Class: Eq_81
  DataType: ptr32
  OrigDataType: ptr32
T_82: (in 0x3F0<u32> + 0x3CE<u32> : word32)
  Class: Eq_82
  DataType: word32
  OrigDataType: word32
T_83: (in Mem7[Mem7[0x000003F0<p32>:word32] + 0x000003CE<p32>:byte] : byte)
  Class: Eq_83
  DataType: byte
  OrigDataType: byte
T_84: (in CONVERT(Mem7[Mem7[0x000003F0<p32>:word32] + 0x000003CE<p32>:byte], byte, word32) : word32)
  Class: Eq_84
  DataType: word32
  OrigDataType: word32
T_85: (in 0<32> : word32)
  Class: Eq_84
  DataType: word32
  OrigDataType: word32
T_86: (in (word32) (0x3F0<u32> + 0x3CE<u32>) != 0<32> : bool)
  Class: Eq_86
  DataType: bool
  OrigDataType: bool
T_87: (in 000003F8 : ptr32)
  Class: Eq_87
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_88 t0000)))
T_88: (in Mem7[0x000003F8<p32>:word32] : word32)
  Class: Eq_88
  DataType: int32
  OrigDataType: int32
T_89: (in r2_11 + g_dw03F8 : word32)
  Class: Eq_89
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_90 t0000)))
T_90: (in Mem7[r2_11 + Mem7[0x000003F8<p32>:word32]:word32] : word32)
  Class: Eq_90
  DataType: word32
  OrigDataType: word32
T_91: (in 0<32> : word32)
  Class: Eq_90
  DataType: word32
  OrigDataType: word32
T_92: (in r2_11 + g_dw03F8 == 0<32> : bool)
  Class: Eq_92
  DataType: bool
  OrigDataType: bool
T_93: (in deregister_tm_clones : ptr32)
  Class: Eq_93
  DataType: (ptr32 Eq_93)
  OrigDataType: (ptr32 (fn T_95 ()))
T_94: (in signature of deregister_tm_clones : void)
  Class: Eq_93
  DataType: (ptr32 Eq_93)
  OrigDataType: 
T_95: (in deregister_tm_clones() : void)
  Class: Eq_95
  DataType: void
  OrigDataType: void
T_96: (in 1<8> : byte)
  Class: Eq_96
  DataType: byte
  OrigDataType: byte
T_97: (in 00000400 : ptr32)
  Class: Eq_97
  DataType: ptr32
  OrigDataType: ptr32
T_98: (in Mem7[0x00000400<p32>:word32] : word32)
  Class: Eq_98
  DataType: word32
  OrigDataType: word32
T_99: (in 000003EE : ptr32)
  Class: Eq_99
  DataType: ptr32
  OrigDataType: ptr32
T_100: (in 0x400<u32> + 0x3EE<u32> : word32)
  Class: Eq_100
  DataType: word32
  OrigDataType: word32
T_101: (in Mem29[Mem7[0x00000400<p32>:word32] + 0x000003EE<p32>:byte] : byte)
  Class: Eq_96
  DataType: byte
  OrigDataType: byte
T_102: (in register_tm_clones : ptr32)
  Class: Eq_102
  DataType: (ptr32 Eq_102)
  OrigDataType: (ptr32 (fn T_104 ()))
T_103: (in signature of register_tm_clones : void)
  Class: Eq_102
  DataType: (ptr32 Eq_102)
  OrigDataType: 
T_104: (in register_tm_clones() : void)
  Class: Eq_104
  DataType: void
  OrigDataType: void
T_105: (in r2 : int32)
  Class: Eq_105
  DataType: int32
  OrigDataType: int32
T_106: (in 0x41<8> : byte)
  Class: Eq_106
  DataType: byte
  OrigDataType: byte
T_107: (in fp : ptr32)
  Class: Eq_107
  DataType: ptr32
  OrigDataType: ptr32
T_108: (in 0x7C<32> : word32)
  Class: Eq_108
  DataType: ui32
  OrigDataType: ui32
T_109: (in fp - 0x7C<32> : word32)
  Class: Eq_109
  DataType: ptr32
  OrigDataType: ptr32
T_110: (in r2 + (fp - 0x7C<32>) : word32)
  Class: Eq_110
  DataType: (ptr32 byte)
  OrigDataType: (ptr32 (struct (0 T_111 t0000)))
T_111: (in Mem32[r2 + (fp - 0x7C<32>):byte] : byte)
  Class: Eq_106
  DataType: byte
  OrigDataType: byte
T_112: (in 0x20<8> : byte)
  Class: Eq_112
  DataType: byte
  OrigDataType: byte
T_113: (in 1<32> : word32)
  Class: Eq_113
  DataType: word32
  OrigDataType: word32
T_114: (in r2 + 1<32> : word32)
  Class: Eq_114
  DataType: int32
  OrigDataType: int32
T_115: (in 8<32> : word32)
  Class: Eq_115
  DataType: ui32
  OrigDataType: ui32
T_116: (in fp - 8<32> : word32)
  Class: Eq_116
  DataType: ptr32
  OrigDataType: ptr32
T_117: (in r2 + 1<32> + (fp - 8<32>) : word32)
  Class: Eq_117
  DataType: (ptr32 Eq_117)
  OrigDataType: (ptr32 (struct (FFFFFF8C T_120 tFFFFFF8C)))
T_118: (in -116<i32> : int32)
  Class: Eq_118
  DataType: int32
  OrigDataType: int32
T_119: (in r2 + 1<32> + (fp - 8<32>) + -116<i32> : word32)
  Class: Eq_119
  DataType: int32
  OrigDataType: int32
T_120: (in Mem38[r2 + 1<32> + (fp - 8<32>) + -116<i32>:byte] : byte)
  Class: Eq_112
  DataType: byte
  OrigDataType: byte
*/
typedef struct Globals {
	<anonymous> t02FC;	// 2FC
	int32 dw035C;	// 35C
	int32 dw0360;	// 360
	word32 dw0380;	// 380
	word32 dw0384;	// 384
	word32 dw0388;	// 388
	int32 dw038C;	// 38C
	word32 dw03B4;	// 3B4
	word32 dw03B8;	// 3B8
	word32 dw03BC;	// 3BC
	int32 dw03C0;	// 3C0
	word32 dw03F4;	// 3F4
	int32 dw03F8;	// 3F8
	<anonymous> * ptr11010;	// 11010
} Eq_1;

typedef void (Eq_3)(code *);

typedef union Eq_43 {
	int32 u0;
	uint32 u1;
} Eq_43;

typedef union Eq_59 {
	int32 u0;
	uint32 u1;
} Eq_59;

typedef union Eq_61 {
	int32 u0;
	uint32 u1;
} Eq_61;

typedef union Eq_62 {
	int32 u0;
	uint32 u1;
} Eq_62;

typedef void (Eq_93)();

typedef void (Eq_102)();

typedef struct Eq_117 {
	byte bFFFFFF8C;	// FFFFFF8C
} Eq_117;

