// hexdump-O2.h
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (10000 Eq_64 t10000) (109F0 (ptr64 Eq_64) ptr109F0) (109F8 word64 qw109F8) (10A00 word64 qw10A00) (10A48 (ptr64 Eq_84) ptr10A48) (10A50 (ptr64 code) ptr10A50) (10A60 (ptr64 code) ptr10A60) (10A68 (ptr64 Eq_38) ptr10A68) (10A70 (ptr64 Eq_118) ptr10A70) (20978 (ptr64 code) ptr20978) (20980 (ptr64 code) ptr20980) (20988 (ptr64 code) ptr20988))
	globals_t (in globals : (ptr64 (struct "Globals")))
Eq_17: (fn word64 (byte))
	T_17 (in __read_cpr2 : ptr64)
	T_18 (in signature of __read_cpr2 : void)
	T_135 (in __read_cpr2 : ptr64)
	T_174 (in __read_cpr2 : ptr64)
Eq_32: (fn void (byte, word64))
	T_32 (in __write_cpr2 : ptr64)
	T_33 (in signature of __write_cpr2 : void)
	T_43 (in __write_cpr2 : ptr64)
	T_49 (in __write_cpr2 : ptr64)
	T_68 (in __write_cpr2 : ptr64)
	T_81 (in __write_cpr2 : ptr64)
	T_89 (in __write_cpr2 : ptr64)
	T_95 (in __write_cpr2 : ptr64)
	T_115 (in __write_cpr2 : ptr64)
	T_147 (in __write_cpr2 : ptr64)
	T_158 (in __write_cpr2 : ptr64)
Eq_38: (struct "Eq_38" (2 word64 qw0002))
	T_38 (in Mem0[0x10A68<64>:word64] : word64)
Eq_55: (fn void ((ptr64 word64), (ptr64 code)))
	T_55 (in register_tm_clones : ptr64)
	T_56 (in signature of register_tm_clones : void)
Eq_60: (union "Eq_60" (int64 u0) (uint64 u1))
	T_60 (in r2_11 : Eq_60)
	T_67 (in g_qw109F8 - ((char *) g_ptr109F0 + 2528<i32>) : word64)
Eq_64: (struct "Eq_64" (A80 byte b0A80) (A88 int64 qw0A88))
	T_64 (in Mem0[0x109F0<64>:word64] : word64)
	T_106 (in r18_14 : (ptr64 Eq_64))
	T_108 (in Mem13[0x109F0<64>:word64] : word64)
	T_129 (in Mem22[0x109F0<64>:word64] : word64)
	T_171 (in Mem14[0x109F0<64>:word64] : word64)
Eq_71: (union "Eq_71" (int64 u0) (uint64 u1))
	T_71 (in r2_11 >> 0x3F<8> : word64)
Eq_73: (union "Eq_73" (int64 u0) (uint64 u1))
	T_73 (in r2_11 >> 3<8> : word64)
Eq_74: (union "Eq_74" (int64 u0) (uint64 u1))
	T_74 (in (r2_11 >>u 0x3F<8>) + (r2_11 >> 3<8>) : word64)
Eq_76: (struct "Eq_76" (4 word64 qw0004))
	T_76 (in (r2_11 >>u 0x3F<8>) + (r2_11 >> 3<8>) >> 1<8> : word64)
Eq_84: (struct "Eq_84" (2 word64 qw0002))
	T_84 (in Mem0[0x10A48<64>:word64] : word64)
Eq_101: (fn void ((ptr64 word64), (ptr64 code)))
	T_101 (in __do_global_dtors_aux : ptr64)
	T_102 (in signature of __do_global_dtors_aux : void)
Eq_118: (struct "Eq_118" (0 code t0000) (4 word64 qw0004))
	T_118 (in Mem22[0x10A70<64>:word64] : word64)
	T_127 (in Mem22[0x10A70<64>:word64] : word64)
Eq_153: (fn void ((ptr64 word64), (ptr64 code)))
	T_153 (in hexdump : ptr64)
	T_154 (in signature of hexdump : void)
Eq_164: (fn void ((ptr64 word64), (ptr64 code)))
	T_164 (in __do_global_ctors_aux : ptr64)
	T_165 (in signature of __do_global_ctors_aux : void)
Eq_169: (struct "Eq_169" 0008 (FFFFFFF8 word64 qwFFFFFFF8) (0 word64 qw0000))
	T_169 (in r16_21 : (ptr64 Eq_169))
	T_173 (in Mem14[0x109F0<64>:word64] + 2496<i64> : word64)
	T_186 (in r16_21 + -8<i64> : word64)
Eq_187: (struct "Eq_187" (FFFF8010 (ptr64 code) ptrFFFF8010))
	T_187 (in r28 : (ptr64 Eq_187))
Eq_192: (fn void ((ptr64 code)))
	T_192 (in _fini : ptr64)
	T_193 (in signature of _fini : void)
// Type Variables ////////////
globals_t: (in globals : (ptr64 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr64 Eq_1)
  OrigDataType: (ptr64 (struct "Globals"))
T_2: (in ra : (ptr64 code))
  Class: Eq_2
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_3: (in 0x10A60<64> : word64)
  Class: Eq_3
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_4 t0000)))
T_4: (in Mem10[0x10A60<64>:word64] : word64)
  Class: Eq_4
  DataType: (ptr64 code)
  OrigDataType: word64
T_5: (in 0<64> : word64)
  Class: Eq_4
  DataType: (ptr64 code)
  OrigDataType: word64
T_6: (in g_ptr10A60 == null : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_7: (in 0000000000020980 : ptr64)
  Class: Eq_7
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_8 t0000)))
T_8: (in Mem10[0x0000000000020980<p64>:word64] : word64)
  Class: Eq_8
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_9: (in 0000000000020978 : ptr64)
  Class: Eq_9
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_10 t0000)))
T_10: (in Mem10[0x0000000000020978<p64>:word64] : word64)
  Class: Eq_10
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_11: (in 0x10A60<64> : word64)
  Class: Eq_11
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_12 t0000)))
T_12: (in Mem10[0x10A60<64>:word64] : word64)
  Class: Eq_4
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_13: (in r0 : (ptr64 word64))
  Class: Eq_13
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_24 t0000)))
T_14: (in r2 : word64)
  Class: Eq_14
  DataType: word64
  OrigDataType: word64
T_15: (in r4 : word64)
  Class: Eq_15
  DataType: word64
  OrigDataType: word64
T_16: (in ra : (ptr64 code))
  Class: Eq_16
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_17: (in __read_cpr2 : ptr64)
  Class: Eq_17
  DataType: (ptr64 Eq_17)
  OrigDataType: (ptr64 (fn T_21 (T_20)))
T_18: (in signature of __read_cpr2 : void)
  Class: Eq_17
  DataType: (ptr64 Eq_17)
  OrigDataType: 
T_19: (in  : byte)
  Class: Eq_19
  DataType: byte
  OrigDataType: 
T_20: (in 0x19<8> : byte)
  Class: Eq_19
  DataType: byte
  OrigDataType: byte
T_21: (in __read_cpr2(0x19<8>) : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_22: (in 0<64> : word64)
  Class: Eq_22
  DataType: word64
  OrigDataType: word64
T_23: (in r0 + 0<64> : word64)
  Class: Eq_23
  DataType: word64
  OrigDataType: word64
T_24: (in Mem20[r0 + 0<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_25: (in r25_22 : (ptr64 code))
  Class: Eq_25
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_26: (in 0x10A50<64> : word64)
  Class: Eq_26
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_27 t0000)))
T_27: (in Mem20[0x10A50<64>:word64] : word64)
  Class: Eq_25
  DataType: (ptr64 code)
  OrigDataType: word64
T_28: (in r4_29 : word64)
  Class: Eq_28
  DataType: word64
  OrigDataType: word64
T_29: (in r5_30 : word64)
  Class: Eq_29
  DataType: word64
  OrigDataType: word64
T_30: (in r0 : (ptr64 word64))
  Class: Eq_30
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_35 t0000)))
T_31: (in ra : (ptr64 code))
  Class: Eq_31
  DataType: (ptr64 code)
  OrigDataType: word64
T_32: (in __write_cpr2 : ptr64)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: (ptr64 (fn T_42 (T_36, T_41)))
T_33: (in signature of __write_cpr2 : void)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: 
T_34: (in  : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: 
T_35: (in  : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: 
T_36: (in 0<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_37: (in 0x10A68<64> : word64)
  Class: Eq_37
  DataType: (ptr64 (ptr64 Eq_38))
  OrigDataType: (ptr64 (struct (0 T_38 t0000)))
T_38: (in Mem0[0x10A68<64>:word64] : word64)
  Class: Eq_38
  DataType: (ptr64 Eq_38)
  OrigDataType: (ptr64 (struct (2 T_41 t0002)))
T_39: (in 2<64> : word64)
  Class: Eq_39
  DataType: word64
  OrigDataType: word64
T_40: (in Mem0[0x10A68<64>:word64] + 2<64> : word64)
  Class: Eq_40
  DataType: word64
  OrigDataType: word64
T_41: (in Mem0[Mem0[0x10A68<64>:word64] + 2<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_42: (in __write_cpr2(0<8>, g_ptr10A68->qw0002) : void)
  Class: Eq_42
  DataType: void
  OrigDataType: void
T_43: (in __write_cpr2 : ptr64)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: (ptr64 (fn T_48 (T_44, T_47)))
T_44: (in 0x19<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_45: (in 0<64> : word64)
  Class: Eq_45
  DataType: word64
  OrigDataType: word64
T_46: (in r0 + 0<64> : word64)
  Class: Eq_46
  DataType: word64
  OrigDataType: word64
T_47: (in Mem0[r0 + 0<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_48: (in __write_cpr2(0x19<8>, *r0) : void)
  Class: Eq_42
  DataType: void
  OrigDataType: void
T_49: (in __write_cpr2 : ptr64)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: (ptr64 (fn T_54 (T_50, T_53)))
T_50: (in 0x1F<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_51: (in 0<64> : word64)
  Class: Eq_51
  DataType: word64
  OrigDataType: word64
T_52: (in r0 + 0<64> : word64)
  Class: Eq_52
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 word64)
T_53: (in Mem0[r0 + 0<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_54: (in __write_cpr2(0x1F<8>, *r0) : void)
  Class: Eq_42
  DataType: void
  OrigDataType: void
T_55: (in register_tm_clones : ptr64)
  Class: Eq_55
  DataType: (ptr64 Eq_55)
  OrigDataType: (ptr64 (fn T_59 (T_30, T_31)))
T_56: (in signature of register_tm_clones : void)
  Class: Eq_55
  DataType: (ptr64 Eq_55)
  OrigDataType: 
T_57: (in r0 : (ptr64 word64))
  Class: Eq_30
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_35 t0000)))
T_58: (in ra : (ptr64 code))
  Class: Eq_31
  DataType: (ptr64 code)
  OrigDataType: word64
T_59: (in register_tm_clones(r0, ra) : void)
  Class: Eq_59
  DataType: void
  OrigDataType: void
T_60: (in r2_11 : Eq_60)
  Class: Eq_60
  DataType: Eq_60
  OrigDataType: (union (int64 u1) (uint64 u0))
T_61: (in 0x109F8<64> : word64)
  Class: Eq_61
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_62 t0000)))
T_62: (in Mem0[0x109F8<64>:word64] : word64)
  Class: Eq_62
  DataType: word64
  OrigDataType: word64
T_63: (in 0x109F0<64> : word64)
  Class: Eq_63
  DataType: (ptr64 (ptr64 Eq_64))
  OrigDataType: (ptr64 (struct (0 T_64 t0000)))
T_64: (in Mem0[0x109F0<64>:word64] : word64)
  Class: Eq_64
  DataType: (ptr64 Eq_64)
  OrigDataType: word64
T_65: (in 2528<i64> : int64)
  Class: Eq_65
  DataType: int64
  OrigDataType: int64
T_66: (in Mem0[0x109F0<64>:word64] + 2528<i64> : word64)
  Class: Eq_66
  DataType: word64
  OrigDataType: word64
T_67: (in g_qw109F8 - ((char *) g_ptr109F0 + 2528<i32>) : word64)
  Class: Eq_60
  DataType: Eq_60
  OrigDataType: word64
T_68: (in __write_cpr2 : ptr64)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: (ptr64 (fn T_80 (T_69, T_79)))
T_69: (in 0<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_70: (in 0x3F<8> : byte)
  Class: Eq_70
  DataType: byte
  OrigDataType: byte
T_71: (in r2_11 >> 0x3F<8> : word64)
  Class: Eq_71
  DataType: Eq_71
  OrigDataType: (union (int64 u1) (uint64 u0))
T_72: (in 3<8> : byte)
  Class: Eq_72
  DataType: byte
  OrigDataType: byte
T_73: (in r2_11 >> 3<8> : word64)
  Class: Eq_73
  DataType: Eq_73
  OrigDataType: (union (int64 u1) (uint64 u0))
T_74: (in (r2_11 >>u 0x3F<8>) + (r2_11 >> 3<8>) : word64)
  Class: Eq_74
  DataType: Eq_74
  OrigDataType: (union (int64 u1) (uint64 u0))
T_75: (in 1<8> : byte)
  Class: Eq_75
  DataType: byte
  OrigDataType: byte
T_76: (in (r2_11 >>u 0x3F<8>) + (r2_11 >> 3<8>) >> 1<8> : word64)
  Class: Eq_76
  DataType: (ptr64 Eq_76)
  OrigDataType: (ptr64 (struct (4 T_79 t0004)))
T_77: (in 4<64> : word64)
  Class: Eq_77
  DataType: word64
  OrigDataType: word64
T_78: (in ((r2_11 >>u 0x3F<8>) + (r2_11 >> 3<8>) >> 1<8>) + 4<64> : word64)
  Class: Eq_78
  DataType: int64
  OrigDataType: int64
T_79: (in Mem0[((r2_11 >>u 0x3F<8>) + (r2_11 >> 3<8>) >> 1<8>) + 4<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_80: (in __write_cpr2(0<8>, Mem0[((r2_11 >>u 0x3F<8>) + (r2_11 >> 3<8>) >> 1<8>) + 4<64>:word64]) : void)
  Class: Eq_42
  DataType: void
  OrigDataType: void
T_81: (in __write_cpr2 : ptr64)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: (ptr64 (fn T_88 (T_82, T_87)))
T_82: (in 0<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_83: (in 0x10A48<64> : word64)
  Class: Eq_83
  DataType: (ptr64 (ptr64 Eq_84))
  OrigDataType: (ptr64 (struct (0 T_84 t0000)))
T_84: (in Mem0[0x10A48<64>:word64] : word64)
  Class: Eq_84
  DataType: (ptr64 Eq_84)
  OrigDataType: (ptr64 (struct (2 T_87 t0002)))
T_85: (in 2<64> : word64)
  Class: Eq_85
  DataType: word64
  OrigDataType: word64
T_86: (in Mem0[0x10A48<64>:word64] + 2<64> : word64)
  Class: Eq_86
  DataType: word64
  OrigDataType: word64
T_87: (in Mem0[Mem0[0x10A48<64>:word64] + 2<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_88: (in __write_cpr2(0<8>, g_ptr10A48->qw0002) : void)
  Class: Eq_42
  DataType: void
  OrigDataType: void
T_89: (in __write_cpr2 : ptr64)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: (ptr64 (fn T_94 (T_90, T_93)))
T_90: (in 0x19<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_91: (in 0<64> : word64)
  Class: Eq_91
  DataType: word64
  OrigDataType: word64
T_92: (in r0 + 0<64> : word64)
  Class: Eq_92
  DataType: word64
  OrigDataType: word64
T_93: (in Mem0[r0 + 0<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_94: (in __write_cpr2(0x19<8>, *r0) : void)
  Class: Eq_42
  DataType: void
  OrigDataType: void
T_95: (in __write_cpr2 : ptr64)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: (ptr64 (fn T_100 (T_96, T_99)))
T_96: (in 0x1F<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_97: (in 0<64> : word64)
  Class: Eq_97
  DataType: word64
  OrigDataType: word64
T_98: (in r0 + 0<64> : word64)
  Class: Eq_98
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 word64)
T_99: (in Mem0[r0 + 0<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_100: (in __write_cpr2(0x1F<8>, *r0) : void)
  Class: Eq_42
  DataType: void
  OrigDataType: void
T_101: (in __do_global_dtors_aux : ptr64)
  Class: Eq_101
  DataType: (ptr64 Eq_101)
  OrigDataType: (ptr64 (fn T_105 (T_57, T_58)))
T_102: (in signature of __do_global_dtors_aux : void)
  Class: Eq_101
  DataType: (ptr64 Eq_101)
  OrigDataType: 
T_103: (in r0 : (ptr64 word64))
  Class: Eq_30
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_140 t0000)))
T_104: (in ra : (ptr64 code))
  Class: Eq_31
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_105: (in __do_global_dtors_aux(r0, ra) : void)
  Class: Eq_105
  DataType: void
  OrigDataType: void
T_106: (in r18_14 : (ptr64 Eq_64))
  Class: Eq_64
  DataType: (ptr64 Eq_64)
  OrigDataType: (ptr64 (struct (A80 T_111 t0A80)))
T_107: (in 0x109F0<64> : word64)
  Class: Eq_107
  DataType: (ptr64 (ptr64 Eq_64))
  OrigDataType: (ptr64 (struct (0 T_108 t0000)))
T_108: (in Mem13[0x109F0<64>:word64] : word64)
  Class: Eq_64
  DataType: (ptr64 Eq_64)
  OrigDataType: word64
T_109: (in 0xA80<64> : word64)
  Class: Eq_109
  DataType: word64
  OrigDataType: word64
T_110: (in r18_14 + 0xA80<64> : word64)
  Class: Eq_110
  DataType: word64
  OrigDataType: word64
T_111: (in Mem18[r18_14 + 0xA80<64>:byte] : byte)
  Class: Eq_111
  DataType: byte
  OrigDataType: byte
T_112: (in CONVERT(Mem18[r18_14 + 0xA80<64>:byte], byte, word64) : word64)
  Class: Eq_112
  DataType: word64
  OrigDataType: word64
T_113: (in 0<64> : word64)
  Class: Eq_112
  DataType: word64
  OrigDataType: word64
T_114: (in (word64) r18_14->b0A80 != 0<64> : bool)
  Class: Eq_114
  DataType: bool
  OrigDataType: bool
T_115: (in __write_cpr2 : ptr64)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: (ptr64 (fn T_122 (T_116, T_121)))
T_116: (in 0<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_117: (in 0x10A70<64> : word64)
  Class: Eq_117
  DataType: (ptr64 (ptr64 Eq_118))
  OrigDataType: (ptr64 (struct (0 T_118 t0000)))
T_118: (in Mem22[0x10A70<64>:word64] : word64)
  Class: Eq_118
  DataType: (ptr64 Eq_118)
  OrigDataType: (ptr64 (struct (4 T_121 t0004)))
T_119: (in 4<64> : word64)
  Class: Eq_119
  DataType: word64
  OrigDataType: word64
T_120: (in Mem22[0x10A70<64>:word64] + 4<64> : word64)
  Class: Eq_120
  DataType: word64
  OrigDataType: word64
T_121: (in Mem22[Mem22[0x10A70<64>:word64] + 4<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_122: (in __write_cpr2(0<8>, g_ptr10A70->qw0004) : void)
  Class: Eq_42
  DataType: void
  OrigDataType: void
T_123: (in r2_24 : word64)
  Class: Eq_123
  DataType: word64
  OrigDataType: word64
T_124: (in 0x10A00<64> : word64)
  Class: Eq_124
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_125 t0000)))
T_125: (in Mem22[0x10A00<64>:word64] : word64)
  Class: Eq_123
  DataType: word64
  OrigDataType: word64
T_126: (in 0x10A70<64> : word64)
  Class: Eq_126
  DataType: (ptr64 (ptr64 Eq_118))
  OrigDataType: (ptr64 (struct (0 T_127 t0000)))
T_127: (in Mem22[0x10A70<64>:word64] : word64)
  Class: Eq_118
  DataType: (ptr64 Eq_118)
  OrigDataType: (ptr64 code)
T_128: (in 0x109F0<64> : word64)
  Class: Eq_128
  DataType: (ptr64 (ptr64 Eq_64))
  OrigDataType: (ptr64 (struct (0 T_129 t0000)))
T_129: (in Mem22[0x109F0<64>:word64] : word64)
  Class: Eq_64
  DataType: (ptr64 Eq_64)
  OrigDataType: (ptr64 (struct (A88 T_132 t0A88)))
T_130: (in 0xA88<64> : word64)
  Class: Eq_130
  DataType: word64
  OrigDataType: word64
T_131: (in Mem22[0x109F0<64>:word64] + 0xA88<64> : word64)
  Class: Eq_131
  DataType: word64
  OrigDataType: word64
T_132: (in Mem22[Mem22[0x109F0<64>:word64] + 0xA88<64>:word64] : word64)
  Class: Eq_132
  DataType: int64
  OrigDataType: int64
T_133: (in 0<64> : word64)
  Class: Eq_132
  DataType: int64
  OrigDataType: int64
T_134: (in g_ptr109F0->qw0A88 <= 0<64> : bool)
  Class: Eq_134
  DataType: bool
  OrigDataType: bool
T_135: (in __read_cpr2 : ptr64)
  Class: Eq_17
  DataType: (ptr64 Eq_17)
  OrigDataType: (ptr64 (fn T_137 (T_136)))
T_136: (in 0x19<8> : byte)
  Class: Eq_19
  DataType: byte
  OrigDataType: byte
T_137: (in __read_cpr2(0x19<8>) : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_138: (in 0<64> : word64)
  Class: Eq_138
  DataType: word64
  OrigDataType: word64
T_139: (in r0 + 0<64> : word64)
  Class: Eq_139
  DataType: word64
  OrigDataType: word64
T_140: (in Mem44[r0 + 0<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_141: (in 1<8> : byte)
  Class: Eq_111
  DataType: byte
  OrigDataType: byte
T_142: (in 0xA80<64> : word64)
  Class: Eq_142
  DataType: word64
  OrigDataType: word64
T_143: (in r18_14 + 0xA80<64> : word64)
  Class: Eq_143
  DataType: (ptr64 byte)
  OrigDataType: (ptr64 byte)
T_144: (in Mem46[r18_14 + 0xA80<64>:byte] : byte)
  Class: Eq_111
  DataType: byte
  OrigDataType: byte
T_145: (in r0 : (ptr64 word64))
  Class: Eq_145
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_151 t0000)))
T_146: (in ra : (ptr64 code))
  Class: Eq_146
  DataType: (ptr64 code)
  OrigDataType: word64
T_147: (in __write_cpr2 : ptr64)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: (ptr64 (fn T_152 (T_148, T_151)))
T_148: (in 0x19<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_149: (in 0<64> : word64)
  Class: Eq_149
  DataType: word64
  OrigDataType: word64
T_150: (in r0 + 0<64> : word64)
  Class: Eq_150
  DataType: word64
  OrigDataType: word64
T_151: (in Mem0[r0 + 0<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_152: (in __write_cpr2(0x19<8>, *r0) : void)
  Class: Eq_42
  DataType: void
  OrigDataType: void
T_153: (in hexdump : ptr64)
  Class: Eq_153
  DataType: (ptr64 Eq_153)
  OrigDataType: (ptr64 (fn T_157 (T_145, T_146)))
T_154: (in signature of hexdump : void)
  Class: Eq_153
  DataType: (ptr64 Eq_153)
  OrigDataType: 
T_155: (in r0 : (ptr64 word64))
  Class: Eq_145
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_162 t0000)))
T_156: (in ra : (ptr64 code))
  Class: Eq_146
  DataType: (ptr64 code)
  OrigDataType: word64
T_157: (in hexdump(r0, ra) : void)
  Class: Eq_157
  DataType: void
  OrigDataType: void
T_158: (in __write_cpr2 : ptr64)
  Class: Eq_32
  DataType: (ptr64 Eq_32)
  OrigDataType: (ptr64 (fn T_163 (T_159, T_162)))
T_159: (in 0x1F<8> : byte)
  Class: Eq_34
  DataType: byte
  OrigDataType: byte
T_160: (in 0<64> : word64)
  Class: Eq_160
  DataType: word64
  OrigDataType: word64
T_161: (in r0 + 0<64> : word64)
  Class: Eq_161
  DataType: word64
  OrigDataType: word64
T_162: (in Mem0[r0 + 0<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_163: (in __write_cpr2(0x1F<8>, *r0) : void)
  Class: Eq_42
  DataType: void
  OrigDataType: void
T_164: (in __do_global_ctors_aux : ptr64)
  Class: Eq_164
  DataType: (ptr64 Eq_164)
  OrigDataType: (ptr64 (fn T_168 (T_155, T_156)))
T_165: (in signature of __do_global_ctors_aux : void)
  Class: Eq_164
  DataType: (ptr64 Eq_164)
  OrigDataType: 
T_166: (in r0 : (ptr64 word64))
  Class: Eq_145
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_179 t0000)))
T_167: (in ra : (ptr64 code))
  Class: Eq_146
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_168: (in __do_global_ctors_aux(r0, ra) : void)
  Class: Eq_168
  DataType: void
  OrigDataType: void
T_169: (in r16_21 : (ptr64 Eq_169))
  Class: Eq_169
  DataType: (ptr64 Eq_169)
  OrigDataType: (ptr64 (struct 0008 (FFFFFFF8 word64 qwFFFFFFF8) (0 word64 qw0000)))
T_170: (in 0x109F0<64> : word64)
  Class: Eq_170
  DataType: (ptr64 (ptr64 Eq_64))
  OrigDataType: (ptr64 (struct (0 T_171 t0000)))
T_171: (in Mem14[0x109F0<64>:word64] : word64)
  Class: Eq_64
  DataType: (ptr64 Eq_64)
  OrigDataType: word64
T_172: (in 2496<i64> : int64)
  Class: Eq_172
  DataType: int64
  OrigDataType: int64
T_173: (in Mem14[0x109F0<64>:word64] + 2496<i64> : word64)
  Class: Eq_169
  DataType: (ptr64 Eq_169)
  OrigDataType: word64
T_174: (in __read_cpr2 : ptr64)
  Class: Eq_17
  DataType: (ptr64 Eq_17)
  OrigDataType: (ptr64 (fn T_176 (T_175)))
T_175: (in 0x19<8> : byte)
  Class: Eq_19
  DataType: byte
  OrigDataType: byte
T_176: (in __read_cpr2(0x19<8>) : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_177: (in 0<64> : word64)
  Class: Eq_177
  DataType: word64
  OrigDataType: word64
T_178: (in r0 + 0<64> : word64)
  Class: Eq_178
  DataType: word64
  OrigDataType: word64
T_179: (in Mem23[r0 + 0<64>:word64] : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_180: (in 0xFFFFFFFFFFFFFFF8<64> : word64)
  Class: Eq_180
  DataType: word64
  OrigDataType: word64
T_181: (in r16_21 + 0xFFFFFFFFFFFFFFF8<64> : word64)
  Class: Eq_181
  DataType: word64
  OrigDataType: word64
T_182: (in Mem23[r16_21 + 0xFFFFFFFFFFFFFFF8<64>:word64] : word64)
  Class: Eq_182
  DataType: int64
  OrigDataType: word64
T_183: (in -1<i64> : int64)
  Class: Eq_182
  DataType: int64
  OrigDataType: int64
T_184: (in r16_21->qwFFFFFFF8 != -1<i64> : bool)
  Class: Eq_184
  DataType: bool
  OrigDataType: bool
T_185: (in -8<i64> : int64)
  Class: Eq_185
  DataType: int64
  OrigDataType: int64
T_186: (in r16_21 + -8<i64> : word64)
  Class: Eq_169
  DataType: (ptr64 Eq_169)
  OrigDataType: (ptr64 word64)
T_187: (in r28 : (ptr64 Eq_187))
  Class: Eq_187
  DataType: (ptr64 Eq_187)
  OrigDataType: (ptr64 (struct (FFFF8010 T_191 tFFFF8010)))
T_188: (in ra : (ptr64 code))
  Class: Eq_188
  DataType: (ptr64 code)
  OrigDataType: word64
T_189: (in 0xFFFFFFFFFFFF8010<64> : word64)
  Class: Eq_189
  DataType: word64
  OrigDataType: word64
T_190: (in r28 + 0xFFFFFFFFFFFF8010<64> : word64)
  Class: Eq_190
  DataType: word64
  OrigDataType: word64
T_191: (in Mem0[r28 + 0xFFFFFFFFFFFF8010<64>:word64] : word64)
  Class: Eq_191
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_192: (in _fini : ptr64)
  Class: Eq_192
  DataType: (ptr64 Eq_192)
  OrigDataType: (ptr64 (fn T_195 (T_188)))
T_193: (in signature of _fini : void)
  Class: Eq_192
  DataType: (ptr64 Eq_192)
  OrigDataType: 
T_194: (in ra : (ptr64 code))
  Class: Eq_188
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_195: (in _fini(ra) : void)
  Class: Eq_195
  DataType: void
  OrigDataType: void
T_196: (in 0000000000020988 : ptr64)
  Class: Eq_196
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_197 t0000)))
T_197: (in Mem10[0x0000000000020988<p64>:word64] : word64)
  Class: Eq_197
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
*/
typedef struct Globals {
	Eq_64 t10000;	// 10000
	struct Eq_64 * ptr109F0;	// 109F0
	word64 qw109F8;	// 109F8
	word64 qw10A00;	// 10A00
	struct Eq_84 * ptr10A48;	// 10A48
	<anonymous> * ptr10A50;	// 10A50
	<anonymous> * ptr10A60;	// 10A60
	struct Eq_38 * ptr10A68;	// 10A68
	struct Eq_118 * ptr10A70;	// 10A70
	<anonymous> * ptr20978;	// 20978
	<anonymous> * ptr20980;	// 20980
	<anonymous> * ptr20988;	// 20988
} Eq_1;

typedef word64 (Eq_17)(byte);

typedef void (Eq_32)(byte, word64);

typedef struct Eq_38 {
	word64 qw0002;	// 2
} Eq_38;

typedef void (Eq_55)(word64 *, code *);

typedef union Eq_60 {
	int64 u0;
	uint64 u1;
} Eq_60;

typedef struct Eq_64 {
	byte b0A80;	// A80
	int64 qw0A88;	// A88
} Eq_64;

typedef union Eq_71 {
	int64 u0;
	uint64 u1;
} Eq_71;

typedef union Eq_73 {
	int64 u0;
	uint64 u1;
} Eq_73;

typedef union Eq_74 {
	int64 u0;
	uint64 u1;
} Eq_74;

typedef struct Eq_76 {
	word64 qw0004;	// 4
} Eq_76;

typedef struct Eq_84 {
	word64 qw0002;	// 2
} Eq_84;

typedef void (Eq_101)(word64 *, code *);

typedef struct Eq_118 {
	<anonymous> t0000;	// 0
	word64 qw0004;	// 4
} Eq_118;

typedef void (Eq_153)(word64 *, code *);

typedef void (Eq_164)(word64 *, code *);

typedef struct Eq_169 {	// size: 8 8
	word64 qwFFFFFFF8;	// FFFFFFF8
	word64 qw0000;	// 0
} Eq_169;

typedef struct Eq_187 {
	<anonymous> * ptrFFFF8010;	// FFFF8010
} Eq_187;

typedef void (Eq_192)(code *);

