// hexdump-Os_got.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

<anonymous> * g_ptr10FC0 = null;
word64 g_qw10FC8 = 0x00;
word64 g_qw10FD0 = 0x00;
<anonymous> * g_ptr10FE0 = null;
