// hexdump-O2_rdata.c
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O2.h"

word64 g_qw61FC4000 = 0x61FC14B0;
void g_v61FC4060 = ??void??;
word32 * g_ptr61FC4170 = &g_dw61FC3030;
Eq_n (* g_ptr61FC4180)[] = &g_a61FC2310;
union Eq_n * g_ptr61FC4190 = &g_t61FC44D0;
union Eq_n * g_ptr61FC41A0 = &g_t61FC44D0;
word64 * g_ptr61FC41B0 = &g_qw61FC4000;
struct Eq_n * g_ptr61FC41C0 = &g_t61FC0000;
union Eq_n * g_ptr61FC41D0 = &g_t61FC3024;
uint64 * g_ptr61FC41E0 = &g_qw61FC7030;
word32 * g_ptr61FC41F0 = &g_dw61FC7038;
PVFV * g_ptr61FC4200 = &g_t61FCA000;
PVFV * g_ptr61FC4210 = &g_t61FCA008;
PVFV * g_ptr61FC4220 = &g_t61FCA010;
PVFV * g_ptr61FC4230 = &g_t61FCA020;
word32 * g_ptr61FC4240 = &g_dw61FC7050;
