// hexdump-Os_rdata.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

word64 g_qw6A4C4000 = 0x6A4C14B0;
void g_v6A4C4060 = ??void??;
word32 * g_ptr6A4C4170 = &g_dw6A4C3030;
Eq_n (* g_ptr6A4C4180)[] = &g_a6A4C2310;
union Eq_n * g_ptr6A4C4190 = &g_t6A4C44D0;
union Eq_n * g_ptr6A4C41A0 = &g_t6A4C44D0;
word64 * g_ptr6A4C41B0 = &g_qw6A4C4000;
struct Eq_n * g_ptr6A4C41C0 = &g_t6A4C0000;
union Eq_n * g_ptr6A4C41D0 = &g_t6A4C3024;
uint64 * g_ptr6A4C41E0 = &g_qw6A4C7030;
word32 * g_ptr6A4C41F0 = &g_dw6A4C7038;
PVFV * g_ptr6A4C4200 = &g_t6A4CA000;
PVFV * g_ptr6A4C4210 = &g_t6A4CA008;
PVFV * g_ptr6A4C4220 = &g_t6A4CA010;
PVFV * g_ptr6A4C4230 = &g_t6A4CA020;
word32 * g_ptr6A4C4240 = &g_dw6A4C7050;
