// hexdump-Os.h
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (FFFFFFFF code tFFFFFFFF) (774 code t0774) (1FEF8 int32 dw1FEF8) (1FEFC (ptr32 code) ptr1FEFC) (1FF00 int32 dw1FF00) (1FF04 (ptr32 code) ptr1FF04) (1FF08 (ptr32 byte) ptr1FF08) (1FF0C word32 dw1FF0C) (1FF14 int32 dw1FF14) (1FF18 (ptr32 (arr (ptr32 code))) ptr1FF18) (1FF1C (ptr32 int32) ptr1FF1C) (1FF24 (ptr32 Eq_183) ptr1FF24) (1FFF0 word32 dw1FFF0) (1FFF4 (struct "Eq_16" (10 (ptr32 code) ptr0010)) t1FFF4))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_7: (fn void (word32))
	T_7 (in frame_dummy : ptr32)
	T_8 (in signature of frame_dummy : void)
Eq_11: (fn void ())
	T_11 (in __do_global_ctors_aux : ptr32)
	T_12 (in signature of __do_global_ctors_aux : void)
Eq_14: (fn void ((ptr32 Eq_16)))
	T_14 (in fn00000740 : ptr32)
	T_15 (in signature of fn00000740 : void)
Eq_16: (struct "Eq_16" (10 (ptr32 code) ptr0010))
	T_16 (in r30 : (ptr32 Eq_16))
	T_17 (in 0001FFF4 : ptr32)
Eq_21: (struct "Eq_21" (0 word32 dw0000) (4 word32 dw0004))
	T_21 (in v5 : word32)
Eq_28: (fn void ((ptr32 Eq_30)))
	T_28 (in fn00000750 : ptr32)
	T_29 (in signature of fn00000750 : void)
Eq_30: (struct "Eq_30" (FFFF80E8 (ptr32 code) ptrFFFF80E8))
	T_30 (in r30 : (ptr32 Eq_30))
	T_31 (in 00027F20 : ptr32)
Eq_33: (fn void ((ptr32 Eq_35)))
	T_33 (in fn00000760 : ptr32)
	T_34 (in signature of fn00000760 : void)
Eq_35: (struct "Eq_35" (FFFF80EC (ptr32 code) ptrFFFF80EC))
	T_35 (in r30 : (ptr32 Eq_35))
	T_36 (in 00027F20 : ptr32)
Eq_38: (fn void ())
	T_38 (in _restgpr_30_x : ptr32)
	T_39 (in signature of _restgpr_30_x : void)
	T_178 (in _restgpr_30_x : ptr32)
Eq_102: (fn void ((ptr32 Eq_104)))
	T_102 (in fn00000730 : ptr32)
	T_103 (in signature of fn00000730 : void)
Eq_104: (struct "Eq_104" (FFFF8108 (ptr32 code) ptrFFFF8108))
	T_104 (in r30 : (ptr32 Eq_104))
	T_105 (in 00027EF8 : ptr32)
Eq_107: (fn void ())
	T_107 (in deregister_tm_clones : ptr32)
	T_108 (in signature of deregister_tm_clones : void)
Eq_130: (fn void (word32))
	T_130 (in register_tm_clones : ptr32)
	T_131 (in signature of register_tm_clones : void)
Eq_133: (fn void ())
	T_133 (in _restgpr_15_x : ptr32)
	T_134 (in signature of _restgpr_15_x : void)
Eq_136: (fn void ())
	T_136 (in _restgpr_16_x : ptr32)
	T_137 (in signature of _restgpr_16_x : void)
Eq_139: (fn void ())
	T_139 (in _restgpr_17_x : ptr32)
	T_140 (in signature of _restgpr_17_x : void)
Eq_142: (fn void ())
	T_142 (in _restgpr_18_x : ptr32)
	T_143 (in signature of _restgpr_18_x : void)
Eq_145: (fn void ())
	T_145 (in _restgpr_19_x : ptr32)
	T_146 (in signature of _restgpr_19_x : void)
Eq_148: (fn void ())
	T_148 (in _restgpr_20_x : ptr32)
	T_149 (in signature of _restgpr_20_x : void)
Eq_151: (fn void ())
	T_151 (in _restgpr_21_x : ptr32)
	T_152 (in signature of _restgpr_21_x : void)
Eq_154: (fn void ())
	T_154 (in _restgpr_22_x : ptr32)
	T_155 (in signature of _restgpr_22_x : void)
Eq_157: (fn void ())
	T_157 (in _restgpr_23_x : ptr32)
	T_158 (in signature of _restgpr_23_x : void)
Eq_160: (fn void ())
	T_160 (in _restgpr_24_x : ptr32)
	T_161 (in signature of _restgpr_24_x : void)
Eq_163: (fn void ())
	T_163 (in _restgpr_25_x : ptr32)
	T_164 (in signature of _restgpr_25_x : void)
Eq_166: (fn void ())
	T_166 (in _restgpr_26_x : ptr32)
	T_167 (in signature of _restgpr_26_x : void)
Eq_169: (fn void ())
	T_169 (in _restgpr_27_x : ptr32)
	T_170 (in signature of _restgpr_27_x : void)
Eq_172: (fn void ())
	T_172 (in _restgpr_28_x : ptr32)
	T_173 (in signature of _restgpr_28_x : void)
Eq_175: (fn void ())
	T_175 (in _restgpr_29_x : ptr32)
	T_176 (in signature of _restgpr_29_x : void)
Eq_180: (fn void ())
	T_180 (in _restgpr_31_x : ptr32)
	T_181 (in signature of _restgpr_31_x : void)
Eq_183: (struct "Eq_183" (FFFFFFFC (ptr32 code) ptrFFFFFFFC))
	T_183 (in r31_16 : (ptr32 Eq_183))
	T_185 (in Mem13[0x0001FF24<p32>:word32] : word32)
Eq_219: (fn void ())
	T_219 (in __do_global_dtors_aux : ptr32)
	T_220 (in signature of __do_global_dtors_aux : void)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in xer : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in 0001FFF0 : ptr32)
  Class: Eq_3
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_4 t0000)))
T_4: (in Mem9[0x0001FFF0<p32>:word32] : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in 0<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_6: (in g_dw1FFF0 == 0<32> : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_7: (in frame_dummy : ptr32)
  Class: Eq_7
  DataType: (ptr32 Eq_7)
  OrigDataType: (ptr32 (fn T_10 (T_2)))
T_8: (in signature of frame_dummy : void)
  Class: Eq_7
  DataType: (ptr32 Eq_7)
  OrigDataType: 
T_9: (in xer : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_10: (in frame_dummy(xer) : void)
  Class: Eq_10
  DataType: void
  OrigDataType: void
T_11: (in __do_global_ctors_aux : ptr32)
  Class: Eq_11
  DataType: (ptr32 Eq_11)
  OrigDataType: (ptr32 (fn T_13 ()))
T_12: (in signature of __do_global_ctors_aux : void)
  Class: Eq_11
  DataType: (ptr32 Eq_11)
  OrigDataType: 
T_13: (in __do_global_ctors_aux() : void)
  Class: Eq_13
  DataType: void
  OrigDataType: void
T_14: (in fn00000740 : ptr32)
  Class: Eq_14
  DataType: (ptr32 Eq_14)
  OrigDataType: (ptr32 (fn T_18 (T_17)))
T_15: (in signature of fn00000740 : void)
  Class: Eq_14
  DataType: (ptr32 Eq_14)
  OrigDataType: 
T_16: (in r30 : (ptr32 Eq_16))
  Class: Eq_16
  DataType: (ptr32 Eq_16)
  OrigDataType: (ptr32 (struct (10 T_210 t0010)))
T_17: (in 0001FFF4 : ptr32)
  Class: Eq_16
  DataType: (ptr32 Eq_16)
  OrigDataType: ptr32
T_18: (in fn00000740(&g_t1FFF4) : void)
  Class: Eq_18
  DataType: void
  OrigDataType: void
T_19: (in r30 : word32)
  Class: Eq_19
  DataType: word32
  OrigDataType: word32
T_20: (in r31 : word32)
  Class: Eq_20
  DataType: word32
  OrigDataType: word32
T_21: (in v5 : word32)
  Class: Eq_21
  DataType: (ptr32 Eq_21)
  OrigDataType: (ptr32 (struct (0 T_24 t0000) (4 T_27 t0004)))
T_22: (in 0<32> : word32)
  Class: Eq_22
  DataType: word32
  OrigDataType: word32
T_23: (in v5 + 0<32> : word32)
  Class: Eq_23
  DataType: word32
  OrigDataType: word32
T_24: (in Mem10[v5 + 0<32>:word32] : word32)
  Class: Eq_19
  DataType: word32
  OrigDataType: word32
T_25: (in 4<i32> : int32)
  Class: Eq_25
  DataType: int32
  OrigDataType: int32
T_26: (in v5 + 4<i32> : word32)
  Class: Eq_26
  DataType: ptr32
  OrigDataType: ptr32
T_27: (in Mem13[v5 + 4<i32>:word32] : word32)
  Class: Eq_20
  DataType: word32
  OrigDataType: word32
T_28: (in fn00000750 : ptr32)
  Class: Eq_28
  DataType: (ptr32 Eq_28)
  OrigDataType: (ptr32 (fn T_32 (T_31)))
T_29: (in signature of fn00000750 : void)
  Class: Eq_28
  DataType: (ptr32 Eq_28)
  OrigDataType: 
T_30: (in r30 : (ptr32 Eq_30))
  Class: Eq_30
  DataType: (ptr32 Eq_30)
  OrigDataType: (ptr32 (struct (FFFF80E8 T_214 tFFFF80E8)))
T_31: (in 00027F20 : ptr32)
  Class: Eq_30
  DataType: (ptr32 Eq_30)
  OrigDataType: ptr32
T_32: (in fn00000750((struct Eq_30 *) 0x27F20<u32>) : void)
  Class: Eq_32
  DataType: void
  OrigDataType: void
T_33: (in fn00000760 : ptr32)
  Class: Eq_33
  DataType: (ptr32 Eq_33)
  OrigDataType: (ptr32 (fn T_37 (T_36)))
T_34: (in signature of fn00000760 : void)
  Class: Eq_33
  DataType: (ptr32 Eq_33)
  OrigDataType: 
T_35: (in r30 : (ptr32 Eq_35))
  Class: Eq_35
  DataType: (ptr32 Eq_35)
  OrigDataType: (ptr32 (struct (FFFF80EC T_218 tFFFF80EC)))
T_36: (in 00027F20 : ptr32)
  Class: Eq_35
  DataType: (ptr32 Eq_35)
  OrigDataType: ptr32
T_37: (in fn00000760((struct Eq_35 *) 0x27F20<u32>) : void)
  Class: Eq_37
  DataType: void
  OrigDataType: void
T_38: (in _restgpr_30_x : ptr32)
  Class: Eq_38
  DataType: (ptr32 Eq_38)
  OrigDataType: (ptr32 (fn T_40 ()))
T_39: (in signature of _restgpr_30_x : void)
  Class: Eq_38
  DataType: (ptr32 Eq_38)
  OrigDataType: 
T_40: (in _restgpr_30_x() : void)
  Class: Eq_40
  DataType: void
  OrigDataType: void
T_41: (in 0001FF00 : ptr32)
  Class: Eq_41
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_42 t0000)))
T_42: (in Mem12[0x0001FF00<p32>:word32] : word32)
  Class: Eq_42
  DataType: int32
  OrigDataType: word32
T_43: (in 0001FEF8 : ptr32)
  Class: Eq_43
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_44 t0000)))
T_44: (in Mem12[0x0001FEF8<p32>:word32] : word32)
  Class: Eq_42
  DataType: int32
  OrigDataType: word32
T_45: (in g_dw1FF00 == g_dw1FEF8 : bool)
  Class: Eq_45
  DataType: bool
  OrigDataType: bool
T_46: (in r9_17 : (ptr32 code))
  Class: Eq_46
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_47: (in 0001FEFC : ptr32)
  Class: Eq_47
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_48 t0000)))
T_48: (in Mem12[0x0001FEFC<p32>:word32] : word32)
  Class: Eq_46
  DataType: (ptr32 code)
  OrigDataType: word32
T_49: (in 0<32> : word32)
  Class: Eq_46
  DataType: (ptr32 code)
  OrigDataType: word32
T_50: (in r9_17 == null : bool)
  Class: Eq_50
  DataType: bool
  OrigDataType: bool
T_51: (in xer : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_52: (in 0001FF00 : ptr32)
  Class: Eq_52
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_53 t0000)))
T_53: (in Mem12[0x0001FF00<p32>:word32] : word32)
  Class: Eq_42
  DataType: int32
  OrigDataType: int32
T_54: (in 0001FEF8 : ptr32)
  Class: Eq_54
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_55 t0000)))
T_55: (in Mem12[0x0001FEF8<p32>:word32] : word32)
  Class: Eq_42
  DataType: int32
  OrigDataType: int32
T_56: (in g_dw1FF00 - g_dw1FEF8 : word32)
  Class: Eq_56
  DataType: int32
  OrigDataType: int32
T_57: (in 3<32> : word32)
  Class: Eq_57
  DataType: word32
  OrigDataType: word32
T_58: (in g_dw1FF00 - g_dw1FEF8 >> 3<32> : word32)
  Class: Eq_58
  DataType: int32
  OrigDataType: int32
T_59: (in (g_dw1FF00 - g_dw1FEF8 >> 3<32>) + xer : word32)
  Class: Eq_59
  DataType: int32
  OrigDataType: int32
T_60: (in 0<32> : word32)
  Class: Eq_59
  DataType: int32
  OrigDataType: word32
T_61: (in (g_dw1FF00 - g_dw1FEF8 >> 3<32>) + xer == 0<32> : bool)
  Class: Eq_61
  DataType: bool
  OrigDataType: bool
T_62: (in r9_23 : (ptr32 code))
  Class: Eq_62
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_63: (in 0001FF04 : ptr32)
  Class: Eq_63
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_64 t0000)))
T_64: (in Mem12[0x0001FF04<p32>:word32] : word32)
  Class: Eq_62
  DataType: (ptr32 code)
  OrigDataType: word32
T_65: (in 0<32> : word32)
  Class: Eq_62
  DataType: (ptr32 code)
  OrigDataType: word32
T_66: (in r9_23 == null : bool)
  Class: Eq_66
  DataType: bool
  OrigDataType: bool
T_67: (in r9_29 : word32)
  Class: Eq_67
  DataType: word32
  OrigDataType: word32
T_68: (in r27_16 : (ptr32 byte))
  Class: Eq_68
  DataType: (ptr32 byte)
  OrigDataType: (ptr32 (struct (0 T_73 t0000)))
T_69: (in 0001FF08 : ptr32)
  Class: Eq_69
  DataType: (ptr32 (ptr32 byte))
  OrigDataType: (ptr32 (struct (0 T_70 t0000)))
T_70: (in Mem13[0x0001FF08<p32>:word32] : word32)
  Class: Eq_68
  DataType: (ptr32 byte)
  OrigDataType: word32
T_71: (in 0<32> : word32)
  Class: Eq_71
  DataType: word32
  OrigDataType: word32
T_72: (in r27_16 + 0<32> : word32)
  Class: Eq_72
  DataType: word32
  OrigDataType: word32
T_73: (in Mem13[r27_16 + 0<32>:byte] : byte)
  Class: Eq_73
  DataType: byte
  OrigDataType: byte
T_74: (in CONVERT(Mem13[r27_16 + 0<32>:byte], byte, word32) : word32)
  Class: Eq_74
  DataType: word32
  OrigDataType: word32
T_75: (in 0<32> : word32)
  Class: Eq_74
  DataType: word32
  OrigDataType: word32
T_76: (in (word32) *r27_16 != 0<32> : bool)
  Class: Eq_76
  DataType: bool
  OrigDataType: bool
T_77: (in 0001FF0C : ptr32)
  Class: Eq_77
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_78 t0000)))
T_78: (in Mem13[0x0001FF0C<p32>:word32] : word32)
  Class: Eq_78
  DataType: word32
  OrigDataType: word32
T_79: (in 0<32> : word32)
  Class: Eq_78
  DataType: word32
  OrigDataType: word32
T_80: (in g_dw1FF0C == 0<32> : bool)
  Class: Eq_80
  DataType: bool
  OrigDataType: bool
T_81: (in r31_35 : (ptr32 int32))
  Class: Eq_81
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_87 t0000)))
T_82: (in 0001FF1C : ptr32)
  Class: Eq_82
  DataType: (ptr32 (ptr32 int32))
  OrigDataType: (ptr32 (struct (0 T_83 t0000)))
T_83: (in Mem25[0x0001FF1C<p32>:word32] : word32)
  Class: Eq_81
  DataType: (ptr32 int32)
  OrigDataType: word32
T_84: (in r28_36 : (arr (ptr32 code)))
  Class: Eq_84
  DataType: (ptr32 (arr (ptr32 code)))
  OrigDataType: (ptr32 (struct (0 (arr T_222) a0000)))
T_85: (in 0001FF18 : ptr32)
  Class: Eq_85
  DataType: (ptr32 (ptr32 (arr (ptr32 code))))
  OrigDataType: (ptr32 (struct (0 T_86 t0000)))
T_86: (in Mem25[0x0001FF18<p32>:word32] : word32)
  Class: Eq_84
  DataType: (ptr32 (arr (ptr32 code)))
  OrigDataType: word32
T_87: (in r9_39 : int32)
  Class: Eq_87
  DataType: int32
  OrigDataType: int32
T_88: (in 0<32> : word32)
  Class: Eq_88
  DataType: word32
  OrigDataType: word32
T_89: (in r31_35 + 0<32> : word32)
  Class: Eq_89
  DataType: word32
  OrigDataType: word32
T_90: (in Mem25[r31_35 + 0<32>:word32] : word32)
  Class: Eq_87
  DataType: int32
  OrigDataType: word32
T_91: (in r29_40 : int32)
  Class: Eq_87
  DataType: int32
  OrigDataType: int32
T_92: (in 0001FF14 : ptr32)
  Class: Eq_92
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_93 t0000)))
T_93: (in Mem25[0x0001FF14<p32>:word32] : word32)
  Class: Eq_93
  DataType: int32
  OrigDataType: int32
T_94: (in 0001FF18 : ptr32)
  Class: Eq_94
  DataType: (ptr32 (ptr32 (arr (ptr32 code))))
  OrigDataType: (ptr32 (struct (0 T_95 t0000)))
T_95: (in Mem25[0x0001FF18<p32>:word32] : word32)
  Class: Eq_84
  DataType: (ptr32 (arr (ptr32 code)))
  OrigDataType: int32
T_96: (in g_dw1FF14 - g_ptr1FF18 : word32)
  Class: Eq_96
  DataType: int32
  OrigDataType: int32
T_97: (in 2<32> : word32)
  Class: Eq_97
  DataType: word32
  OrigDataType: word32
T_98: (in g_dw1FF14 - g_ptr1FF18 >> 2<32> : word32)
  Class: Eq_98
  DataType: int32
  OrigDataType: int32
T_99: (in 0xFFFFFFFF<32> : word32)
  Class: Eq_99
  DataType: word32
  OrigDataType: word32
T_100: (in (g_dw1FF14 - g_ptr1FF18 >> 2<32>) + 0xFFFFFFFF<32> : word32)
  Class: Eq_87
  DataType: int32
  OrigDataType: int32
T_101: (in r9_39 >= r29_40 : bool)
  Class: Eq_101
  DataType: bool
  OrigDataType: bool
T_102: (in fn00000730 : ptr32)
  Class: Eq_102
  DataType: (ptr32 Eq_102)
  OrigDataType: (ptr32 (fn T_106 (T_105)))
T_103: (in signature of fn00000730 : void)
  Class: Eq_102
  DataType: (ptr32 Eq_102)
  OrigDataType: 
T_104: (in r30 : (ptr32 Eq_104))
  Class: Eq_104
  DataType: (ptr32 Eq_104)
  OrigDataType: (ptr32 (struct (FFFF8108 T_206 tFFFF8108)))
T_105: (in 00027EF8 : ptr32)
  Class: Eq_104
  DataType: (ptr32 Eq_104)
  OrigDataType: ptr32
T_106: (in fn00000730((struct Eq_104 *) 0x27EF8<u32>) : void)
  Class: Eq_106
  DataType: void
  OrigDataType: void
T_107: (in deregister_tm_clones : ptr32)
  Class: Eq_107
  DataType: (ptr32 Eq_107)
  OrigDataType: (ptr32 (fn T_109 ()))
T_108: (in signature of deregister_tm_clones : void)
  Class: Eq_107
  DataType: (ptr32 Eq_107)
  OrigDataType: 
T_109: (in deregister_tm_clones() : void)
  Class: Eq_109
  DataType: void
  OrigDataType: void
T_110: (in 1<8> : byte)
  Class: Eq_73
  DataType: byte
  OrigDataType: byte
T_111: (in 0<32> : word32)
  Class: Eq_111
  DataType: word32
  OrigDataType: word32
T_112: (in r27_16 + 0<32> : word32)
  Class: Eq_112
  DataType: (ptr32 byte)
  OrigDataType: (ptr32 byte)
T_113: (in Mem76[r27_16 + 0<32>:byte] : byte)
  Class: Eq_73
  DataType: byte
  OrigDataType: byte
T_114: (in r9_43 : int32)
  Class: Eq_87
  DataType: int32
  OrigDataType: int32
T_115: (in 1<32> : word32)
  Class: Eq_115
  DataType: word32
  OrigDataType: word32
T_116: (in r9_39 + 1<32> : word32)
  Class: Eq_87
  DataType: int32
  OrigDataType: int32
T_117: (in 0<32> : word32)
  Class: Eq_117
  DataType: word32
  OrigDataType: word32
T_118: (in r31_35 + 0<32> : word32)
  Class: Eq_118
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_119: (in Mem46[r31_35 + 0<32>:word32] : word32)
  Class: Eq_87
  DataType: int32
  OrigDataType: word32
T_120: (in r9_48 : (ptr32 code))
  Class: Eq_120
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_121: (in 4<32> : ui32)
  Class: Eq_121
  DataType: ui32
  OrigDataType: ui32
T_122: (in r9_43 * 4<32> : word32)
  Class: Eq_122
  DataType: ui32
  OrigDataType: ui32
T_123: (in r28_36[r9_43 * 4<32>] : word32)
  Class: Eq_120
  DataType: (ptr32 code)
  OrigDataType: word32
T_124: (in r3_57 : word32)
  Class: Eq_124
  DataType: word32
  OrigDataType: word32
T_125: (in r11_59 : word32)
  Class: Eq_125
  DataType: word32
  OrigDataType: word32
T_126: (in 0<32> : word32)
  Class: Eq_126
  DataType: word32
  OrigDataType: word32
T_127: (in r31_35 + 0<32> : word32)
  Class: Eq_127
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 int32)
T_128: (in Mem46[r31_35 + 0<32>:word32] : word32)
  Class: Eq_87
  DataType: int32
  OrigDataType: int32
T_129: (in r9_39 < r29_40 : bool)
  Class: Eq_129
  DataType: bool
  OrigDataType: bool
T_130: (in register_tm_clones : ptr32)
  Class: Eq_130
  DataType: (ptr32 Eq_130)
  OrigDataType: (ptr32 (fn T_132 (T_9)))
T_131: (in signature of register_tm_clones : void)
  Class: Eq_130
  DataType: (ptr32 Eq_130)
  OrigDataType: 
T_132: (in register_tm_clones(xer) : void)
  Class: Eq_132
  DataType: void
  OrigDataType: void
T_133: (in _restgpr_15_x : ptr32)
  Class: Eq_133
  DataType: (ptr32 Eq_133)
  OrigDataType: (ptr32 (fn T_135 ()))
T_134: (in signature of _restgpr_15_x : void)
  Class: Eq_133
  DataType: (ptr32 Eq_133)
  OrigDataType: 
T_135: (in _restgpr_15_x() : void)
  Class: Eq_135
  DataType: void
  OrigDataType: void
T_136: (in _restgpr_16_x : ptr32)
  Class: Eq_136
  DataType: (ptr32 Eq_136)
  OrigDataType: (ptr32 (fn T_138 ()))
T_137: (in signature of _restgpr_16_x : void)
  Class: Eq_136
  DataType: (ptr32 Eq_136)
  OrigDataType: 
T_138: (in _restgpr_16_x() : void)
  Class: Eq_138
  DataType: void
  OrigDataType: void
T_139: (in _restgpr_17_x : ptr32)
  Class: Eq_139
  DataType: (ptr32 Eq_139)
  OrigDataType: (ptr32 (fn T_141 ()))
T_140: (in signature of _restgpr_17_x : void)
  Class: Eq_139
  DataType: (ptr32 Eq_139)
  OrigDataType: 
T_141: (in _restgpr_17_x() : void)
  Class: Eq_141
  DataType: void
  OrigDataType: void
T_142: (in _restgpr_18_x : ptr32)
  Class: Eq_142
  DataType: (ptr32 Eq_142)
  OrigDataType: (ptr32 (fn T_144 ()))
T_143: (in signature of _restgpr_18_x : void)
  Class: Eq_142
  DataType: (ptr32 Eq_142)
  OrigDataType: 
T_144: (in _restgpr_18_x() : void)
  Class: Eq_144
  DataType: void
  OrigDataType: void
T_145: (in _restgpr_19_x : ptr32)
  Class: Eq_145
  DataType: (ptr32 Eq_145)
  OrigDataType: (ptr32 (fn T_147 ()))
T_146: (in signature of _restgpr_19_x : void)
  Class: Eq_145
  DataType: (ptr32 Eq_145)
  OrigDataType: 
T_147: (in _restgpr_19_x() : void)
  Class: Eq_147
  DataType: void
  OrigDataType: void
T_148: (in _restgpr_20_x : ptr32)
  Class: Eq_148
  DataType: (ptr32 Eq_148)
  OrigDataType: (ptr32 (fn T_150 ()))
T_149: (in signature of _restgpr_20_x : void)
  Class: Eq_148
  DataType: (ptr32 Eq_148)
  OrigDataType: 
T_150: (in _restgpr_20_x() : void)
  Class: Eq_150
  DataType: void
  OrigDataType: void
T_151: (in _restgpr_21_x : ptr32)
  Class: Eq_151
  DataType: (ptr32 Eq_151)
  OrigDataType: (ptr32 (fn T_153 ()))
T_152: (in signature of _restgpr_21_x : void)
  Class: Eq_151
  DataType: (ptr32 Eq_151)
  OrigDataType: 
T_153: (in _restgpr_21_x() : void)
  Class: Eq_153
  DataType: void
  OrigDataType: void
T_154: (in _restgpr_22_x : ptr32)
  Class: Eq_154
  DataType: (ptr32 Eq_154)
  OrigDataType: (ptr32 (fn T_156 ()))
T_155: (in signature of _restgpr_22_x : void)
  Class: Eq_154
  DataType: (ptr32 Eq_154)
  OrigDataType: 
T_156: (in _restgpr_22_x() : void)
  Class: Eq_156
  DataType: void
  OrigDataType: void
T_157: (in _restgpr_23_x : ptr32)
  Class: Eq_157
  DataType: (ptr32 Eq_157)
  OrigDataType: (ptr32 (fn T_159 ()))
T_158: (in signature of _restgpr_23_x : void)
  Class: Eq_157
  DataType: (ptr32 Eq_157)
  OrigDataType: 
T_159: (in _restgpr_23_x() : void)
  Class: Eq_159
  DataType: void
  OrigDataType: void
T_160: (in _restgpr_24_x : ptr32)
  Class: Eq_160
  DataType: (ptr32 Eq_160)
  OrigDataType: (ptr32 (fn T_162 ()))
T_161: (in signature of _restgpr_24_x : void)
  Class: Eq_160
  DataType: (ptr32 Eq_160)
  OrigDataType: 
T_162: (in _restgpr_24_x() : void)
  Class: Eq_162
  DataType: void
  OrigDataType: void
T_163: (in _restgpr_25_x : ptr32)
  Class: Eq_163
  DataType: (ptr32 Eq_163)
  OrigDataType: (ptr32 (fn T_165 ()))
T_164: (in signature of _restgpr_25_x : void)
  Class: Eq_163
  DataType: (ptr32 Eq_163)
  OrigDataType: 
T_165: (in _restgpr_25_x() : void)
  Class: Eq_165
  DataType: void
  OrigDataType: void
T_166: (in _restgpr_26_x : ptr32)
  Class: Eq_166
  DataType: (ptr32 Eq_166)
  OrigDataType: (ptr32 (fn T_168 ()))
T_167: (in signature of _restgpr_26_x : void)
  Class: Eq_166
  DataType: (ptr32 Eq_166)
  OrigDataType: 
T_168: (in _restgpr_26_x() : void)
  Class: Eq_168
  DataType: void
  OrigDataType: void
T_169: (in _restgpr_27_x : ptr32)
  Class: Eq_169
  DataType: (ptr32 Eq_169)
  OrigDataType: (ptr32 (fn T_171 ()))
T_170: (in signature of _restgpr_27_x : void)
  Class: Eq_169
  DataType: (ptr32 Eq_169)
  OrigDataType: 
T_171: (in _restgpr_27_x() : void)
  Class: Eq_171
  DataType: void
  OrigDataType: void
T_172: (in _restgpr_28_x : ptr32)
  Class: Eq_172
  DataType: (ptr32 Eq_172)
  OrigDataType: (ptr32 (fn T_174 ()))
T_173: (in signature of _restgpr_28_x : void)
  Class: Eq_172
  DataType: (ptr32 Eq_172)
  OrigDataType: 
T_174: (in _restgpr_28_x() : void)
  Class: Eq_174
  DataType: void
  OrigDataType: void
T_175: (in _restgpr_29_x : ptr32)
  Class: Eq_175
  DataType: (ptr32 Eq_175)
  OrigDataType: (ptr32 (fn T_177 ()))
T_176: (in signature of _restgpr_29_x : void)
  Class: Eq_175
  DataType: (ptr32 Eq_175)
  OrigDataType: 
T_177: (in _restgpr_29_x() : void)
  Class: Eq_177
  DataType: void
  OrigDataType: void
T_178: (in _restgpr_30_x : ptr32)
  Class: Eq_38
  DataType: (ptr32 Eq_38)
  OrigDataType: (ptr32 (fn T_179 ()))
T_179: (in _restgpr_30_x() : void)
  Class: Eq_40
  DataType: void
  OrigDataType: void
T_180: (in _restgpr_31_x : ptr32)
  Class: Eq_180
  DataType: (ptr32 Eq_180)
  OrigDataType: (ptr32 (fn T_182 ()))
T_181: (in signature of _restgpr_31_x : void)
  Class: Eq_180
  DataType: (ptr32 Eq_180)
  OrigDataType: 
T_182: (in _restgpr_31_x() : void)
  Class: Eq_182
  DataType: void
  OrigDataType: void
T_183: (in r31_16 : (ptr32 Eq_183))
  Class: Eq_183
  DataType: (ptr32 Eq_183)
  OrigDataType: (ptr32 (struct (FFFFFFFC T_189 tFFFFFFFC)))
T_184: (in 0001FF24 : ptr32)
  Class: Eq_184
  DataType: (ptr32 (ptr32 Eq_183))
  OrigDataType: (ptr32 (struct (0 T_185 t0000)))
T_185: (in Mem13[0x0001FF24<p32>:word32] : word32)
  Class: Eq_183
  DataType: (ptr32 Eq_183)
  OrigDataType: word32
T_186: (in r9_17 : (ptr32 code))
  Class: Eq_186
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_187: (in -4<i32> : int32)
  Class: Eq_187
  DataType: int32
  OrigDataType: int32
T_188: (in r31_16 + -4<i32> : word32)
  Class: Eq_188
  DataType: word32
  OrigDataType: word32
T_189: (in Mem13[r31_16 + -4<i32>:word32] : word32)
  Class: Eq_186
  DataType: (ptr32 code)
  OrigDataType: word32
T_190: (in 0xFFFFFFFF<32> : word32)
  Class: Eq_186
  DataType: (ptr32 code)
  OrigDataType: word32
T_191: (in r9_17 == (<anonymous> *) 0xFFFFFFFF<32> : bool)
  Class: Eq_191
  DataType: bool
  OrigDataType: bool
T_192: (in r31_19 : (ptr32 word32))
  Class: Eq_192
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct 0004 (0 word32 dw0000)))
T_193: (in 0xFFFFFFFC<32> : word32)
  Class: Eq_193
  DataType: int32
  OrigDataType: int32
T_194: (in r31_16 + 0xFFFFFFFC<32> : word32)
  Class: Eq_194
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_195: (in -4<i32> : int32)
  Class: Eq_195
  DataType: int32
  OrigDataType: int32
T_196: (in r31_16 + 0xFFFFFFFC<32> + -4<i32> : word32)
  Class: Eq_192
  DataType: (ptr32 word32)
  OrigDataType: ptr32
T_197: (in 0<i32> : int32)
  Class: Eq_197
  DataType: int32
  OrigDataType: int32
T_198: (in r31_19 + 0<i32> : word32)
  Class: Eq_198
  DataType: ptr32
  OrigDataType: ptr32
T_199: (in Mem13[r31_19 + 0<i32>:word32] : word32)
  Class: Eq_186
  DataType: (ptr32 code)
  OrigDataType: word32
T_200: (in r31_19 + -4<i32> : word32)
  Class: Eq_192
  DataType: (ptr32 word32)
  OrigDataType: ptr32
T_201: (in 0xFFFFFFFF<32> : word32)
  Class: Eq_186
  DataType: (ptr32 code)
  OrigDataType: word32
T_202: (in r9_17 != (<anonymous> *) 0xFFFFFFFF<32> : bool)
  Class: Eq_202
  DataType: bool
  OrigDataType: bool
T_203: (in r11_5 : (ptr32 code))
  Class: Eq_203
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_204: (in -32504<i32> : int32)
  Class: Eq_204
  DataType: int32
  OrigDataType: int32
T_205: (in r30 + -32504<i32> : word32)
  Class: Eq_205
  DataType: word32
  OrigDataType: word32
T_206: (in Mem0[r30 + -32504<i32>:word32] : word32)
  Class: Eq_203
  DataType: (ptr32 code)
  OrigDataType: word32
T_207: (in r11_5 : (ptr32 code))
  Class: Eq_207
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_208: (in 16<i32> : int32)
  Class: Eq_208
  DataType: int32
  OrigDataType: int32
T_209: (in r30 + 16<i32> : word32)
  Class: Eq_209
  DataType: word32
  OrigDataType: word32
T_210: (in Mem0[r30 + 16<i32>:word32] : word32)
  Class: Eq_207
  DataType: (ptr32 code)
  OrigDataType: word32
T_211: (in r11_5 : (ptr32 code))
  Class: Eq_211
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_212: (in -32536<i32> : int32)
  Class: Eq_212
  DataType: int32
  OrigDataType: int32
T_213: (in r30 + -32536<i32> : word32)
  Class: Eq_213
  DataType: word32
  OrigDataType: word32
T_214: (in Mem0[r30 + -32536<i32>:word32] : word32)
  Class: Eq_211
  DataType: (ptr32 code)
  OrigDataType: word32
T_215: (in r11_5 : (ptr32 code))
  Class: Eq_215
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_216: (in -32532<i32> : int32)
  Class: Eq_216
  DataType: int32
  OrigDataType: int32
T_217: (in r30 + -32532<i32> : word32)
  Class: Eq_217
  DataType: word32
  OrigDataType: word32
T_218: (in Mem0[r30 + -32532<i32>:word32] : word32)
  Class: Eq_215
  DataType: (ptr32 code)
  OrigDataType: word32
T_219: (in __do_global_dtors_aux : ptr32)
  Class: Eq_219
  DataType: (ptr32 Eq_219)
  OrigDataType: (ptr32 (fn T_221 ()))
T_220: (in signature of __do_global_dtors_aux : void)
  Class: Eq_219
  DataType: (ptr32 Eq_219)
  OrigDataType: 
T_221: (in __do_global_dtors_aux() : void)
  Class: Eq_221
  DataType: void
  OrigDataType: void
T_222:
  Class: Eq_222
  DataType: (ptr32 code)
  OrigDataType: (struct 0004 (0 T_123 t0000))
*/
typedef struct Eq_16;
struct Globals {
	<anonymous> tFFFFFFFF;	// FFFFFFFF
	<anonymous> t0774;	// 774
	int32 dw1FEF8;	// 1FEF8
	<anonymous> * ptr1FEFC;	// 1FEFC
	int32 dw1FF00;	// 1FF00
	<anonymous> * ptr1FF04;	// 1FF04
	byte * ptr1FF08;	// 1FF08
	word32 dw1FF0C;	// 1FF0C
	int32 dw1FF14;	// 1FF14
	<anonymous> * (* ptr1FF18)[];	// 1FF18
	int32 * ptr1FF1C;	// 1FF1C
	struct Eq_183 * ptr1FF24;	// 1FF24
	word32 dw1FFF0;	// 1FFF0
	struct Eq_16 t1FFF4;	// 1FFF4
} Eq_1;

typedef void (Eq_7)(word32);

typedef void (Eq_11)();

typedef void (Eq_14)(Eq_16 *);

typedef struct Eq_16 {
	<anonymous> * ptr0010;	// 10
} Eq_16;

typedef struct Eq_21 {
	word32 dw0000;	// 0
	word32 dw0004;	// 4
} Eq_21;

typedef void (Eq_28)(Eq_30 *);

typedef struct Eq_30 {
	<anonymous> * ptrFFFF80E8;	// FFFF80E8
} Eq_30;

typedef void (Eq_33)(Eq_35 *);

typedef struct Eq_35 {
	<anonymous> * ptrFFFF80EC;	// FFFF80EC
} Eq_35;

typedef void (Eq_38)();

typedef void (Eq_102)(Eq_104 *);

typedef struct Eq_104 {
	<anonymous> * ptrFFFF8108;	// FFFF8108
} Eq_104;

typedef void (Eq_107)();

typedef void (Eq_130)(word32);

typedef void (Eq_133)();

typedef void (Eq_136)();

typedef void (Eq_139)();

typedef void (Eq_142)();

typedef void (Eq_145)();

typedef void (Eq_148)();

typedef void (Eq_151)();

typedef void (Eq_154)();

typedef void (Eq_157)();

typedef void (Eq_160)();

typedef void (Eq_163)();

typedef void (Eq_166)();

typedef void (Eq_169)();

typedef void (Eq_172)();

typedef void (Eq_175)();

typedef void (Eq_180)();

typedef struct Eq_183 {
	<anonymous> * ptrFFFFFFFC;	// FFFFFFFC
} Eq_183;

typedef void (Eq_219)();

