// hexdump-O0_got_plt.c
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O0.h"

<anonymous> * g_ptr11000 = &g_t0500;
<anonymous> * g_ptr11008 = &g_t0500;
<anonymous> * g_ptr11010 = &g_t0500;
<anonymous> * g_ptr11018 = &g_t0B44;
