// hexdump-O0_text.c
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O0.h"

// 00000440: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	word32 d1_n = g_dw403E;
	if (d1_n - g_dw401E != 0x00)
	{
		<anonymous> * a0_n = g_ptr4022;
		if (a0_n != null)
		{
			word32 a0_n;
			a0_n();
		}
	}
}

// 00000474: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	word32 d1_n = g_dw403E;
	int32 d0_n = g_dw401E - d1_n;
	Eq_n d0_n = (word32) (d0_n >> 0x02) + (d0_n * 0x02 < 0x00);
	if (d0_n >> 0x01 != 0x00)
	{
		<anonymous> * a0_n = g_ptr4026;
		if (a0_n != null)
		{
			word32 a0_n;
			a0_n();
		}
	}
}

// 000004BC: void __do_global_dtors_aux()
// Called from:
//      _fini
void __do_global_dtors_aux()
{
	ptr32 a5_n = 0x3FFE;
	byte * a3_n = g_ptr4042;
	if (*a3_n == 0x00)
	{
		if (g_dw402A != 0x00)
			fn000003F0();
		<anonymous> * a4_n[] = g_ptr403A;
		struct Eq_n * a2_n = g_ptr4046;
		Eq_n d2_n = (g_dw4032 - a4_n >> 0x02) - 0x01;
		Eq_n d0_n = a2_n->dw0000;
		while (d2_n - d0_n > 0x00)
		{
			Eq_n d0_n = (word32) d0_n + 1;
			a2_n->dw0000 = (word32) d0_n;
			word32 a0_n;
			word32 d1_n;
			a4_n[d0_n]();
			d0_n = a2_n->dw0000;
		}
		deregister_tm_clones();
		*a3_n = 0x01;
	}
}

// 00000534: void call___do_global_dtors_aux()
void call___do_global_dtors_aux()
{
}

// 00000536: void frame_dummy()
// Called from:
//      _init
void frame_dummy()
{
	register_tm_clones();
}

// 0000053C: void call_frame_dummy()
void call_frame_dummy()
{
}

// 00000540: void hexdump()
void hexdump()
{
}

// 00000598: void main()
void main()
{
	fn00000418();
	fn0000042C();
}

// 000005F0: void __do_global_ctors_aux()
// Called from:
//      _init
void __do_global_ctors_aux()
{
	struct Eq_n * a2_n = g_ptr404A;
	<anonymous> * a0_n = a2_n->ptrFFFFFFFC;
	ptr32 a5_n = 0x3FFE;
	if (a0_n != (<anonymous> *) -1)
	{
		ptr32 a2_n = a2_n - 4;
		do
		{
			struct Eq_n * a2_n;
			a0_n();
			a0_n = a2_n->ptrFFFFFFFC;
			a2_n = a2_n - 4;
		} while (a0_n != (<anonymous> *) -1);
	}
}

// 00000620: void call___do_global_ctors_aux()
void call___do_global_ctors_aux()
{
}

