// hexdump-Os_got_plt.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

struct Eq_n g_t4000 = 
	{
		hexdump,
	};
<anonymous> * g_ptr4004 = null;
<anonymous> * g_ptr4008 = null;
