// hexdump-Os_plt_got.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

// 00001040: void fn00001040(Register (ptr32 Eq_n) ebx)
// Called from:
//      main
void fn00001040(struct Eq_n * ebx)
{
	ebx->ptrFFFFFFEC();
}

// 00001048: void fn00001048(Register (ptr32 Eq_n) ebx)
// Called from:
//      __do_global_dtors_aux
void fn00001048(struct Eq_n * ebx)
{
	ebx->ptrFFFFFFF0();
}

