// hexdump-Os_init.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

// 0000000000001000: void _init()
void _init()
{
	if (__gmon_start__ != 0x00)
		__gmon_start__();
}

