// hexdump-Os_got.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

<anonymous> * g_ptr2008 = &g_tFFFFFFFF;
<anonymous> * g_ptr2020 = &g_t0E48;
<anonymous> * g_ptr2030 = null;
<anonymous> * g_ptr2040 = null;
<anonymous> * g_ptr2048 = null;
