// hexdump-Os_bss.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

struct Eq_n g_t68E87000 = 
	{
		0x00,
		0x00,
		0x00,
	};
word32 g_dw68E87018 = 0x00;
word32 g_dw68E87020 = 0x00;
uint64 g_qw68E87030 = 0x00;
word32 g_dw68E87038 = 0x00;
word32 g_dw68E87050 = 0x00;
word32 g_dw68E87060 = 0x00;
int32 g_dw68E87064 = 0;
struct Eq_n * g_ptr68E87068 = null;
struct Eq_n * g_ptr68E87080 = null;
word32 g_dw68E87088 = 0x00;
struct _RTL_CRITICAL_SECTION g_t68E870A0 = 
	{
		null,
		0,
		0,
		null,
		null,
		0x00,
	};
