// hexdump-Os_data.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

struct Eq_n * g_ptr68E83010 = &g_t68E82330;
Eq_n g_t68E83024 = 
	{
		0xFFFFFFFF
	};
word32 g_dw68E83030 = 0x02;
