// hexdump-Os_got.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

struct Eq_n * g_ptr10A40 = &g_t10000;
word64 g_qw10A48 = 0x00010A30;
word64 g_qw10A50 = 68296;
int64 g_qw10A58 = 68136;
<anonymous> * g_ptr10A98 = null;
<anonymous> * g_ptr10AA0 = hexdump;
<anonymous> * g_ptr10AB0 = null;
<anonymous> * g_ptr10AB8 = null;
<anonymous> * g_ptr10AC0 = null;
