// hexdump-Os.globals.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

Eq_n g_t10000;
<anonymous> * g_ptr209C8;
<anonymous> * g_ptr209D0;
<anonymous> * g_ptr209D8;
<anonymous> g_tFFFFFFFF;
