// hexdump-O0_text.c
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O0.h"

// 000000006E9C1000: void fn000000006E9C1000()
void fn000000006E9C1000()
{
	fn000000006E9C21A0(&g_t6E9C7000);
}

// 000000006E9C1010: Register word32 fn000000006E9C1010(Register Eq_n edx, Register (ptr32 Eq_n) gs)
// Called from:
//      DllMain
word32 fn000000006E9C1010(Eq_n edx, struct Eq_n * gs)
{
	Eq_n edx = (word32) rdx;
	if (edx != 0x00)
	{
		if (edx != 0x01)
			return 0x01;
		uint64 * rbx_n = g_ptr6E9C41E0;
		uint64 rsi_n = gs->ptr0030->qw0008;
		while (true)
		{
			word32 edi_n;
			__lock();
			uint64 rax_n;
			__cmpxchg(*rbx_n, rsi_n, 0x00, out rax_n);
			if (rax_n == 0x00)
				break;
			if (rsi_n == rax_n)
			{
				edi_n = 0x01;
				goto l000000006E9C10EF;
			}
			Sleep(1000);
		}
		edi_n = 0x00;
l000000006E9C10EF:
		word32 * rsi_n = g_ptr6E9C41F0;
		if ((word32) (uint64) *rsi_n != 0x01)
		{
			if ((word32) (uint64) *rsi_n == 0x00)
			{
				PVFV * rdx_n = g_ptr6E9C4230;
				PVFV * rcx_n = g_ptr6E9C4220;
				*rsi_n = 0x01;
				_initterm(rcx_n, rdx_n);
			}
		}
		else
			_amsg_exit(0x1F);
		if ((word32) (uint64) *rsi_n == 0x01)
		{
			_initterm(g_ptr6E9C4200, g_ptr6E9C4210);
			*rsi_n = 0x02;
		}
		if (edi_n == 0x00)
			*rbx_n = 0x00;
		if (*g_ptr6E9C41B0 != 0x00)
			fn000000006E9C1580(0x02);
		++g_dw6E9C7018;
		return 0x01;
	}
	else
	{
		int32 edx_n = (word32) (uint64) g_dw6E9C7018;
		uint64 rax_n = 0x00;
		if (edx_n > 0x00)
		{
			uint64 * rbx_n = g_ptr6E9C41E0;
			g_dw6E9C7018 = (word32) (uint64) (edx_n - 0x01);
			while (true)
			{
				__lock();
				uint64 rax_n;
				__cmpxchg(*rbx_n, 0x01, 0x00, out rax_n);
				if (rax_n == 0x00)
					break;
				Sleep(1000);
			}
			word32 * rdi_n = g_ptr6E9C41F0;
			if ((word32) (uint64) *rdi_n != 0x02)
			{
				_amsg_exit(0x1F);
				rax_n = 0x01;
			}
			else
			{
				fn000000006E9C22B0(&g_t6E9C7000);
				*rdi_n = 0x00;
				*rbx_n = rax_n;
				rax_n = 0x01;
			}
		}
		return (word32) rax_n;
	}
}

// 000000006E9C1200: Register word32 fn000000006E9C1200(Register Eq_n edx, Register (ptr32 Eq_n) gs)
// Called from:
//      DllMain
word32 fn000000006E9C1200(Eq_n edx, struct Eq_n * gs)
{
	Eq_n edx = (word32) rdx;
	word32 r14d_n;
	up32 eax_n;
	union Eq_n * rsi_n = g_ptr6E9C41D0;
	*rsi_n = (union Eq_n *) edx;
	uint64 r12_n = (uint64) edx;
	word32 r12d_n = (word32) r12_n;
	if (edx == 0x00)
	{
		eax_n = (word32) (uint64) g_dw6E9C7018;
		if (eax_n == 0x00)
			goto l000000006E9C1261;
		fn000000006E9C1800();
		fn000000006E9C2140();
l000000006E9C123E:
		fn000000006E9C2130();
		r14d_n = (word32) (uint64) eax_n;
		if ((word32) (uint64) fn000000006E9C1010((uint64) r12d_n, gs) != 0x00)
			goto l000000006E9C1264;
		goto l000000006E9C1261;
	}
	fn000000006E9C1800();
	eax_n = (word32) (uint64) (word32) (r12_n - 0x01);
	Eq_n rdx_n = (uint64) r12d_n;
	if (eax_n > 0x01)
	{
		fn000000006E9C2140();
		r14d_n = (word32) (uint64) eax_n;
		if (r12d_n == 0x03)
			goto l000000006E9C123E;
		goto l000000006E9C1264;
	}
	else
	{
		word32 eax_n = (word32) (uint64) fn000000006E9C1010(rdx_n, gs);
		if (eax_n != 0x00)
		{
			fn000000006E9C2130();
			r14d_n = (word32) (uint64) eax_n;
			if (eax_n != 0x00)
			{
				if (r12d_n == 0x01)
				{
					fn000000006E9C1530();
					fn000000006E9C2140();
					r14d_n = (word32) (uint64) eax_n;
					if (eax_n != 0x00)
						goto l000000006E9C1264;
					fn000000006E9C2140();
					fn000000006E9C2130();
l000000006E9C12F2:
					fn000000006E9C1010(0x00, gs);
					goto l000000006E9C1264;
				}
				fn000000006E9C2140();
				r14d_n = (word32) (uint64) eax_n;
l000000006E9C1264:
				*rsi_n = ~0x00;
				return (word32) (uint64) r14d_n;
			}
			if (r12d_n == 0x01)
				goto l000000006E9C12F2;
		}
l000000006E9C1261:
		r14d_n = 0x00;
		goto l000000006E9C1264;
	}
}

// 000000006E9C1350: Register Eq_n DllMain(Register Eq_n hModule, Register Eq_n dwReason, Register Eq_n lpReserved)
Eq_n DllMain(Eq_n hModule, Eq_n dwReason, Eq_n lpReserved)
{
	*g_ptr6E9C4240 = 0x00;
	return (BOOL) (uint64) fn000000006E9C1200(dwReason, gs);
}

// 000000006E9C1370: void fn000000006E9C1370(Register ptr64 rcx)
// Called from:
//      fn000000006E9C1530
//      fn000000006E9C23C0
void fn000000006E9C1370(ptr64 rcx)
{
	fn000000006E9C21D0(&g_t6E9C7000, rcx);
}

// 000000006E9C1380: void fn000000006E9C1380()
// Called from:
//      fn000000006E9C23C0
void fn000000006E9C1380()
{
	fn000000006E9C1370(0x6E9C1390);
}

// 000000006E9C1390: void fn000000006E9C1390()
void fn000000006E9C1390()
{
}

// 000000006E9C13A0: void hexdump(Register word32 r8d)
// Called from:
//      main
void hexdump(word32 r8d)
{
	(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(fp - 0x88)[(int64) (word32) (uint64) r8d].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0] = (Eq_n) 0x41;
	(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(fp - 0x88)[(int64) (word32) (uint64) ((word32) (uint64) r8d + 0x01)].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0].a0000)[0] = (Eq_n) 0x20;
}

// 000000006E9C1422: void main(Register word32 ecx, Register (ptr64 (ptr64 char)) rdx)
void main(word32 ecx, char ** rdx)
{
	fn000000006E9C1530();
	strlen(*rdx);
	hexdump((word32) (uint64) ecx);
}

// 000000006E9C1480: void fn000000006E9C1480()
void fn000000006E9C1480()
{
	<anonymous> * rax_n = g_ptr6E9C3010->qw0000;
	while (rax_n != null)
	{
		rax_n();
		struct Eq_n * rax_n = g_ptr6E9C3010;
		rax_n = rax_n->ptr0008;
		g_ptr6E9C3010 = (struct Eq_n *) &rax_n->ptr0008;
	}
}

// 000000006E9C14C0: void fn000000006E9C14C0()
// Called from:
//      fn000000006E9C1530
void fn000000006E9C14C0()
{
	Eq_n rdx_n[] = g_ptr6E9C4180;
	Eq_n eax_n = rdx_n[0].dw0000;
	word32 ecx_n = (word32) (uint64) eax_n;
	if (eax_n == ~0x00)
	{
		uint64 rax_n = 0x00;
		do
		{
			uint64 r8_n = (uint64) (word32) (rax_n + 0x01);
			ecx_n = (word32) (uint64) (word32) rax_n;
			rax_n = r8_n;
		} while (rdx_n[r8_n].dw0000 != 0x00);
	}
	if (ecx_n != 0x00)
	{
		uint64 rax_n = (uint64) ecx_n;
		ptr64 rbx_n = &(rdx_n + rax_n)->dw0000;
		ptr64 rsi_n = rdx_n - 0x08 + (rax_n - (uint64) (ecx_n - 0x01)) * 0x08;
		do
		{
			word64 r8_n;
			fn9090909090909090();
			rbx_n -= 0x08;
		} while (rbx_n != rsi_n);
	}
	fn000000006E9C1370(1855722624);
}

// 000000006E9C1530: void fn000000006E9C1530()
// Called from:
//      DllMain
//      main
void fn000000006E9C1530()
{
	if ((word32) (uint64) g_dw6E9C7020 != 0x00)
		return;
	g_dw6E9C7020 = 0x01;
	fn000000006E9C14C0();
}

// 000000006E9C1550: void fn000000006E9C1550(Register up32 edx)
void fn000000006E9C1550(up32 edx)
{
	if (edx != 0x03 && edx != 0x00)
		return;
	fn000000006E9C1C10(edx);
}

// 000000006E9C1580: Register up32 fn000000006E9C1580(Register up32 edx)
// Called from:
//      fn000000006E9C1010
up32 fn000000006E9C1580(up32 edx)
{
	word32 * rax_n = g_ptr6E9C4170;
	if (*rax_n != 0x02)
		*rax_n = 0x02;
	if (edx == 0x02)
	{
		word64 * rbx_n = &g_qw6E9CA050;
		if (1855758416 == 1855758416)
			return edx;
		do
		{
			<anonymous> * rax_n = *rbx_n;
			if (rax_n != null)
			{
				word64 rcx_n;
				rax_n();
			}
			++rbx_n;
		} while (&g_qw6E9CA050 != rbx_n);
		return edx;
	}
	else
	{
		if (edx != 0x01)
			return edx;
		fn000000006E9C1C10(edx);
		return edx;
	}
}

// 000000006E9C1610: void fn000000006E9C1610()
void fn000000006E9C1610()
{
}

// 000000006E9C1620: void fn000000006E9C1620(Register ptr64 rcx)
// Called from:
//      fn000000006E9C1690
//      fn000000006E9C1800
void fn000000006E9C1620(ptr64 rcx)
{
	FILE * rax_n = fn000000006E9C2330(0x02);
	fwrite(&g_v6E9C4060, 0x01, 0x1B, rax_n);
	union Eq_n * rcx_n;
	msvcrt.dll!vfprintf();
	abort();
	fn000000006E9C1690(rcx_n);
}

// 000000006E9C1690: void fn000000006E9C1690(Register (ptr64 Eq_n) rcx)
// Called from:
//      fn000000006E9C1620
//      fn000000006E9C1800
void fn000000006E9C1690(union Eq_n * rcx)
{
	Eq_n rbx_n;
	Eq_n rbx_n = (int64) g_dw6E9C7064;
	int32 ebx_n = (word32) rbx_n;
	if (ebx_n <= 0x00)
	{
l000000006E9C17C0:
		rbx_n.u1 = 0x00;
		goto l000000006E9C16E7;
	}
	else
	{
		struct Eq_n * rax_n = g_ptr6E9C7068->a0018;
		uint64 rcx_n = 0x00;
		do
		{
			word32 ecx_n = (word32) rcx_n;
			union Eq_n * rdx_n = rax_n->qw0000;
			if (rdx_n <= rcx && rcx < (char *) rdx_n + (uint64) (rax_n->ptr0008)->dw0008)
				return;
			rcx_n = (uint64) (ecx_n + 0x01);
			++rax_n;
			rbx_n = rbx_n;
		} while ((word32) rcx_n != ebx_n);
l000000006E9C16E7:
		struct Eq_n * rax_n = fn000000006E9C1E20(rcx);
		if (rax_n != null)
		{
			ui64 rbx_n = rbx_n * 0x05;
			struct Eq_n * rax_n = g_ptr6E9C7068 + (rbx_n << 0x03) / 24;
			rax_n->ptr0020 = rax_n;
			rax_n->dw0000 = 0x00;
			word64 rax_n = fn000000006E9C1F50();
			struct Eq_n * rax_n = g_ptr6E9C7068;
			Eq_n rcx_n = (uint64) rax_n->dw000C + rax_n;
			rax_n->a0018[rbx_n] = rcx_n;
			if (SEQ(SLICE(rax_n, word32, 32), VirtualQuery(rcx_n, fp - 0x48, 0x30)) != 0x00)
			{
				uint64 rax_n = (uint64) dwLoc24;
				word32 eax_n = (word32) rax_n;
				if ((word32) (uint64) ((word32) (uint64) (word32) (rax_n - 0x40) & ~0x40) != 0x00 && (word32) ((uint64) ((word32) ((uint64) ((word32) (rax_n - 0x04))) & ~0x04)) != 0x00)
				{
					Eq_n r8_n = 0x04;
					if (eax_n != 0x02)
						r8_n.u0 = 0x40;
					Eq_n rbx_n = g_ptr6E9C7068 + (rbx_n << 0x03) / 24;
					*((word64) rbx_n + 8) = qwLoc48;
					*((word64) rbx_n + 16) = qwLoc30;
					if (VirtualProtect(qwLoc48, qwLoc30, r8_n, rbx_n) == 0x00)
					{
						GetLastError();
						fn000000006E9C1620(1855733976);
						goto l000000006E9C17C0;
					}
				}
				++g_dw6E9C7064;
				return;
			}
			fn000000006E9C1620(0x6E9C40A0);
		}
		fn000000006E9C1620(1855733888);
		fn000000006E9C1800();
	}
}

// 000000006E9C1800: void fn000000006E9C1800()
// Called from:
//      DllMain
//      fn000000006E9C1690
void fn000000006E9C1800()
{
	int32 edi_n = (word32) (uint64) g_dw6E9C7060;
	if (edi_n != 0x00)
		return;
	g_dw6E9C7060 = 0x01;
	ui64 rax_n = (word64) ((word64) ((int64) (word32) (uint64) fn000000006E9C1EA0() * 0x28) + 0x0F);
	fn000000006E9C20F0(rax_n & ~0x0F);
	union Eq_n * r12_n = g_ptr6E9C4190;
	union Eq_n * rbx_n = g_ptr6E9C41A0;
	g_dw6E9C7064 = 0x00;
	g_ptr6E9C7068 = fp - 0x78 - (rax_n & ~0x0F) + 0x20;
	int64 rax_n = r12_n - rbx_n;
	if (rax_n <= 0x07)
		return;
	uint64 rax_n;
	uint64 rdx_n = (uint64) *rbx_n;
	word32 edx_n = (word32) rdx_n;
	if (rax_n > 11)
	{
		if (edx_n != 0x00)
			goto l000000006E9C1A40;
		rax_n = (uint64) *((char *) rbx_n + 4);
		if ((word32) (uint64) ((word32) (uint64) (word32) rax_n | *((char *) rbx_n + 8)) != 0x00)
			goto l000000006E9C18A8;
		rdx_n = (uint64) *((char *) rbx_n + 0x0C);
		rbx_n = (union Eq_n *) ((char *) rbx_n + 0x0C);
	}
	if ((word32) rdx_n != 0x00)
		goto l000000006E9C1A40;
	rax_n = (uint64) *((char *) rbx_n + 4);
l000000006E9C18A8:
	if ((word32) rax_n == 0x00)
	{
		if ((word32) (uint64) *((char *) rbx_n + 8) != 0x01)
		{
l000000006E9C1A81:
			fn000000006E9C1620(0x6E9C4100);
			fn000000006E9C1A90();
			return;
		}
		union Eq_n * rbx_n = (char *) rbx_n + 0x0C;
		if (rbx_n >= r12_n)
			return;
		struct Eq_n * r13_n = g_ptr6E9C41C0;
		do
		{
			Eq_n rax_n = r13_n + (uint64) (*rbx_n) / 64;
			up32 edx_n = (word32) (uint64) (word32) *((char *) rbx_n + 8);
			union Eq_n * rsi_n = r13_n + (uint64) (*((char *) rbx_n + 4)) / 64;
			word64 r15_n = *rax_n;
			if (edx_n != 0x20)
			{
				if (edx_n <= 0x20)
				{
					if (edx_n == 0x08)
					{
						uint64 rdx_n = (uint64) (word32) *rsi_n;
						if ((byte) rdx_n < 0x00)
							rdx_n |= ~0xFF;
						fn000000006E9C1690(rcx_n);
						*rsi_n = (union Eq_n *) (byte) (r15_n + (rdx_n - rax_n));
						goto l000000006E9C1904;
					}
					if (edx_n == 0x10)
					{
						uint64 rdx_n = (uint64) (word32) *rsi_n;
						if ((word16) rdx_n < 0x00)
							rdx_n |= ~0xFFFF;
						fn000000006E9C1690(rcx_n);
						*rsi_n = (union Eq_n *) (word16) (r15_n + (rdx_n - rax_n));
						rbx_n = (union Eq_n *) ((char *) rbx_n + 0x0C);
						if (rbx_n >= r12_n)
							break;
						continue;
					}
l000000006E9C1A75:
					fn000000006E9C1620(1855734072);
					goto l000000006E9C1A81;
				}
				if (edx_n != 0x40)
					goto l000000006E9C1A75;
				Eq_n r15_n = (word64) (*rsi_n - rax_n) + r15_n;
				fn000000006E9C1690(rsi_n);
				*rsi_n = (union Eq_n *) r15_n;
			}
			else
			{
				uint64 rdx_n = (uint64) *rsi_n;
				uint64 rdx_n = rdx_n | 0xFFFFFFFF00000000;
				if ((word32) rdx_n >= 0x00)
					rdx_n = rdx_n;
				fn000000006E9C1690(rsi_n);
				*rsi_n = (union Eq_n *) (word32) (r15_n + (rdx_n - rax_n));
			}
l000000006E9C1904:
			rbx_n = (union Eq_n *) ((char *) rbx_n + 0x0C);
		} while (rbx_n < r12_n);
l000000006E9C1970:
		if ((word32) (uint64) g_dw6E9C7064 > 0x00)
		{
			uint64 rbx_n = 0x00;
			do
			{
				struct Eq_n * rax_n = g_ptr6E9C7068 + rbx_n / 24;
				Eq_n r8_n = (uint64) rax_n->dw0000;
				if ((word32) r8_n != 0x00)
					VirtualProtect(rax_n->t0008, rax_n->t0010, r8_n, fp - 0x4C);
				edi_n = (word32) (uint64) (edi_n + 0x01);
				rbx_n += 0x28;
			} while (edi_n < g_dw6E9C7064);
		}
		return;
	}
l000000006E9C1A40:
	if (rbx_n >= r12_n)
		return;
	struct Eq_n * r14_n = g_ptr6E9C41C0;
	do
	{
		union Eq_n * rsi_n = r14_n + (uint64) (*((char *) rbx_n + 4)) / 64;
		Eq_n r13d_n = (word32) (uint64) ((char *) *rsi_n + (word32) ((uint64) (*rbx_n)));
		fn000000006E9C1690(rsi_n);
		*rsi_n = (union Eq_n *) r13d_n;
		rbx_n = (union Eq_n *) ((char *) rbx_n + 8);
	} while (rbx_n < r12_n);
	goto l000000006E9C1970;
}

// 000000006E9C1A90: void fn000000006E9C1A90()
// Called from:
//      fn000000006E9C1800
//      fn000000006E9C1C10
void fn000000006E9C1A90()
{
	EnterCriticalSection(&g_t6E9C70A0);
	struct Eq_n * rbx_n = g_ptr6E9C7080;
	while (rbx_n != null)
	{
		Eq_n rax_n = TlsGetValue((uint64) rbx_n->qw0000);
		if (GetLastError() == 0x00 && rax_n != null)
		{
			word64 rax_n;
			rbx_n[1]();
		}
		rbx_n = (struct Eq_n *) rbx_n[2];
	}
	LeaveCriticalSection(&g_t6E9C70A0);
}

// 000000006E9C1B00: void fn000000006E9C1B00(Register word32 ecx, Register (ptr64 code) rdx)
void fn000000006E9C1B00(word32 ecx, <anonymous> * rdx)
{
	word32 ecx = (word32) rcx;
	word32 edi_n = (word32) (uint64) ecx;
	if ((word32) (uint64) g_dw6E9C7088 == 0x00)
		return;
	struct Eq_n * rax_n = calloc(0x01, 0x18);
	if (rax_n == null)
		return;
	rax_n->qw0000 = (word64) edi_n;
	rax_n[1] = (struct Eq_n) rdx;
	EnterCriticalSection(&g_t6E9C70A0);
	struct Eq_n * rax_n = g_ptr6E9C7080;
	g_ptr6E9C7080 = rax_n;
	rax_n[2] = (struct Eq_n) rax_n;
	LeaveCriticalSection(&g_t6E9C70A0);
}

// 000000006E9C1B80: void fn000000006E9C1B80(Register word32 ecx)
void fn000000006E9C1B80(word32 ecx)
{
	word32 ecx = (word32) rcx;
	word32 ebx_n = (word32) (uint64) ecx;
	if ((word32) (uint64) g_dw6E9C7088 == 0x00)
		return;
	EnterCriticalSection(&g_t6E9C70A0);
	struct Eq_n * rcx_n = g_ptr6E9C7080;
	if (rcx_n != null)
	{
		struct Eq_n * rdx_n = null;
		while (true)
		{
			struct Eq_n * rax_n = rcx_n[2];
			if ((word32) (uint64) rcx_n->qw0000 == ebx_n)
				break;
			rdx_n = rcx_n;
			if (rax_n == null)
				goto l000000006E9C1BE3;
			rcx_n = rax_n;
		}
		if (rdx_n != null)
			rdx_n[2] = (struct Eq_n) rax_n;
		else
			g_ptr6E9C7080 = rax_n;
		free(rcx_n);
	}
l000000006E9C1BE3:
	LeaveCriticalSection(&g_t6E9C70A0);
}

// 000000006E9C1C10: void fn000000006E9C1C10(Register up32 edx)
// Called from:
//      fn000000006E9C1550
//      fn000000006E9C1580
void fn000000006E9C1C10(up32 edx)
{
	if (edx == 0x02)
		fn000000006E9C20E0();
	else if (edx <= 0x02)
	{
		if (edx != 0x00)
		{
			if ((word32) (uint64) g_dw6E9C7088 == 0x00)
				InitializeCriticalSection(&g_t6E9C70A0);
			g_dw6E9C7088 = 0x01;
		}
		else
		{
			if ((word32) (uint64) g_dw6E9C7088 != 0x00)
				fn000000006E9C1A90();
			if ((word32) (uint64) g_dw6E9C7088 == 0x01)
			{
				struct Eq_n * rbx_n = g_ptr6E9C7080;
				while (rbx_n != null)
				{
					rbx_n = (struct Eq_n *) rbx_n[2];
					free(rbx_n);
				}
				g_ptr6E9C7080 = null;
				g_dw6E9C7088 = 0x00;
				DeleteCriticalSection(&g_t6E9C70A0);
			}
		}
	}
	else if (edx == 0x03 && (word32) ((uint64) g_dw6E9C7088) != 0x00)
		fn000000006E9C1A90();
}

// 000000006E9C1D00: void fn000000006E9C1D00(Register (ptr64 Eq_n) rcx)
void fn000000006E9C1D00(struct Eq_n * rcx)
{
	if (rcx->a0000[0].w0000 != 23117 || rcx[(int64) rcx->dw003C / 64] != 0x4550)
		;
}

// 000000006E9C1D30: void fn000000006E9C1D30(Register (ptr64 Eq_n) rcx, Register uint64 rdx)
void fn000000006E9C1D30(struct Eq_n * rcx, uint64 rdx)
{
	struct Eq_n * rdx_n = rcx + (int64) rcx->dw003C / 64;
	struct Eq_n * rax_n = &rdx_n->w0014 + 2 + (uint64) ((word32) rdx_n->w0014) / 22;
	word32 edx_n = (word32) (uint64) (word32) rdx_n->w0006;
	if (edx_n != 0x00)
	{
		struct Eq_n * r9_n = rax_n + 1 + (uint64) (edx_n - 0x01);
		do
		{
			uint64 rcx_n = (uint64) rax_n->dw000C;
			word32 edx_n = (word32) rcx_n;
			if (rcx_n <= rdx && (uint64) (edx_n + rax_n->dw0008) > rdx)
				return;
			++rax_n;
		} while (rax_n != r9_n);
	}
}

// 000000006E9C1D80: void fn000000006E9C1D80(Register word32 rax_32_n, Register (ptr64 char) rcx)
void fn000000006E9C1D80(word32 rax_32_n, char * rcx)
{
	if (SEQ(rax_32_n, strlen(rcx)) > 0x08)
		return;
	struct Eq_n * rdx_n = g_ptr6E9C41C0;
	if (rdx_n->w0000 != 23117)
		return;
	struct Eq_n * rax_n = rdx_n + (int64) rdx_n->dw003C / 64;
	if (rax_n->dw0000 != 0x4550 || rax_n->w0018 != 0x020B)
		return;
	char * r12_n = &rax_n->w0018 + (uint64) ((word32) rax_n->w0014);
	word32 eax_n = (word32) (uint64) (word32) rax_n->w0006;
	if (eax_n != 0x00)
	{
		char * rsi_n = r12_n + 40 + (uint64) (eax_n - 0x01) * 0x28;
		do
		{
			if (strncmp(r12_n, rcx, 0x08) == 0x00)
				return;
			r12_n += 40;
		} while (r12_n != rsi_n);
	}
}

// 000000006E9C1E20: Register (ptr64 Eq_n) fn000000006E9C1E20(Register (ptr64 Eq_n) rcx)
// Called from:
//      fn000000006E9C1690
struct Eq_n * fn000000006E9C1E20(union Eq_n * rcx)
{
	struct Eq_n * rdx_n = g_ptr6E9C41C0;
	struct Eq_n * rax_n = null;
	if (rdx_n->w0000 != 23117)
		return rax_n;
	struct Eq_n * r8_n = rdx_n + (int64) rdx_n->dw003C / 64;
	if (r8_n->dw0000 != 0x4550 || r8_n->w0018 != 0x020B)
		return rax_n;
	uint64 rcx_n = rcx - rdx_n;
	word32 edx_n = (word32) (uint64) (word32) r8_n->w0006;
	rax_n = (struct Eq_n *) (&r8_n->w0018 + (uint64) ((word32) r8_n->w0014));
	if (edx_n != 0x00)
	{
		word64 r9_n = rax_n + 0x28 + CONVERT(edx_n - 0x01, word32, uint64) * 0x28;
		do
		{
			uint64 r8_n = (uint64) rax_n->dw000C;
			word32 edx_n = (word32) r8_n;
			if (rcx_n >= r8_n && rcx_n < (uint64) (edx_n + rax_n->dw0008))
				return rax_n;
			rax_n += 0x28;
		} while (rax_n != r9_n);
	}
	return null;
}

// 000000006E9C1EA0: Register word32 fn000000006E9C1EA0()
// Called from:
//      fn000000006E9C1800
word32 fn000000006E9C1EA0()
{
	struct Eq_n * rax_n = g_ptr6E9C41C0;
	if (rax_n->w0000 == 23117)
	{
		struct Eq_n * rax_n = rax_n + (int64) rax_n->dw003C / 64;
		if (rax_n->dw0000 == 0x4550 && rax_n->w0018 == 0x020B)
			return (word32) (uint64) (word32) (uint64) (word32) rax_n->w0006;
	}
	return 0x00;
}

// 000000006E9C1EE0: void fn000000006E9C1EE0(Register word64 rcx)
void fn000000006E9C1EE0(word64 rcx)
{
	struct Eq_n * r8_n = g_ptr6E9C41C0;
	if (r8_n->w0000 != 23117)
		return;
	struct Eq_n * rdx_n = r8_n + (int64) r8_n->dw003C / 64;
	if (rdx_n->dw0000 != 0x4550 || rdx_n->w0018 != 0x020B)
		return;
	struct Eq_n * rax_n = (char *) (&rdx_n->w0018 + (uint64) ((word32) rdx_n->w0014)) + 39;
	word32 edx_n = (word32) (uint64) (word32) rdx_n->w0006;
	if (edx_n != 0x00)
	{
		struct Eq_n * rdx_n = rax_n + 1 + (uint64) (edx_n - 0x01);
		do
		{
			if ((rax_n->b0000 & 0x20) != 0x00)
			{
				if (rcx == 0x00)
					return;
				--rcx;
			}
			++rax_n;
		} while (rax_n != rdx_n);
	}
}

// 000000006E9C1F50: Register (ptr64 Eq_n) fn000000006E9C1F50()
// Called from:
//      fn000000006E9C1690
struct Eq_n * fn000000006E9C1F50()
{
	struct Eq_n * rax_n = g_ptr6E9C41C0;
	struct Eq_n * r8_n = null;
	if (rax_n->w0000 != 23117)
		return null;
	struct Eq_n * rdx_n = rax_n + (int64) rax_n->dw003C / 64;
	if (rdx_n->dw0000 != 0x4550)
		return null;
	if (rdx_n->w0018 == 0x020B)
		r8_n = rax_n;
	return r8_n;
}

// 000000006E9C1F90: void fn000000006E9C1F90(Register ui64 rcx)
void fn000000006E9C1F90(ui64 rcx)
{
	struct Eq_n * rax_n = g_ptr6E9C41C0;
	if (rax_n->w0000 != 23117)
		return;
	struct Eq_n * rdx_n = rax_n + (int64) rax_n->dw003C / 64;
	if (rdx_n->dw0000 != 0x4550 || rdx_n->w0018 != 0x020B)
		return;
	uint64 rcx_n = rcx - rax_n;
	struct Eq_n * rax_n = &rdx_n->w0018 + (uint64) ((word32) rdx_n->w0014);
	word32 edx_n = (word32) (uint64) (word32) rdx_n->w0006;
	if (edx_n == 0x00)
		return;
	struct Eq_n * r9_n = rax_n + 1 + (uint64) (edx_n - 0x01);
	do
	{
		uint64 r8_n = (uint64) rax_n->dw000C;
		word32 edx_n = (word32) r8_n;
		if (rcx_n >= r8_n && rcx_n < (uint64) (edx_n + rax_n->dw0008))
			return;
		++rax_n;
	} while (r9_n != rax_n);
}

// 000000006E9C2020: void fn000000006E9C2020(Register word32 ecx)
void fn000000006E9C2020(word32 ecx)
{
	struct Eq_n * r11_n = g_ptr6E9C41C0;
	if (r11_n->w0000 != 23117)
		return;
	struct Eq_n * r8_n = r11_n + (int64) r11_n->dw003C / 64;
	if (r8_n->dw0000 != 0x4550 || r8_n->w0018 != 0x020B)
		return;
	uint64 rax_n = (uint64) r8_n->dw0090;
	if ((word32) rax_n == 0x00)
		return;
	struct Eq_n * rdx_n = &r8_n->w0018 + (uint64) ((word32) r8_n->w0014);
	word32 r8d_n = (word32) (uint64) (word32) r8_n->w0006;
	if (r8d_n == 0x00)
		return;
	struct Eq_n * r10_n = rdx_n + 1 + (uint64) (r8d_n - 0x01);
	do
	{
		uint64 r9_n = (uint64) rdx_n->dw000C;
		word32 r8d_n = (word32) r9_n;
		if (rax_n >= r9_n && rax_n < (uint64) (r8d_n + rdx_n->dw0008))
		{
			struct Eq_n * rax_n = r11_n + rax_n / 64;
			while (true)
			{
				int32 ecx_n = (word32) rcx;
				if ((word32) (uint64) rax_n->dw0004 == 0x00 && (word32) ((uint64) rax_n->dw000C) == 0x00)
					break;
				if (ecx_n <= 0x00)
					return;
				rcx = (uint64) (ecx_n - 0x01);
				++rax_n;
			}
			return;
		}
		++rdx_n;
	} while (r10_n != rdx_n);
}

// 000000006E9C20E0: void fn000000006E9C20E0()
// Called from:
//      fn000000006E9C1C10
void fn000000006E9C20E0()
{
	__fninit();
}

// 000000006E9C20F0: void fn000000006E9C20F0(Register uint64 rax)
// Called from:
//      fn000000006E9C1800
void fn000000006E9C20F0(uint64 rax)
{
	struct Eq_n * rcx_n = fp + 0x08;
	if (rax >= 0x1000)
	{
		do
		{
			rcx_n -= 0x1000;
			rcx_n->qw0000 = rcx_n->qw0000;
			rax -= 0x1000;
		} while (rax > 0x1000);
	}
	word64 * rcx_n = rcx_n - rax;
	*rcx_n = *rcx_n;
}

// 000000006E9C2130: void fn000000006E9C2130()
// Called from:
//      DllMain
void fn000000006E9C2130()
{
}

// 000000006E9C2140: void fn000000006E9C2140()
// Called from:
//      DllMain
void fn000000006E9C2140()
{
}

// 000000006E9C21A0: void fn000000006E9C21A0(Register (ptr64 Eq_n) rcx)
// Called from:
//      fn000000006E9C1000
void fn000000006E9C21A0(struct Eq_n * rcx)
{
	if (rcx == null)
		return;
	rcx->qw0010 = 0x00;
	rcx->qw0008 = 0x00;
	rcx->qw0000 = 0x00;
}

// 000000006E9C21D0: void fn000000006E9C21D0(Register (ptr64 Eq_n) rcx, Register ptr64 rdx)
// Called from:
//      fn000000006E9C1370
void fn000000006E9C21D0(struct Eq_n * rcx, ptr64 rdx)
{
	if (rcx == null)
		return;
	ptr64 * rax_n;
	ptr64 * rdx_n;
	ptr64 * rdx_n;
	lock();
	if (rcx->ptr0000 != null)
	{
		rax_n = rcx->ptr0008;
		rdx_n = rcx->ptr0010;
	}
	else
	{
		rax_n = calloc(0x20, 0x08);
		rcx->ptr0000 = rax_n;
		rdx_n = (ptr64 *) 0x08;
		if (rax_n == null)
			goto l000000006E9C2292;
		rcx->ptr0008 = rax_n;
		rcx->ptr0010 = rax_n + 32;
		rdx_n = rax_n + 32;
	}
	if (rdx_n != rax_n)
	{
l000000006E9C2204:
		ptr64 * rdx_n = rax_n + 1;
		rcx->ptr0008 = rdx_n;
		*rax_n = rdx;
		unlock();
		return;
	}
	ptr64 * rcx_n = rcx->ptr0000;
	Eq_n rax_n = rax_n - rcx_n;
	Eq_n rdx_n = rax_n >> 0x03 << 0x04;
	ptr64 * rax_n = realloc(rcx_n, rdx_n);
	rdx_n = rax_n;
	if (rax_n != null)
	{
		rcx->ptr0000 = rax_n;
		Mem89[rcx + 0x10:word64] = rax_n + rdx_n;
		rax_n = rax_n + rax_n;
		goto l000000006E9C2204;
	}
l000000006E9C2292:
	unlock();
}

// 000000006E9C22B0: void fn000000006E9C22B0(Register (ptr64 Eq_n) rcx)
// Called from:
//      fn000000006E9C1010
void fn000000006E9C22B0(struct Eq_n * rcx)
{
	lock();
	struct Eq_n * r12_n = rcx->ptr0000;
	struct Eq_n * rbx_n = rcx->ptr0008;
	rcx->qw0010 = 0x00;
	rcx->ptr0008 = null;
	rcx->ptr0000 = null;
	word64 rcx_n;
	unlock();
	if (r12_n != null)
	{
l000000006E9C22F2:
		for (rbx_n -= 0x08; r12_n <= rbx_n; rbx_n -= 0x08)
		{
			<anonymous> * rax_n = rbx_n->qw0000;
			if (rax_n == null)
				goto l000000006E9C22F2;
			rax_n();
		}
		free(r12_n);
	}
}

// 000000006E9C2330: Register word64 fn000000006E9C2330(Register word32 ecx)
// Called from:
//      fn000000006E9C1620
word64 fn000000006E9C2330(word32 ecx)
{
	word64 rax_n;
	_iob_func();
	return rax_n + (uint64) ((word32) ((uint64) ecx)) * 0x30;
}

// 000000006E9C23C0: void fn000000006E9C23C0()
void fn000000006E9C23C0()
{
	fn000000006E9C1380();
}

Eq_n g_a6E9C23D0[] = 
	{
	};
Eq_n g_t6E9C23F0 = 
	{
		0x00,
		null,
	};
