// hexdump-O0_data.c
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O0.h"

struct Eq_n * g_ptr6E9C3010 = &g_t6E9C23F0;
Eq_n g_t6E9C3024 = 
	{
		0xFFFFFFFF
	};
word32 g_dw6E9C3030 = 0x02;
