// hexdump-O0_CRT.c
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O0.h"

Eq_n g_t6E9CA000 = null;
Eq_n g_t6E9CA008 = null;
Eq_n g_t6E9CA010 = null;
Eq_n g_t6E9CA020 = null;
word64 g_qw6E9CA050 = 0x00;
