// hexdump-Os_fini.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

// 00000000000009C0: void _fini()
// Called from:
//      strlen
void _fini()
{
	(*(<anonymous> **) 0x000209D8)();
}

