// hexdump-O0.h
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (840 code t0840) (E00 code t0E00) (2018 (ptr64 code) ptr2018) (2020 (ptr64 code) ptr2020) (2030 (ptr64 code) ptr2030) (2040 (ptr64 code) ptr2040) (2048 (ptr64 code) ptr2048) (2050 byte b2050))
	globals_t (in globals : (ptr64 (struct "Globals")))
Eq_17: (union "Eq_17" (int64 u0) (uint64 u1))
	T_17 (in a5_7 : Eq_17)
	T_20 (in 0x2008<u64> - 0x2008<u64> : word64)
Eq_18: (union "Eq_18" (int64 u0) (ptr64 u1))
	T_18 (in 0000000000002008 : ptr64)
Eq_19: (union "Eq_19" (int64 u0) (ptr64 u1))
	T_19 (in 0000000000002008 : ptr64)
Eq_22: (union "Eq_22" (int64 u0) (uint64 u1))
	T_22 (in a5_7 >> 0x3F<u32> : word64)
Eq_24: (union "Eq_24" (int64 u0) (uint64 u1))
	T_24 (in a5_7 >> 3<u32> : word64)
Eq_25: (union "Eq_25" (int64 u0) (uint64 u1))
	T_25 (in (a5_7 >>u 0x3F<u32>) + (a5_7 >> 3<u32>) : word64)
Eq_49: (fn void ())
	T_49 (in deregister_tm_clones : ptr64)
	T_50 (in signature of deregister_tm_clones : void)
Eq_57: (fn void ())
	T_57 (in register_tm_clones : ptr64)
	T_58 (in signature of register_tm_clones : void)
Eq_60: (fn void ())
	T_60 (in fn0000000000000440 : ptr64)
	T_61 (in signature of fn0000000000000440 : void)
Eq_63: (fn void ())
	T_63 (in fn0000000000000450 : ptr64)
	T_64 (in signature of fn0000000000000450 : void)
// Type Variables ////////////
globals_t: (in globals : (ptr64 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr64 Eq_1)
  OrigDataType: (ptr64 (struct "Globals"))
T_2: (in t3_5 : (ptr64 code))
  Class: Eq_2
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_3: (in 0000000000002018 : ptr64)
  Class: Eq_3
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_4 t0000)))
T_4: (in Mem0[0x0000000000002018<p64>:word64] : word64)
  Class: Eq_2
  DataType: (ptr64 code)
  OrigDataType: word64
T_5: (in t3_5 : (ptr64 code))
  Class: Eq_5
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_6: (in 0000000000002020 : ptr64)
  Class: Eq_6
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_7 t0000)))
T_7: (in Mem0[0x0000000000002020<p64>:word64] : word64)
  Class: Eq_5
  DataType: (ptr64 code)
  OrigDataType: word64
T_8: (in 0000000000002008 : ptr64)
  Class: Eq_8
  DataType: ptr64
  OrigDataType: ptr64
T_9: (in 0000000000002008 : ptr64)
  Class: Eq_8
  DataType: ptr64
  OrigDataType: ptr64
T_10: (in 0x2008<u64> == 0x2008<u64> : bool)
  Class: Eq_10
  DataType: bool
  OrigDataType: bool
T_11: (in t1_9 : (ptr64 code))
  Class: Eq_11
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_12: (in 0000000000002030 : ptr64)
  Class: Eq_12
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_13 t0000)))
T_13: (in Mem0[0x0000000000002030<p64>:word64] : word64)
  Class: Eq_11
  DataType: (ptr64 code)
  OrigDataType: word64
T_14: (in 0<64> : word64)
  Class: Eq_11
  DataType: (ptr64 code)
  OrigDataType: word64
T_15: (in t1_9 == null : bool)
  Class: Eq_15
  DataType: bool
  OrigDataType: bool
T_16: (in t1_13 : word64)
  Class: Eq_16
  DataType: word64
  OrigDataType: word64
T_17: (in a5_7 : Eq_17)
  Class: Eq_17
  DataType: Eq_17
  OrigDataType: (union (int64 u0) (uint64 u1))
T_18: (in 0000000000002008 : ptr64)
  Class: Eq_18
  DataType: int64
  OrigDataType: (union (int64 u0) (ptr64 u1))
T_19: (in 0000000000002008 : ptr64)
  Class: Eq_19
  DataType: int64
  OrigDataType: (union (int64 u1) (ptr64 u0))
T_20: (in 0x2008<u64> - 0x2008<u64> : word64)
  Class: Eq_17
  DataType: Eq_17
  OrigDataType: int64
T_21: (in 0x3F<u32> : uint32)
  Class: Eq_21
  DataType: uint32
  OrigDataType: uint32
T_22: (in a5_7 >> 0x3F<u32> : word64)
  Class: Eq_22
  DataType: Eq_22
  OrigDataType: (union (int64 u1) (uint64 u0))
T_23: (in 3<u32> : uint32)
  Class: Eq_23
  DataType: uint32
  OrigDataType: uint32
T_24: (in a5_7 >> 3<u32> : word64)
  Class: Eq_24
  DataType: Eq_24
  OrigDataType: (union (int64 u1) (uint64 u0))
T_25: (in (a5_7 >>u 0x3F<u32>) + (a5_7 >> 3<u32>) : word64)
  Class: Eq_25
  DataType: Eq_25
  OrigDataType: (union (int64 u1) (uint64 u0))
T_26: (in 1<i32> : int32)
  Class: Eq_26
  DataType: int32
  OrigDataType: int32
T_27: (in (a5_7 >>u 0x3F<u32>) + (a5_7 >> 3<u32>) >> 1<i32> : word64)
  Class: Eq_27
  DataType: int64
  OrigDataType: int64
T_28: (in 0<64> : word64)
  Class: Eq_27
  DataType: int64
  OrigDataType: word64
T_29: (in (a5_7 >>u 0x3F<u32>) + (a5_7 >> 3<u32>) >> 1<i32> == 0<64> : bool)
  Class: Eq_29
  DataType: bool
  OrigDataType: bool
T_30: (in t1_14 : (ptr64 code))
  Class: Eq_30
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_31: (in 0000000000002048 : ptr64)
  Class: Eq_31
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_32 t0000)))
T_32: (in Mem0[0x0000000000002048<p64>:word64] : word64)
  Class: Eq_30
  DataType: (ptr64 code)
  OrigDataType: word64
T_33: (in 0<64> : word64)
  Class: Eq_30
  DataType: (ptr64 code)
  OrigDataType: word64
T_34: (in t1_14 == null : bool)
  Class: Eq_34
  DataType: bool
  OrigDataType: bool
T_35: (in t1_20 : word64)
  Class: Eq_35
  DataType: word64
  OrigDataType: word64
T_36: (in ra : word64)
  Class: Eq_36
  DataType: word64
  OrigDataType: word64
T_37: (in s0_16 : (ptr64 byte))
  Class: Eq_37
  DataType: (ptr64 byte)
  OrigDataType: (ptr64 (struct (0 T_55 t0000)))
T_38: (in 0000000000002050 : ptr64)
  Class: Eq_37
  DataType: (ptr64 byte)
  OrigDataType: ptr64
T_39: (in 0000000000002050 : ptr64)
  Class: Eq_39
  DataType: (ptr64 byte)
  OrigDataType: (ptr64 (struct (0 T_40 t0000)))
T_40: (in Mem5[0x0000000000002050<p64>:byte] : byte)
  Class: Eq_40
  DataType: byte
  OrigDataType: byte
T_41: (in CONVERT(Mem5[0x0000000000002050<p64>:byte], byte, word64) : word64)
  Class: Eq_41
  DataType: word64
  OrigDataType: word64
T_42: (in 0<64> : word64)
  Class: Eq_41
  DataType: word64
  OrigDataType: word64
T_43: (in (word64) g_b2050 != 0<64> : bool)
  Class: Eq_43
  DataType: bool
  OrigDataType: bool
T_44: (in a5_12 : (ptr64 code))
  Class: Eq_44
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_45: (in 0000000000002040 : ptr64)
  Class: Eq_45
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_46 t0000)))
T_46: (in Mem10[0x0000000000002040<p64>:word64] : word64)
  Class: Eq_44
  DataType: (ptr64 code)
  OrigDataType: word64
T_47: (in 0<64> : word64)
  Class: Eq_44
  DataType: (ptr64 code)
  OrigDataType: word64
T_48: (in a5_12 == null : bool)
  Class: Eq_48
  DataType: bool
  OrigDataType: bool
T_49: (in deregister_tm_clones : ptr64)
  Class: Eq_49
  DataType: (ptr64 Eq_49)
  OrigDataType: (ptr64 (fn T_51 ()))
T_50: (in signature of deregister_tm_clones : void)
  Class: Eq_49
  DataType: (ptr64 Eq_49)
  OrigDataType: 
T_51: (in deregister_tm_clones() : void)
  Class: Eq_51
  DataType: void
  OrigDataType: void
T_52: (in 1<8> : byte)
  Class: Eq_52
  DataType: byte
  OrigDataType: byte
T_53: (in 0<64> : word64)
  Class: Eq_53
  DataType: word64
  OrigDataType: word64
T_54: (in s0_16 + 0<64> : word64)
  Class: Eq_54
  DataType: ptr64
  OrigDataType: ptr64
T_55: (in Mem25[s0_16 + 0<64>:byte] : byte)
  Class: Eq_52
  DataType: byte
  OrigDataType: byte
T_56: (in t1_34 : word64)
  Class: Eq_56
  DataType: word64
  OrigDataType: word64
T_57: (in register_tm_clones : ptr64)
  Class: Eq_57
  DataType: (ptr64 Eq_57)
  OrigDataType: (ptr64 (fn T_59 ()))
T_58: (in signature of register_tm_clones : void)
  Class: Eq_57
  DataType: (ptr64 Eq_57)
  OrigDataType: 
T_59: (in register_tm_clones() : void)
  Class: Eq_59
  DataType: void
  OrigDataType: void
T_60: (in fn0000000000000440 : ptr64)
  Class: Eq_60
  DataType: (ptr64 Eq_60)
  OrigDataType: (ptr64 (fn T_62 ()))
T_61: (in signature of fn0000000000000440 : void)
  Class: Eq_60
  DataType: (ptr64 Eq_60)
  OrigDataType: 
T_62: (in fn0000000000000440() : void)
  Class: Eq_62
  DataType: void
  OrigDataType: void
T_63: (in fn0000000000000450 : ptr64)
  Class: Eq_63
  DataType: (ptr64 Eq_63)
  OrigDataType: (ptr64 (fn T_65 ()))
T_64: (in signature of fn0000000000000450 : void)
  Class: Eq_63
  DataType: (ptr64 Eq_63)
  OrigDataType: 
T_65: (in fn0000000000000450() : void)
  Class: Eq_65
  DataType: void
  OrigDataType: void
*/
typedef struct Globals {
	<anonymous> t0840;	// 840
	<anonymous> t0E00;	// E00
	<anonymous> * ptr2018;	// 2018
	<anonymous> * ptr2020;	// 2020
	<anonymous> * ptr2030;	// 2030
	<anonymous> * ptr2040;	// 2040
	<anonymous> * ptr2048;	// 2048
	byte b2050;	// 2050
} Eq_1;

typedef union Eq_17 {
	int64 u0;
	uint64 u1;
} Eq_17;

typedef union Eq_18 {
	int64 u0;
	ptr64 u1;
} Eq_18;

typedef union Eq_19 {
	int64 u0;
	ptr64 u1;
} Eq_19;

typedef union Eq_22 {
	int64 u0;
	uint64 u1;
} Eq_22;

typedef union Eq_24 {
	int64 u0;
	uint64 u1;
} Eq_24;

typedef union Eq_25 {
	int64 u0;
	uint64 u1;
} Eq_25;

typedef void (Eq_49)();

typedef void (Eq_57)();

typedef void (Eq_60)();

typedef void (Eq_63)();

