// hexdump-Os.h
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (4020 byte b4020))
	globals_t (in globals : (ptr64 (struct "Globals")))
Eq_35: (union "Eq_35" (int64 u0) (uint64 u1))
	T_35 (in rsi_6 : Eq_35)
	T_38 (in 0x4020<u64> - 0x4020<u64> : word64)
Eq_36: (union "Eq_36" (int64 u0) (ptr64 u1))
	T_36 (in 0000000000004020 : ptr64)
Eq_37: (union "Eq_37" (int64 u0) (ptr64 u1))
	T_37 (in 0000000000004020 : ptr64)
Eq_40: (union "Eq_40" (int64 u0) (uint64 u1))
	T_40 (in rsi_6 >> 0x3F<64> : word64)
Eq_42: (union "Eq_42" (int64 u0) (uint64 u1))
	T_42 (in rsi_6 >> 3<64> : word64)
Eq_43: (union "Eq_43" (int64 u0) (uint64 u1))
	T_43 (in (rsi_6 >>u 0x3F<64>) + (rsi_6 >> 3<64>) : word64)
Eq_60: (fn void ())
	T_60 (in deregister_tm_clones : ptr64)
	T_61 (in signature of deregister_tm_clones : void)
Eq_69: (fn void ())
	T_69 (in register_tm_clones : ptr64)
	T_70 (in signature of register_tm_clones : void)
// Type Variables ////////////
globals_t: (in globals : (ptr64 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr64 Eq_1)
  OrigDataType: (ptr64 (struct "Globals"))
T_2: (in __gmon_start__ : ptr64)
  Class: Eq_2
  DataType: word64
  OrigDataType: 
T_3: (in signature of __gmon_start__ : void)
  Class: Eq_3
  DataType: Eq_3
  OrigDataType: 
T_4: (in 0<64> : word64)
  Class: Eq_2
  DataType: word64
  OrigDataType: word64
T_5: (in __gmon_start__ == 0<64> : bool)
  Class: Eq_5
  DataType: bool
  OrigDataType: bool
T_6: (in __gmon_start__ : ptr64)
  Class: Eq_6
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_7: (in rsi : (ptr64 (ptr64 byte)))
  Class: Eq_7
  DataType: (ptr64 (ptr64 byte))
  OrigDataType: (ptr64 (struct (0 T_11 t0000)))
T_8: (in rdi_10 : (ptr64 byte))
  Class: Eq_8
  DataType: (ptr64 byte)
  OrigDataType: word64
T_9: (in 0<64> : word64)
  Class: Eq_9
  DataType: word64
  OrigDataType: word64
T_10: (in rsi + 0<64> : word64)
  Class: Eq_10
  DataType: word64
  OrigDataType: word64
T_11: (in Mem6[rsi + 0<64>:word64] : word64)
  Class: Eq_8
  DataType: (ptr64 byte)
  OrigDataType: word64
T_12: (in rcx_14 : word64)
  Class: Eq_12
  DataType: word64
  OrigDataType: word64
T_13: (in 0xFFFFFFFFFFFFFFFF<64> : word64)
  Class: Eq_12
  DataType: word64
  OrigDataType: word64
T_14: (in hexdump : ptr64)
  Class: Eq_14
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_15: (in signature of hexdump : void)
  Class: Eq_15
  DataType: Eq_15
  OrigDataType: 
T_16: (in rdi_69 : word64)
  Class: Eq_8
  DataType: (ptr64 byte)
  OrigDataType: (ptr64 (struct (0 T_23 t0000)))
T_17: (in 1<i64> : int64)
  Class: Eq_17
  DataType: int64
  OrigDataType: int64
T_18: (in rdi_69 + 1<i64> : word64)
  Class: Eq_8
  DataType: (ptr64 byte)
  OrigDataType: word64
T_19: (in 1<64> : word64)
  Class: Eq_19
  DataType: word64
  OrigDataType: word64
T_20: (in rcx_14 - 1<64> : word64)
  Class: Eq_12
  DataType: word64
  OrigDataType: word64
T_21: (in 0<64> : word64)
  Class: Eq_21
  DataType: word64
  OrigDataType: word64
T_22: (in rdi_69 + 0<64> : word64)
  Class: Eq_22
  DataType: word64
  OrigDataType: word64
T_23: (in Mem6[rdi_69 + 0<64>:byte] : byte)
  Class: Eq_23
  DataType: byte
  OrigDataType: byte
T_24: (in 0<8> : byte)
  Class: Eq_23
  DataType: byte
  OrigDataType: byte
T_25: (in *rdi_69 == 0<8> : bool)
  Class: Eq_25
  DataType: bool
  OrigDataType: bool
T_26: (in 0<64> : word64)
  Class: Eq_12
  DataType: word64
  OrigDataType: word64
T_27: (in rcx_14 == 0<64> : bool)
  Class: Eq_27
  DataType: bool
  OrigDataType: bool
T_28: (in 0000000000004020 : ptr64)
  Class: Eq_28
  DataType: ptr64
  OrigDataType: ptr64
T_29: (in 0000000000004020 : ptr64)
  Class: Eq_28
  DataType: ptr64
  OrigDataType: ptr64
T_30: (in 0x4020<u64> == 0x4020<u64> : bool)
  Class: Eq_30
  DataType: bool
  OrigDataType: bool
T_31: (in _ITM_deregisterTMCloneTable : ptr64)
  Class: Eq_31
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_32: (in signature of _ITM_deregisterTMCloneTable : void)
  Class: Eq_32
  DataType: Eq_32
  OrigDataType: 
T_33: (in 0<64> : word64)
  Class: Eq_31
  DataType: (ptr64 code)
  OrigDataType: word64
T_34: (in _ITM_deregisterTMCloneTable == null : bool)
  Class: Eq_34
  DataType: bool
  OrigDataType: bool
T_35: (in rsi_6 : Eq_35)
  Class: Eq_35
  DataType: Eq_35
  OrigDataType: (union (int64 u0) (uint64 u1))
T_36: (in 0000000000004020 : ptr64)
  Class: Eq_36
  DataType: int64
  OrigDataType: (union (int64 u0) (ptr64 u1))
T_37: (in 0000000000004020 : ptr64)
  Class: Eq_37
  DataType: int64
  OrigDataType: (union (int64 u1) (ptr64 u0))
T_38: (in 0x4020<u64> - 0x4020<u64> : word64)
  Class: Eq_35
  DataType: Eq_35
  OrigDataType: int64
T_39: (in 0x3F<64> : word64)
  Class: Eq_39
  DataType: word64
  OrigDataType: word64
T_40: (in rsi_6 >> 0x3F<64> : word64)
  Class: Eq_40
  DataType: Eq_40
  OrigDataType: (union (int64 u1) (uint64 u0))
T_41: (in 3<64> : word64)
  Class: Eq_41
  DataType: word64
  OrigDataType: word64
T_42: (in rsi_6 >> 3<64> : word64)
  Class: Eq_42
  DataType: Eq_42
  OrigDataType: (union (int64 u1) (uint64 u0))
T_43: (in (rsi_6 >>u 0x3F<64>) + (rsi_6 >> 3<64>) : word64)
  Class: Eq_43
  DataType: Eq_43
  OrigDataType: (union (int64 u1) (uint64 u0))
T_44: (in 1<64> : word64)
  Class: Eq_44
  DataType: word64
  OrigDataType: word64
T_45: (in (rsi_6 >>u 0x3F<64>) + (rsi_6 >> 3<64>) >> 1<64> : word64)
  Class: Eq_45
  DataType: int64
  OrigDataType: int64
T_46: (in 0<64> : word64)
  Class: Eq_45
  DataType: int64
  OrigDataType: word64
T_47: (in (rsi_6 >>u 0x3F<64>) + (rsi_6 >> 3<64>) >> 1<64> == 0<64> : bool)
  Class: Eq_47
  DataType: bool
  OrigDataType: bool
T_48: (in _ITM_registerTMCloneTable : ptr64)
  Class: Eq_48
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_49: (in signature of _ITM_registerTMCloneTable : void)
  Class: Eq_49
  DataType: Eq_49
  OrigDataType: 
T_50: (in 0<64> : word64)
  Class: Eq_48
  DataType: (ptr64 code)
  OrigDataType: word64
T_51: (in _ITM_registerTMCloneTable == null : bool)
  Class: Eq_51
  DataType: bool
  OrigDataType: bool
T_52: (in 0000000000004020 : ptr64)
  Class: Eq_52
  DataType: (ptr64 byte)
  OrigDataType: (ptr64 (struct (0 T_53 t0000)))
T_53: (in Mem0[0x0000000000004020<p64>:byte] : byte)
  Class: Eq_53
  DataType: byte
  OrigDataType: byte
T_54: (in 0<8> : byte)
  Class: Eq_53
  DataType: byte
  OrigDataType: byte
T_55: (in g_b4020 != 0<8> : bool)
  Class: Eq_55
  DataType: bool
  OrigDataType: bool
T_56: (in __cxa_finalize : ptr64)
  Class: Eq_56
  DataType: word64
  OrigDataType: 
T_57: (in signature of __cxa_finalize : void)
  Class: Eq_57
  DataType: Eq_57
  OrigDataType: 
T_58: (in 0<64> : word64)
  Class: Eq_56
  DataType: word64
  OrigDataType: word64
T_59: (in __cxa_finalize == 0<64> : bool)
  Class: Eq_59
  DataType: bool
  OrigDataType: bool
T_60: (in deregister_tm_clones : ptr64)
  Class: Eq_60
  DataType: (ptr64 Eq_60)
  OrigDataType: (ptr64 (fn T_62 ()))
T_61: (in signature of deregister_tm_clones : void)
  Class: Eq_60
  DataType: (ptr64 Eq_60)
  OrigDataType: 
T_62: (in deregister_tm_clones() : void)
  Class: Eq_62
  DataType: void
  OrigDataType: void
T_63: (in 1<8> : byte)
  Class: Eq_53
  DataType: byte
  OrigDataType: byte
T_64: (in 0000000000004020 : ptr64)
  Class: Eq_64
  DataType: (ptr64 byte)
  OrigDataType: (ptr64 (struct (0 T_65 t0000)))
T_65: (in Mem22[0x0000000000004020<p64>:byte] : byte)
  Class: Eq_53
  DataType: byte
  OrigDataType: byte
T_66: (in rax_27 : word64)
  Class: Eq_66
  DataType: word64
  OrigDataType: word64
T_67: (in __cxa_finalize : ptr64)
  Class: Eq_67
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_68: (in signature of __cxa_finalize : void)
  Class: Eq_68
  DataType: Eq_68
  OrigDataType: 
T_69: (in register_tm_clones : ptr64)
  Class: Eq_69
  DataType: (ptr64 Eq_69)
  OrigDataType: (ptr64 (fn T_71 ()))
T_70: (in signature of register_tm_clones : void)
  Class: Eq_69
  DataType: (ptr64 Eq_69)
  OrigDataType: 
T_71: (in register_tm_clones() : void)
  Class: Eq_71
  DataType: void
  OrigDataType: void
*/
typedef struct Globals {
	byte b4020;	// 4020
} Eq_1;

typedef union Eq_35 {
	int64 u0;
	uint64 u1;
} Eq_35;

typedef union Eq_36 {
	int64 u0;
	ptr64 u1;
} Eq_36;

typedef union Eq_37 {
	int64 u0;
	ptr64 u1;
} Eq_37;

typedef union Eq_40 {
	int64 u0;
	uint64 u1;
} Eq_40;

typedef union Eq_42 {
	int64 u0;
	uint64 u1;
} Eq_42;

typedef union Eq_43 {
	int64 u0;
	uint64 u1;
} Eq_43;

typedef void (Eq_60)();

typedef void (Eq_69)();

