// hexdump-O2_data.c
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O2.h"

struct Eq_n * g_ptr6EC03010 = &g_t6EC02330;
Eq_n g_t6EC03024 = 
	{
		0xFFFFFFFF
	};
word32 g_dw6EC03030 = 0x02;
