// hexdump-O0_data.c
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O0.h"

struct Eq_n * g_ptr637C3010 = &g_t637C23F0;
Eq_n g_t637C3024 = 
	{
		0xFFFFFFFF
	};
word32 g_dw637C3030 = 0x02;
