// hexdump-O2_bss.c
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O2.h"

struct Eq_n g_t68D47000 = 
	{
		0x00,
		0x00,
		0x00,
	};
word32 g_dw68D47018 = 0x00;
word32 g_dw68D47020 = 0x00;
uint64 g_qw68D47030 = 0x00;
word32 g_dw68D47038 = 0x00;
word32 g_dw68D47050 = 0x00;
word32 g_dw68D47060 = 0x00;
int32 g_dw68D47064 = 0;
struct Eq_n * g_ptr68D47068 = null;
struct Eq_n * g_ptr68D47080 = null;
word32 g_dw68D47088 = 0x00;
struct _RTL_CRITICAL_SECTION g_t68D470A0 = 
	{
		null,
		0,
		0,
		null,
		null,
		0x00,
	};
