// hexdump-O0_got.c
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O0.h"

word64 g_qw1FD8 = 0x00;
<anonymous> * g_ptr1FE0 = null;
<anonymous> * g_ptr1FE8 = null;
<anonymous> * g_ptr1FF8 = null;
