// hexdump-O0_init.c
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O0.h"

// 0000000000000690: void _init(Register (ptr64 code) ra)
void _init(<anonymous> * ra)
{
	if (g_ptr10B30 == null)
	{
		(*(<anonymous> **) 0x00020A50)();
		(*(<anonymous> **) 0x00020A48)();
		ra();
	}
	else
		g_ptr10B30();
}

