// hexdump-O2_plt_got.c
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O2.h"

// 00001050: void fn00001050(Register (ptr32 Eq_n) ebx)
// Called from:
//      __do_global_dtors_aux
void fn00001050(struct Eq_n * ebx)
{
	ebx->ptrFFFFFFF0();
}

// 00001058: void fn00001058(Register (ptr32 Eq_n) ebx)
// Called from:
//      main
void fn00001058(struct Eq_n * ebx)
{
	ebx->ptrFFFFFFF8();
}

