// hexdump-O2.h
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr64 (struct "Globals")))
Eq_6: (struct "Eq_6" (11BD0 (ptr64 code) ptr11BD0))
	T_6 (in r27 : (ptr64 Eq_6))
Eq_18: (fn (ptr64 code) (word64, word64, word64, (ptr64 Eq_23), word64))
	T_18 (in fn0000000000000718 : ptr64)
	T_19 (in signature of fn0000000000000718 : void)
Eq_23: (struct "Eq_23" (FFFF8028 (ptr64 code) ptrFFFF8028))
	T_23 (in r29 : (ptr64 Eq_23))
	T_25 (in 00000000000268E8 : ptr64)
Eq_29: (fn void ((ptr64 code), word64, word64, (ptr64 Eq_34)))
	T_29 (in fn0000000000000748 : ptr64)
	T_30 (in signature of fn0000000000000748 : void)
Eq_34: (struct "Eq_34" (FFFF7E40 (ptr64 code) ptrFFFF7E40))
	T_34 (in r29 : (ptr64 Eq_34))
	T_35 (in 0000000000026918 : ptr64)
	T_254 (in r26 + 0x19888<64> : word64)
Eq_41: (struct "Eq_41" (11B38 (ptr64 code) ptr11B38))
	T_41 (in r27 : (ptr64 Eq_41))
Eq_48: (struct "Eq_48" (11B1C (ptr64 code) ptr11B1C))
	T_48 (in r26_24 : (ptr64 Eq_48))
Eq_56: (struct "Eq_56" 0001 (FFFF8000 (ptr64 code) ptrFFFF8000) (FFFF8008 (ptr64 code) ptrFFFF8008) (FFFF8038 word64 qwFFFF8038) (FFFF8040 word64 qwFFFF8040))
	T_56 (in r29 : (ptr64 Eq_56))
	T_81 (in r29 : (ptr64 Eq_56))
	T_86 (in r11_105 : (ptr64 Eq_56))
	T_109 (in r13_45 : (ptr64 Eq_56))
	T_135 (in r26 + 0x199B0<64> : word64)
	T_201 (in r26 + 0x1995C<64> : word64)
	T_271 (in 0000000000026F88 : ptr64)
Eq_90: (fn word64 (word64, word64))
	T_90 (in __extbl : ptr64)
	T_91 (in signature of __extbl : void)
Eq_111: (fn word64 (Eq_113, byte))
	T_111 (in __src : ptr64)
	T_112 (in signature of __src : void)
	T_213 (in __src : ptr64)
	T_219 (in __src : ptr64)
Eq_113: (union "Eq_113" (uint64 u0) (ptr64 u1))
	T_113 (in  : word64)
	T_117 (in r29 - 0x81A8<64> - r8 : word64)
	T_209 (in r17_10 : Eq_113)
	T_212 (in r29 - 0x8010<64> - r0 : word64)
	T_222 (in (r17_10 >> 0x3F<8>) + r8 : word64)
Eq_142: (fn word64 (word64, word64, (ptr64 Eq_56), ptr64))
	T_142 (in fn0000000000000568 : ptr64)
	T_143 (in signature of fn0000000000000568 : void)
Eq_159: (fn ui64 (word64, word64))
	T_159 (in __insbl : ptr64)
	T_160 (in signature of __insbl : void)
Eq_165: (fn word64 (word64, word64))
	T_165 (in __mskbl : ptr64)
	T_166 (in signature of __mskbl : void)
Eq_170: (fn word64 (word64, ui64))
	T_170 (in __stq_u : ptr64)
	T_171 (in signature of __stq_u : void)
Eq_269: (fn void (word64, uint64, word64, word64, word64, word64, word64, (ptr64 Eq_56)))
	T_269 (in fn0000000000000618 : ptr64)
	T_270 (in signature of fn0000000000000618 : void)
// Type Variables ////////////
globals_t: (in globals : (ptr64 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr64 Eq_1)
  OrigDataType: (ptr64 (struct "Globals"))
T_2: (in r0 : word64)
  Class: Eq_2
  DataType: word64
  OrigDataType: word64
T_3: (in r8 : word64)
  Class: Eq_3
  DataType: word64
  OrigDataType: word64
T_4: (in r24 : word64)
  Class: Eq_4
  DataType: word64
  OrigDataType: word64
T_5: (in r26 : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_6: (in r27 : (ptr64 Eq_6))
  Class: Eq_6
  DataType: (ptr64 Eq_6)
  OrigDataType: (ptr64 (struct (11BD0 T_11 t11BD0)))
T_7: (in r26_15 : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_8: (in r27_8 : (ptr64 code))
  Class: Eq_8
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_9: (in 0x11BD0<64> : word64)
  Class: Eq_9
  DataType: word64
  OrigDataType: word64
T_10: (in r27 + 0x11BD0<64> : word64)
  Class: Eq_10
  DataType: word64
  OrigDataType: word64
T_11: (in Mem0[r27 + 0x11BD0<64>:word64] : word64)
  Class: Eq_8
  DataType: (ptr64 code)
  OrigDataType: word64
T_12: (in 0<64> : word64)
  Class: Eq_8
  DataType: (ptr64 code)
  OrigDataType: word64
T_13: (in r27_8 == null : bool)
  Class: Eq_13
  DataType: bool
  OrigDataType: bool
T_14: (in 0<64> : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_15: (in 0<64> : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_16: (in 0<64> : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_17: (in r16_28 : (ptr64 code))
  Class: Eq_17
  DataType: (ptr64 code)
  OrigDataType: word64
T_18: (in fn0000000000000718 : ptr64)
  Class: Eq_18
  DataType: (ptr64 Eq_18)
  OrigDataType: (ptr64 (fn T_26 (T_2, T_3, T_7, T_25, T_5)))
T_19: (in signature of fn0000000000000718 : void)
  Class: Eq_18
  DataType: (ptr64 Eq_18)
  OrigDataType: 
T_20: (in r0 : word64)
  Class: Eq_2
  DataType: word64
  OrigDataType: word64
T_21: (in r8 : word64)
  Class: Eq_3
  DataType: word64
  OrigDataType: word64
T_22: (in r26 : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_23: (in r29 : (ptr64 Eq_23))
  Class: Eq_23
  DataType: (ptr64 Eq_23)
  OrigDataType: (ptr64 (struct (FFFF8028 T_230 tFFFF8028)))
T_24: (in qwArg00 : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_25: (in 00000000000268E8 : ptr64)
  Class: Eq_23
  DataType: (ptr64 Eq_23)
  OrigDataType: ptr64
T_26: (in fn0000000000000718(r0, r8, r26_15, (struct Eq_23 *) 0x268E8<u64>, r26) : word64)
  Class: Eq_17
  DataType: (ptr64 code)
  OrigDataType: word64
T_27: (in 0<64> : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_28: (in 0<64> : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_29: (in fn0000000000000748 : ptr64)
  Class: Eq_29
  DataType: (ptr64 Eq_29)
  OrigDataType: (ptr64 (fn T_36 (T_17, T_4, T_7, T_35)))
T_30: (in signature of fn0000000000000748 : void)
  Class: Eq_29
  DataType: (ptr64 Eq_29)
  OrigDataType: 
T_31: (in r16 : (ptr64 code))
  Class: Eq_17
  DataType: (ptr64 code)
  OrigDataType: word64
T_32: (in r24 : word64)
  Class: Eq_4
  DataType: word64
  OrigDataType: word64
T_33: (in r26 : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_34: (in r29 : (ptr64 Eq_34))
  Class: Eq_34
  DataType: (ptr64 Eq_34)
  OrigDataType: (ptr64 (struct (FFFF7E40 T_237 tFFFF7E40)))
T_35: (in 0000000000026918 : ptr64)
  Class: Eq_34
  DataType: (ptr64 Eq_34)
  OrigDataType: ptr64
T_36: (in fn0000000000000748(r16_28, r24, r26_15, (struct Eq_34 *) 0x26918<u64>) : void)
  Class: Eq_36
  DataType: void
  OrigDataType: void
T_37: (in r0 : word64)
  Class: Eq_37
  DataType: word64
  OrigDataType: word64
T_38: (in r9 : word64)
  Class: Eq_38
  DataType: word64
  OrigDataType: word64
T_39: (in r17 : word64)
  Class: Eq_39
  DataType: word64
  OrigDataType: word64
T_40: (in r26 : word64)
  Class: Eq_40
  DataType: word64
  OrigDataType: word64
T_41: (in r27 : (ptr64 Eq_41))
  Class: Eq_41
  DataType: (ptr64 Eq_41)
  OrigDataType: (ptr64 (struct (11B38 T_45 t11B38)))
T_42: (in r27_8 : (ptr64 code))
  Class: Eq_42
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_43: (in 0x11B38<64> : word64)
  Class: Eq_43
  DataType: word64
  OrigDataType: word64
T_44: (in r27 + 0x11B38<64> : word64)
  Class: Eq_44
  DataType: word64
  OrigDataType: word64
T_45: (in Mem0[r27 + 0x11B38<64>:word64] : word64)
  Class: Eq_42
  DataType: (ptr64 code)
  OrigDataType: word64
T_46: (in r9_20 : word64)
  Class: Eq_46
  DataType: word64
  OrigDataType: word64
T_47: (in r0_21 : word64)
  Class: Eq_47
  DataType: word64
  OrigDataType: word64
T_48: (in r26_24 : (ptr64 Eq_48))
  Class: Eq_48
  DataType: (ptr64 Eq_48)
  OrigDataType: (ptr64 (struct (11B1C T_53 t11B1C)))
T_49: (in r8_25 : word64)
  Class: Eq_49
  DataType: word64
  OrigDataType: word64
T_50: (in r27_36 : (ptr64 code))
  Class: Eq_50
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_51: (in 0x11B1C<64> : word64)
  Class: Eq_51
  DataType: word64
  OrigDataType: word64
T_52: (in r26_24 + 0x11B1C<64> : word64)
  Class: Eq_52
  DataType: word64
  OrigDataType: word64
T_53: (in Mem16[r26_24 + 0x11B1C<64>:word64] : word64)
  Class: Eq_50
  DataType: (ptr64 code)
  OrigDataType: word64
T_54: (in r0 : word64)
  Class: Eq_54
  DataType: word64
  OrigDataType: word64
T_55: (in r26 : word64)
  Class: Eq_55
  DataType: word64
  OrigDataType: word64
T_56: (in r29 : (ptr64 Eq_56))
  Class: Eq_56
  DataType: (ptr64 Eq_56)
  OrigDataType: (ptr64 (struct (FFFF8000 T_70 tFFFF8000)))
T_57: (in r16Out : ptr64)
  Class: Eq_57
  DataType: ptr64
  OrigDataType: ptr64
T_58: (in r16_16 : ptr64)
  Class: Eq_57
  DataType: ptr64
  OrigDataType: word64
T_59: (in 0x8010<64> : word64)
  Class: Eq_59
  DataType: word64
  OrigDataType: word64
T_60: (in r29 - 0x8010<64> : word64)
  Class: Eq_57
  DataType: ptr64
  OrigDataType: word64
T_61: (in 0x8010<64> : word64)
  Class: Eq_61
  DataType: word64
  OrigDataType: word64
T_62: (in r29 - 0x8010<64> : word64)
  Class: Eq_54
  DataType: word64
  OrigDataType: word64
T_63: (in r29 - 0x8010<64> == r0 : bool)
  Class: Eq_63
  DataType: bool
  OrigDataType: bool
T_64: (in CONVERT(r29 - 0x8010<64> == r0, bool, word64) : word64)
  Class: Eq_64
  DataType: word64
  OrigDataType: word64
T_65: (in 0<64> : word64)
  Class: Eq_64
  DataType: word64
  OrigDataType: word64
T_66: (in (word64) (r29 - 0x8010<64> == r0) != 0<64> : bool)
  Class: Eq_66
  DataType: bool
  OrigDataType: bool
T_67: (in r27_13 : (ptr64 code))
  Class: Eq_67
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_68: (in 0xFFFFFFFFFFFF8000<64> : word64)
  Class: Eq_68
  DataType: word64
  OrigDataType: word64
T_69: (in r29 + 0xFFFFFFFFFFFF8000<64> : word64)
  Class: Eq_69
  DataType: word64
  OrigDataType: word64
T_70: (in Mem8[r29 + 0xFFFFFFFFFFFF8000<64>:word64] : word64)
  Class: Eq_67
  DataType: (ptr64 code)
  OrigDataType: word64
T_71: (in 0<64> : word64)
  Class: Eq_67
  DataType: (ptr64 code)
  OrigDataType: word64
T_72: (in r27_13 == null : bool)
  Class: Eq_72
  DataType: bool
  OrigDataType: bool
T_73: (in r27_20 : word64)
  Class: Eq_73
  DataType: word64
  OrigDataType: word64
T_74: (in r0 : word64)
  Class: Eq_54
  DataType: word64
  OrigDataType: word64
T_75: (in r8 : uint64)
  Class: Eq_75
  DataType: uint64
  OrigDataType: uint64
T_76: (in r9 : word64)
  Class: Eq_76
  DataType: word64
  OrigDataType: word64
T_77: (in r10 : word64)
  Class: Eq_77
  DataType: word64
  OrigDataType: word64
T_78: (in r13 : word64)
  Class: Eq_78
  DataType: word64
  OrigDataType: word64
T_79: (in r16 : word64)
  Class: Eq_79
  DataType: word64
  OrigDataType: word64
T_80: (in r26 : word64)
  Class: Eq_55
  DataType: word64
  OrigDataType: word64
T_81: (in r29 : (ptr64 Eq_56))
  Class: Eq_56
  DataType: (ptr64 Eq_56)
  OrigDataType: (ptr64 (struct (FFFF8008 T_102 tFFFF8008) (FFFF8038 T_96 tFFFF8038) (FFFF8040 T_108 tFFFF8040)))
T_82: (in r30_26 : (ptr64 word64))
  Class: Eq_82
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 (struct (0 T_138 t0000)))
T_83: (in fp : ptr64)
  Class: Eq_83
  DataType: ptr64
  OrigDataType: ptr64
T_84: (in 0x30<64> : word64)
  Class: Eq_84
  DataType: ui64
  OrigDataType: ui64
T_85: (in fp - 0x30<64> : word64)
  Class: Eq_82
  DataType: (ptr64 word64)
  OrigDataType: ptr64
T_86: (in r11_105 : (ptr64 Eq_56))
  Class: Eq_56
  DataType: (ptr64 Eq_56)
  OrigDataType: (ptr64 (struct (FFFF8038 T_154 tFFFF8038)))
T_87: (in r12_10 : word64)
  Class: Eq_87
  DataType: word64
  OrigDataType: word64
T_88: (in 0x7FC8<64> : word64)
  Class: Eq_88
  DataType: word64
  OrigDataType: word64
T_89: (in r29 - 0x7FC8<64> : word64)
  Class: Eq_87
  DataType: word64
  OrigDataType: word64
T_90: (in __extbl : ptr64)
  Class: Eq_90
  DataType: (ptr64 Eq_90)
  OrigDataType: (ptr64 (fn T_97 (T_96, T_74)))
T_91: (in signature of __extbl : void)
  Class: Eq_90
  DataType: (ptr64 Eq_90)
  OrigDataType: 
T_92: (in  : word64)
  Class: Eq_92
  DataType: word64
  OrigDataType: 
T_93: (in  : word64)
  Class: Eq_54
  DataType: word64
  OrigDataType: 
T_94: (in 0xFFFFFFFFFFFF8038<64> : word64)
  Class: Eq_94
  DataType: word64
  OrigDataType: word64
T_95: (in r29 + 0xFFFFFFFFFFFF8038<64> : word64)
  Class: Eq_95
  DataType: word64
  OrigDataType: word64
T_96: (in Mem9[r29 + 0xFFFFFFFFFFFF8038<64>:word64] : word64)
  Class: Eq_92
  DataType: word64
  OrigDataType: word64
T_97: (in __extbl(r29->qwFFFF8038, r0) : word64)
  Class: Eq_97
  DataType: word64
  OrigDataType: word64
T_98: (in 0<64> : word64)
  Class: Eq_97
  DataType: word64
  OrigDataType: word64
T_99: (in __extbl(r29->qwFFFF8038, r0) != 0<64> : bool)
  Class: Eq_99
  DataType: bool
  OrigDataType: bool
T_100: (in 0xFFFFFFFFFFFF8008<64> : word64)
  Class: Eq_100
  DataType: word64
  OrigDataType: word64
T_101: (in r29 + 0xFFFFFFFFFFFF8008<64> : word64)
  Class: Eq_101
  DataType: ptr64
  OrigDataType: ptr64
T_102: (in Mem21[r29 + 0xFFFFFFFFFFFF8008<64>:word64] : word64)
  Class: Eq_102
  DataType: (ptr64 code)
  OrigDataType: word64
T_103: (in 0<64> : word64)
  Class: Eq_102
  DataType: (ptr64 code)
  OrigDataType: word64
T_104: (in r29->ptrFFFF8008 == null : bool)
  Class: Eq_104
  DataType: bool
  OrigDataType: bool
T_105: (in r1_51 : uint64)
  Class: Eq_75
  DataType: uint64
  OrigDataType: up64
T_106: (in 0xFFFFFFFFFFFF8040<64> : word64)
  Class: Eq_106
  DataType: word64
  OrigDataType: word64
T_107: (in r29 + 0xFFFFFFFFFFFF8040<64> : word64)
  Class: Eq_107
  DataType: ptr64
  OrigDataType: ptr64
T_108: (in Mem21[r29 + 0xFFFFFFFFFFFF8040<64>:word64] : word64)
  Class: Eq_75
  DataType: uint64
  OrigDataType: word64
T_109: (in r13_45 : (ptr64 Eq_56))
  Class: Eq_56
  DataType: (ptr64 Eq_56)
  OrigDataType: (ptr64 (struct 0001 (FFFF8008 T_102 tFFFF8008) (FFFF8038 T_96 tFFFF8038) (FFFF8040 word64 qwFFFF8040)))
T_110: (in r9_54 : word64)
  Class: Eq_110
  DataType: word64
  OrigDataType: word64
T_111: (in __src : ptr64)
  Class: Eq_111
  DataType: (ptr64 Eq_111)
  OrigDataType: (ptr64 (fn T_119 (T_117, T_118)))
T_112: (in signature of __src : void)
  Class: Eq_111
  DataType: (ptr64 Eq_111)
  OrigDataType: 
T_113: (in  : word64)
  Class: Eq_113
  DataType: Eq_113
  OrigDataType: 
T_114: (in  : byte)
  Class: Eq_114
  DataType: byte
  OrigDataType: 
T_115: (in 0x81A8<64> : word64)
  Class: Eq_115
  DataType: ui64
  OrigDataType: ui64
T_116: (in r29 - 0x81A8<64> : word64)
  Class: Eq_116
  DataType: ptr64
  OrigDataType: ptr64
T_117: (in r29 - 0x81A8<64> - r8 : word64)
  Class: Eq_113
  DataType: Eq_113
  OrigDataType: ptr64
T_118: (in 3<8> : byte)
  Class: Eq_114
  DataType: byte
  OrigDataType: byte
T_119: (in __src(r29 - 0x81A8<64> - r8, 3<8>) : word64)
  Class: Eq_119
  DataType: word64
  OrigDataType: word64
T_120: (in 1<64> : word64)
  Class: Eq_120
  DataType: word64
  OrigDataType: word64
T_121: (in __src(r29 - 0x81A8<64> - r8, 3<8>) - 1<64> : word64)
  Class: Eq_110
  DataType: word64
  OrigDataType: word64
T_122: (in r10_56 : ptr64)
  Class: Eq_122
  DataType: ptr64
  OrigDataType: ptr64
T_123: (in 0x81B0<64> : word64)
  Class: Eq_123
  DataType: ui64
  OrigDataType: ui64
T_124: (in r29 - 0x81B0<64> : word64)
  Class: Eq_122
  DataType: ptr64
  OrigDataType: ptr64
T_125: (in r1_51 < r8 : bool)
  Class: Eq_125
  DataType: bool
  OrigDataType: bool
T_126: (in CONVERT(r1_51 <u r8, bool, word64) : word64)
  Class: Eq_126
  DataType: word64
  OrigDataType: word64
T_127: (in 0<64> : word64)
  Class: Eq_126
  DataType: word64
  OrigDataType: word64
T_128: (in (word64) (r1_51 < r8) == 0<64> : bool)
  Class: Eq_128
  DataType: bool
  OrigDataType: bool
T_129: (in r27_36 : word64)
  Class: Eq_129
  DataType: word64
  OrigDataType: word64
T_130: (in r2_39 : word64)
  Class: Eq_130
  DataType: word64
  OrigDataType: word64
T_131: (in 0xFFFFFFFFFFFF8008<64> : word64)
  Class: Eq_131
  DataType: word64
  OrigDataType: word64
T_132: (in r29 + 0xFFFFFFFFFFFF8008<64> : word64)
  Class: Eq_132
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 word64)
T_133: (in Mem21[r29 + 0xFFFFFFFFFFFF8008<64>:word64] : word64)
  Class: Eq_102
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_134: (in 0x199B0<64> : word64)
  Class: Eq_134
  DataType: word64
  OrigDataType: word64
T_135: (in r26 + 0x199B0<64> : word64)
  Class: Eq_56
  DataType: (ptr64 Eq_56)
  OrigDataType: word64
T_136: (in 0<64> : word64)
  Class: Eq_136
  DataType: word64
  OrigDataType: word64
T_137: (in r30_26 + 0<64> : word64)
  Class: Eq_137
  DataType: ptr64
  OrigDataType: ptr64
T_138: (in Mem93[r30_26 + 0<64>:word64] : word64)
  Class: Eq_138
  DataType: word64
  OrigDataType: word64
T_139: (in 0<64> : word64)
  Class: Eq_138
  DataType: word64
  OrigDataType: word64
T_140: (in r16_100 : ui64)
  Class: Eq_140
  DataType: ui64
  OrigDataType: ui64
T_141: (in r0_102 : word64)
  Class: Eq_141
  DataType: word64
  OrigDataType: word64
T_142: (in fn0000000000000568 : ptr64)
  Class: Eq_142
  DataType: (ptr64 Eq_142)
  OrigDataType: (ptr64 (fn T_145 (T_74, T_80, T_81, T_144)))
T_143: (in signature of fn0000000000000568 : void)
  Class: Eq_142
  DataType: (ptr64 Eq_142)
  OrigDataType: 
T_144: (in out r16_100 : ptr64)
  Class: Eq_57
  DataType: ptr64
  OrigDataType: ptr64
T_145: (in fn0000000000000568(r0, r26, r29, out r16_100) : word64)
  Class: Eq_141
  DataType: word64
  OrigDataType: word64
T_146: (in 0<64> : word64)
  Class: Eq_146
  DataType: word64
  OrigDataType: word64
T_147: (in r30_26 + 0<64> : word64)
  Class: Eq_147
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 word64)
T_148: (in Mem93[r30_26 + 0<64>:word64] : word64)
  Class: Eq_138
  DataType: word64
  OrigDataType: word64
T_149: (in 0<64> : word64)
  Class: Eq_138
  DataType: word64
  OrigDataType: word64
T_150: (in 0<64> : word64)
  Class: Eq_150
  DataType: word64
  OrigDataType: word64
T_151: (in r30_26 + 0<64> : word64)
  Class: Eq_151
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 word64)
T_152: (in Mem93[r30_26 + 0<64>:word64] : word64)
  Class: Eq_138
  DataType: word64
  OrigDataType: word64
T_153: (in 0<64> : word64)
  Class: Eq_138
  DataType: word64
  OrigDataType: word64
T_154: (in r2_107 : word64)
  Class: Eq_92
  DataType: word64
  OrigDataType: word64
T_155: (in 0xFFFFFFFFFFFF8038<64> : word64)
  Class: Eq_155
  DataType: word64
  OrigDataType: word64
T_156: (in r11_105 + 0xFFFFFFFFFFFF8038<64> : word64)
  Class: Eq_156
  DataType: word64
  OrigDataType: word64
T_157: (in Mem93[r11_105 + 0xFFFFFFFFFFFF8038<64>:word64] : word64)
  Class: Eq_92
  DataType: word64
  OrigDataType: word64
T_158: (in r1_108 : ui64)
  Class: Eq_158
  DataType: ui64
  OrigDataType: ui64
T_159: (in __insbl : ptr64)
  Class: Eq_159
  DataType: (ptr64 Eq_159)
  OrigDataType: (ptr64 (fn T_164 (T_163, T_141)))
T_160: (in signature of __insbl : void)
  Class: Eq_159
  DataType: (ptr64 Eq_159)
  OrigDataType: 
T_161: (in  : word64)
  Class: Eq_161
  DataType: word64
  OrigDataType: 
T_162: (in  : word64)
  Class: Eq_141
  DataType: word64
  OrigDataType: 
T_163: (in 1<64> : word64)
  Class: Eq_161
  DataType: word64
  OrigDataType: word64
T_164: (in __insbl(1<64>, r0_102) : word64)
  Class: Eq_158
  DataType: ui64
  OrigDataType: word64
T_165: (in __mskbl : ptr64)
  Class: Eq_165
  DataType: (ptr64 Eq_165)
  OrigDataType: (ptr64 (fn T_169 (T_154, T_141)))
T_166: (in signature of __mskbl : void)
  Class: Eq_165
  DataType: (ptr64 Eq_165)
  OrigDataType: 
T_167: (in  : word64)
  Class: Eq_92
  DataType: word64
  OrigDataType: 
T_168: (in  : word64)
  Class: Eq_141
  DataType: word64
  OrigDataType: 
T_169: (in __mskbl(r2_107, r0_102) : word64)
  Class: Eq_169
  DataType: word64
  OrigDataType: word64
T_170: (in __stq_u : ptr64)
  Class: Eq_170
  DataType: (ptr64 Eq_170)
  OrigDataType: (ptr64 (fn T_178 (T_176, T_177)))
T_171: (in signature of __stq_u : void)
  Class: Eq_170
  DataType: (ptr64 Eq_170)
  OrigDataType: 
T_172: (in  : word64)
  Class: Eq_92
  DataType: word64
  OrigDataType: 
T_173: (in  : word64)
  Class: Eq_173
  DataType: ui64
  OrigDataType: 
T_174: (in 0xFFFFFFFFFFFF8038<64> : word64)
  Class: Eq_174
  DataType: word64
  OrigDataType: word64
T_175: (in r11_105 + 0xFFFFFFFFFFFF8038<64> : word64)
  Class: Eq_175
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 word64)
T_176: (in Mem93[r11_105 + 0xFFFFFFFFFFFF8038<64>:word64] : word64)
  Class: Eq_92
  DataType: word64
  OrigDataType: word64
T_177: (in r1_108 | r16_100 : word64)
  Class: Eq_173
  DataType: ui64
  OrigDataType: ui64
T_178: (in __stq_u(r11_105->qwFFFF8038, r1_108 | r16_100) : word64)
  Class: Eq_178
  DataType: word64
  OrigDataType: word64
T_179: (in 0<64> : word64)
  Class: Eq_179
  DataType: word64
  OrigDataType: word64
T_180: (in r30_26 + 0<64> : word64)
  Class: Eq_180
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 word64)
T_181: (in Mem21[r30_26 + 0<64>:word64] : word64)
  Class: Eq_138
  DataType: word64
  OrigDataType: word64
T_182: (in 0<64> : word64)
  Class: Eq_138
  DataType: word64
  OrigDataType: word64
T_183: (in r1_59 : uint64)
  Class: Eq_183
  DataType: uint64
  OrigDataType: uint64
T_184: (in 1<64> : word64)
  Class: Eq_184
  DataType: up64
  OrigDataType: up64
T_185: (in r1_51 + 1<64> : word64)
  Class: Eq_183
  DataType: uint64
  OrigDataType: up64
T_186: (in 0xFFFFFFFFFFFF8040<64> : word64)
  Class: Eq_186
  DataType: word64
  OrigDataType: word64
T_187: (in r13_45 + 0xFFFFFFFFFFFF8040<64> : word64)
  Class: Eq_187
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 word64)
T_188: (in Mem61[r13_45 + 0xFFFFFFFFFFFF8040<64>:word64] : word64)
  Class: Eq_183
  DataType: uint64
  OrigDataType: word64
T_189: (in r1_63 : (ptr64 (ptr64 code)))
  Class: Eq_189
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_196 t0000)))
T_190: (in 8<64> : word64)
  Class: Eq_190
  DataType: ui64
  OrigDataType: ui64
T_191: (in r1_59 * 8<64> : word64)
  Class: Eq_191
  DataType: ui64
  OrigDataType: ui64
T_192: (in r1_59 * 8<64> + r16 : word64)
  Class: Eq_189
  DataType: (ptr64 (ptr64 code))
  OrigDataType: ui64
T_193: (in r27_84 : word64)
  Class: Eq_193
  DataType: word64
  OrigDataType: word64
T_194: (in 0<64> : word64)
  Class: Eq_194
  DataType: word64
  OrigDataType: word64
T_195: (in r1_63 + 0<64> : word64)
  Class: Eq_195
  DataType: ui64
  OrigDataType: ui64
T_196: (in Mem61[r1_63 + 0<64>:word64] : word64)
  Class: Eq_196
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_197: (in 0xFFFFFFFFFFFF8040<64> : word64)
  Class: Eq_197
  DataType: word64
  OrigDataType: word64
T_198: (in r13_45 + 0xFFFFFFFFFFFF8040<64> : word64)
  Class: Eq_198
  DataType: (ptr64 word64)
  OrigDataType: (ptr64 word64)
T_199: (in Mem61[r13_45 + 0xFFFFFFFFFFFF8040<64>:word64] : word64)
  Class: Eq_75
  DataType: uint64
  OrigDataType: word64
T_200: (in 0x1995C<64> : word64)
  Class: Eq_200
  DataType: word64
  OrigDataType: word64
T_201: (in r26 + 0x1995C<64> : word64)
  Class: Eq_56
  DataType: (ptr64 Eq_56)
  OrigDataType: word64
T_202: (in r2_91 : word64)
  Class: Eq_202
  DataType: word64
  OrigDataType: word64
T_203: (in r1_51 < r8 : bool)
  Class: Eq_203
  DataType: bool
  OrigDataType: bool
T_204: (in CONVERT(r1_51 <u r8, bool, word64) : word64)
  Class: Eq_202
  DataType: word64
  OrigDataType: word64
T_205: (in 0<64> : word64)
  Class: Eq_202
  DataType: word64
  OrigDataType: word64
T_206: (in r2_91 != 0<64> : bool)
  Class: Eq_206
  DataType: bool
  OrigDataType: bool
T_207: (in r16 : word64)
  Class: Eq_207
  DataType: word64
  OrigDataType: word64
T_208: (in 0<64> : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_209: (in r17_10 : Eq_113)
  Class: Eq_113
  DataType: Eq_113
  OrigDataType: uint64
T_210: (in 0x8010<64> : word64)
  Class: Eq_210
  DataType: word64
  OrigDataType: word64
T_211: (in r29 - 0x8010<64> : word64)
  Class: Eq_211
  DataType: word64
  OrigDataType: word64
T_212: (in r29 - 0x8010<64> - r0 : word64)
  Class: Eq_113
  DataType: Eq_113
  OrigDataType: word64
T_213: (in __src : ptr64)
  Class: Eq_111
  DataType: (ptr64 Eq_111)
  OrigDataType: (ptr64 (fn T_215 (T_209, T_214)))
T_214: (in 3<8> : byte)
  Class: Eq_114
  DataType: byte
  OrigDataType: byte
T_215: (in __src(r17_10, 3<8>) : word64)
  Class: Eq_119
  DataType: word64
  OrigDataType: word64
T_216: (in r16_22 : word64)
  Class: Eq_207
  DataType: word64
  OrigDataType: word64
T_217: (in 0x8010<64> : word64)
  Class: Eq_217
  DataType: word64
  OrigDataType: word64
T_218: (in r29 - 0x8010<64> : word64)
  Class: Eq_207
  DataType: word64
  OrigDataType: word64
T_219: (in __src : ptr64)
  Class: Eq_111
  DataType: (ptr64 Eq_111)
  OrigDataType: (ptr64 (fn T_224 (T_222, T_223)))
T_220: (in 0x3F<8> : byte)
  Class: Eq_220
  DataType: byte
  OrigDataType: byte
T_221: (in r17_10 >> 0x3F<8> : word64)
  Class: Eq_221
  DataType: uint64
  OrigDataType: uint64
T_222: (in (r17_10 >> 0x3F<8>) + r8 : word64)
  Class: Eq_113
  DataType: Eq_113
  OrigDataType: uint64
T_223: (in 1<8> : byte)
  Class: Eq_114
  DataType: byte
  OrigDataType: byte
T_224: (in __src((r17_10 >> 0x3F<8>) + r8, 1<8>) : word64)
  Class: Eq_119
  DataType: word64
  OrigDataType: word64
T_225: (in 0<64> : word64)
  Class: Eq_119
  DataType: word64
  OrigDataType: word64
T_226: (in __src((r17_10 >> 0x3F<8>) + r8, 1<8>) == 0<64> : bool)
  Class: Eq_226
  DataType: bool
  OrigDataType: bool
T_227: (in r27_19 : (ptr64 code))
  Class: Eq_227
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_228: (in 0xFFFFFFFFFFFF8028<64> : word64)
  Class: Eq_228
  DataType: word64
  OrigDataType: word64
T_229: (in r29 + 0xFFFFFFFFFFFF8028<64> : word64)
  Class: Eq_229
  DataType: word64
  OrigDataType: word64
T_230: (in Mem18[r29 + 0xFFFFFFFFFFFF8028<64>:word64] : word64)
  Class: Eq_227
  DataType: (ptr64 code)
  OrigDataType: word64
T_231: (in 0<64> : word64)
  Class: Eq_227
  DataType: (ptr64 code)
  OrigDataType: word64
T_232: (in r27_19 == null : bool)
  Class: Eq_232
  DataType: bool
  OrigDataType: bool
T_233: (in r27_28 : word64)
  Class: Eq_233
  DataType: word64
  OrigDataType: word64
T_234: (in r27_14 : (ptr64 code))
  Class: Eq_17
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_235: (in 0xFFFFFFFFFFFF7E40<64> : word64)
  Class: Eq_235
  DataType: word64
  OrigDataType: word64
T_236: (in r29 + 0xFFFFFFFFFFFF7E40<64> : word64)
  Class: Eq_236
  DataType: word64
  OrigDataType: word64
T_237: (in Mem13[r29 + 0xFFFFFFFFFFFF7E40<64>:word64] : word64)
  Class: Eq_17
  DataType: (ptr64 code)
  OrigDataType: word64
T_238: (in r10_11 : word64)
  Class: Eq_238
  DataType: word64
  OrigDataType: word64
T_239: (in 0xFFFFFFFFFFFFFFFF<64> : word64)
  Class: Eq_238
  DataType: word64
  OrigDataType: word64
T_240: (in r27_14 == r16 : bool)
  Class: Eq_240
  DataType: bool
  OrigDataType: bool
T_241: (in CONVERT(r27_14 == r16, bool, word64) : word64)
  Class: Eq_241
  DataType: word64
  OrigDataType: word64
T_242: (in 0<64> : word64)
  Class: Eq_241
  DataType: word64
  OrigDataType: word64
T_243: (in (word64) (r27_14 == r16) != 0<64> : bool)
  Class: Eq_243
  DataType: bool
  OrigDataType: bool
T_244: (in 0<64> : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_245: (in 0<64> : word64)
  Class: Eq_4
  DataType: word64
  OrigDataType: word64
T_246: (in 0<64> : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_247: (in r9_17 : (ptr64 (ptr64 code)))
  Class: Eq_247
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_252 t0000)))
T_248: (in 0x81C0<64> : word64)
  Class: Eq_248
  DataType: ui64
  OrigDataType: ui64
T_249: (in r29 - 0x81C0<64> : word64)
  Class: Eq_247
  DataType: (ptr64 (ptr64 code))
  OrigDataType: ptr64
T_250: (in 0<64> : word64)
  Class: Eq_250
  DataType: word64
  OrigDataType: word64
T_251: (in r9_17 + 0<64> : word64)
  Class: Eq_251
  DataType: ptr64
  OrigDataType: ptr64
T_252: (in Mem13[r9_17 + 0<64>:word64] : word64)
  Class: Eq_17
  DataType: (ptr64 code)
  OrigDataType: word64
T_253: (in 0x19888<64> : word64)
  Class: Eq_253
  DataType: word64
  OrigDataType: word64
T_254: (in r26 + 0x19888<64> : word64)
  Class: Eq_34
  DataType: (ptr64 Eq_34)
  OrigDataType: word64
T_255: (in r27_14 == r16 : bool)
  Class: Eq_255
  DataType: bool
  OrigDataType: bool
T_256: (in CONVERT(r27_14 == r16, bool, word64) : word64)
  Class: Eq_256
  DataType: word64
  OrigDataType: word64
T_257: (in 0<64> : word64)
  Class: Eq_256
  DataType: word64
  OrigDataType: word64
T_258: (in (word64) (r27_14 == r16) == 0<64> : bool)
  Class: Eq_258
  DataType: bool
  OrigDataType: bool
T_259: (in r0 : word64)
  Class: Eq_54
  DataType: word64
  OrigDataType: word64
T_260: (in r8 : uint64)
  Class: Eq_75
  DataType: uint64
  OrigDataType: word64
T_261: (in r9 : word64)
  Class: Eq_76
  DataType: word64
  OrigDataType: word64
T_262: (in r10 : word64)
  Class: Eq_77
  DataType: word64
  OrigDataType: word64
T_263: (in r13 : word64)
  Class: Eq_78
  DataType: word64
  OrigDataType: word64
T_264: (in r16 : word64)
  Class: Eq_79
  DataType: word64
  OrigDataType: word64
T_265: (in r26 : word64)
  Class: Eq_55
  DataType: word64
  OrigDataType: word64
T_266: (in 0<64> : word64)
  Class: Eq_55
  DataType: word64
  OrigDataType: word64
T_267: (in 0<64> : word64)
  Class: Eq_55
  DataType: word64
  OrigDataType: word64
T_268: (in 0<64> : word64)
  Class: Eq_55
  DataType: word64
  OrigDataType: word64
T_269: (in fn0000000000000618 : ptr64)
  Class: Eq_269
  DataType: (ptr64 Eq_269)
  OrigDataType: (ptr64 (fn T_272 (T_259, T_260, T_261, T_262, T_263, T_264, T_265, T_271)))
T_270: (in signature of fn0000000000000618 : void)
  Class: Eq_269
  DataType: (ptr64 Eq_269)
  OrigDataType: 
T_271: (in 0000000000026F88 : ptr64)
  Class: Eq_56
  DataType: (ptr64 Eq_56)
  OrigDataType: ptr64
T_272: (in fn0000000000000618(r0, r8, r9, r10, r13, r16, r26, (struct Eq_56 *) 0x26F88<u64>) : void)
  Class: Eq_272
  DataType: void
  OrigDataType: void
*/
typedef struct Globals {
} Eq_1;

typedef struct Eq_6 {
	<anonymous> * ptr11BD0;	// 11BD0
} Eq_6;

typedef code * (Eq_18)(word64, word64, word64, Eq_23 *, word64);

typedef struct Eq_23 {
	<anonymous> * ptrFFFF8028;	// FFFF8028
} Eq_23;

typedef void (Eq_29)(code *, word64, word64, Eq_34 *);

typedef struct Eq_34 {
	<anonymous> * ptrFFFF7E40;	// FFFF7E40
} Eq_34;

typedef struct Eq_41 {
	<anonymous> * ptr11B38;	// 11B38
} Eq_41;

typedef struct Eq_48 {
	<anonymous> * ptr11B1C;	// 11B1C
} Eq_48;

typedef struct Eq_56 {	// size: 1 1
	<anonymous> * ptrFFFF8000;	// FFFF8000
	<anonymous> * ptrFFFF8008;	// FFFF8008
	word64 qwFFFF8038;	// FFFF8038
	word64 qwFFFF8040;	// FFFF8040
} Eq_56;

typedef word64 (Eq_90)(word64, word64);

typedef word64 (Eq_111)(Eq_113, byte);

typedef union Eq_113 {
	uint64 u0;
	ptr64 u1;
} Eq_113;

typedef word64 (Eq_142)(word64, word64, Eq_56 *, ptr64);

typedef ui64 (Eq_159)(word64, word64);

typedef word64 (Eq_165)(word64, word64);

typedef word64 (Eq_170)(word64, ui64);

typedef void (Eq_269)(word64, uint64, word64, word64, word64, word64, word64, Eq_56 *);

