// hexdump-O0.h
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (4AE code t04AE) (4F2 code t04F2) (512 code t0512) (1FE8 (ptr64 code) ptr1FE8) (2000 (ptr64 code) ptr2000) (2008 (ptr64 code) ptr2008))
	globals_t (in globals : (ptr64 (struct "Globals")))
Eq_14: (fn void ((ptr64 code)))
	T_14 (in frame_dummy : ptr64)
	T_15 (in signature of frame_dummy : void)
Eq_19: (fn void ())
	T_19 (in __do_global_ctors_aux : ptr64)
	T_20 (in signature of __do_global_ctors_aux : void)
Eq_29: (union "Eq_29" (int64 u0) (uint64 u1))
	T_29 (in r1_5 : Eq_29)
	T_32 (in 0x2020<u64> - 0x2020<u64> : word64)
Eq_30: (union "Eq_30" (int64 u0) (ptr64 u1))
	T_30 (in 0000000000002020 : ptr64)
Eq_31: (union "Eq_31" (int64 u0) (ptr64 u1))
	T_31 (in 0000000000002020 : ptr64)
Eq_34: (union "Eq_34" (int64 u0) (uint64 u1))
	T_34 (in r1_5 >> 63<i32> : word64)
Eq_36: (union "Eq_36" (int64 u0) (uint64 u1))
	T_36 (in r1_5 >> 3<i32> : word64)
Eq_37: (union "Eq_37" (int64 u0) (uint64 u1))
	T_37 (in (r1_5 >>u 63<i32>) + (r1_5 >> 3<i32>) : word64)
Eq_42: (union "Eq_42" (bool u0) (byte u1))
	T_42 (in CC : byte)
Eq_43: (fn void ((ptr64 code)))
	T_43 (in register_tm_clones : ptr64)
	T_44 (in signature of register_tm_clones : void)
Eq_46: (fn void ())
	T_46 (in call_frame_dummy : ptr64)
	T_47 (in signature of call_frame_dummy : void)
	T_49 (in call_frame_dummy : ptr64)
Eq_51: (fn void ())
	T_51 (in __do_global_dtors_aux : ptr64)
	T_52 (in signature of __do_global_dtors_aux : void)
// Type Variables ////////////
globals_t: (in globals : (ptr64 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr64 Eq_1)
  OrigDataType: (ptr64 (struct "Globals"))
T_2: (in r6 : word64)
  Class: Eq_2
  DataType: word64
  OrigDataType: word64
T_3: (in r7 : word64)
  Class: Eq_3
  DataType: word64
  OrigDataType: word64
T_4: (in r8 : word64)
  Class: Eq_4
  DataType: word64
  OrigDataType: word64
T_5: (in r9 : word64)
  Class: Eq_5
  DataType: word64
  OrigDataType: word64
T_6: (in r10 : word64)
  Class: Eq_6
  DataType: word64
  OrigDataType: word64
T_7: (in r11 : word64)
  Class: Eq_7
  DataType: word64
  OrigDataType: word64
T_8: (in r13 : word64)
  Class: Eq_8
  DataType: word64
  OrigDataType: word64
T_9: (in r1_37 : (ptr64 code))
  Class: Eq_9
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_10: (in 0000000000001FE8 : ptr64)
  Class: Eq_10
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_11 t0000)))
T_11: (in Mem34[0x0000000000001FE8<p64>:word64] : word64)
  Class: Eq_9
  DataType: (ptr64 code)
  OrigDataType: word64
T_12: (in 0<64> : word64)
  Class: Eq_9
  DataType: (ptr64 code)
  OrigDataType: word64
T_13: (in r1_37 == null : bool)
  Class: Eq_13
  DataType: bool
  OrigDataType: bool
T_14: (in frame_dummy : ptr64)
  Class: Eq_14
  DataType: (ptr64 Eq_14)
  OrigDataType: (ptr64 (fn T_18 (T_17)))
T_15: (in signature of frame_dummy : void)
  Class: Eq_14
  DataType: (ptr64 Eq_14)
  OrigDataType: 
T_16: (in r14 : (ptr64 code))
  Class: Eq_16
  DataType: (ptr64 code)
  OrigDataType: word64
T_17: (in 00000000000004AE : ptr64)
  Class: Eq_16
  DataType: (ptr64 code)
  OrigDataType: ptr64
T_18: (in frame_dummy(&g_t04AE) : void)
  Class: Eq_18
  DataType: void
  OrigDataType: void
T_19: (in __do_global_ctors_aux : ptr64)
  Class: Eq_19
  DataType: (ptr64 Eq_19)
  OrigDataType: (ptr64 (fn T_21 ()))
T_20: (in signature of __do_global_ctors_aux : void)
  Class: Eq_19
  DataType: (ptr64 Eq_19)
  OrigDataType: 
T_21: (in __do_global_ctors_aux() : void)
  Class: Eq_21
  DataType: void
  OrigDataType: void
T_22: (in r1_5 : (ptr64 code))
  Class: Eq_22
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_23: (in 0000000000002000 : ptr64)
  Class: Eq_23
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_24 t0000)))
T_24: (in Mem0[0x0000000000002000<p64>:word64] : word64)
  Class: Eq_22
  DataType: (ptr64 code)
  OrigDataType: word64
T_25: (in r1_5 : (ptr64 code))
  Class: Eq_25
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_26: (in 0000000000002008 : ptr64)
  Class: Eq_26
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_27 t0000)))
T_27: (in Mem0[0x0000000000002008<p64>:word64] : word64)
  Class: Eq_25
  DataType: (ptr64 code)
  OrigDataType: word64
T_28: (in r14 : (ptr64 code))
  Class: Eq_16
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_29: (in r1_5 : Eq_29)
  Class: Eq_29
  DataType: Eq_29
  OrigDataType: (union (int64 u0) (uint64 u1))
T_30: (in 0000000000002020 : ptr64)
  Class: Eq_30
  DataType: int64
  OrigDataType: (union (int64 u0) (ptr64 u1))
T_31: (in 0000000000002020 : ptr64)
  Class: Eq_31
  DataType: int64
  OrigDataType: (union (int64 u1) (ptr64 u0))
T_32: (in 0x2020<u64> - 0x2020<u64> : word64)
  Class: Eq_29
  DataType: Eq_29
  OrigDataType: int64
T_33: (in 63<i32> : int32)
  Class: Eq_33
  DataType: int32
  OrigDataType: int32
T_34: (in r1_5 >> 63<i32> : word64)
  Class: Eq_34
  DataType: Eq_34
  OrigDataType: (union (int64 u1) (uint64 u0))
T_35: (in 3<i32> : int32)
  Class: Eq_35
  DataType: int32
  OrigDataType: int32
T_36: (in r1_5 >> 3<i32> : word64)
  Class: Eq_36
  DataType: Eq_36
  OrigDataType: (union (int64 u1) (uint64 u0))
T_37: (in (r1_5 >>u 63<i32>) + (r1_5 >> 3<i32>) : word64)
  Class: Eq_37
  DataType: Eq_37
  OrigDataType: (union (int64 u1) (uint64 u0))
T_38: (in 1<i32> : int32)
  Class: Eq_38
  DataType: int32
  OrigDataType: int32
T_39: (in (r1_5 >>u 63<i32>) + (r1_5 >> 3<i32>) >> 1<i32> : word64)
  Class: Eq_39
  DataType: int64
  OrigDataType: int64
T_40: (in 0<64> : word64)
  Class: Eq_39
  DataType: int64
  OrigDataType: word64
T_41: (in (r1_5 >>u 63<i32>) + (r1_5 >> 3<i32>) >> 1<i32> != 0<64> : bool)
  Class: Eq_41
  DataType: bool
  OrigDataType: bool
T_42: (in CC : byte)
  Class: Eq_42
  DataType: Eq_42
  OrigDataType: (union (bool u1) (byte u0))
T_43: (in register_tm_clones : ptr64)
  Class: Eq_43
  DataType: (ptr64 Eq_43)
  OrigDataType: (ptr64 (fn T_45 (T_16)))
T_44: (in signature of register_tm_clones : void)
  Class: Eq_43
  DataType: (ptr64 Eq_43)
  OrigDataType: 
T_45: (in register_tm_clones(r14) : void)
  Class: Eq_45
  DataType: void
  OrigDataType: void
T_46: (in call_frame_dummy : ptr64)
  Class: Eq_46
  DataType: (ptr64 Eq_46)
  OrigDataType: (ptr64 (fn T_48 ()))
T_47: (in signature of call_frame_dummy : void)
  Class: Eq_46
  DataType: (ptr64 Eq_46)
  OrigDataType: 
T_48: (in call_frame_dummy() : void)
  Class: Eq_48
  DataType: void
  OrigDataType: void
T_49: (in call_frame_dummy : ptr64)
  Class: Eq_46
  DataType: (ptr64 Eq_46)
  OrigDataType: (ptr64 (fn T_50 ()))
T_50: (in call_frame_dummy() : void)
  Class: Eq_48
  DataType: void
  OrigDataType: void
T_51: (in __do_global_dtors_aux : ptr64)
  Class: Eq_51
  DataType: (ptr64 Eq_51)
  OrigDataType: (ptr64 (fn T_53 ()))
T_52: (in signature of __do_global_dtors_aux : void)
  Class: Eq_51
  DataType: (ptr64 Eq_51)
  OrigDataType: 
T_53: (in __do_global_dtors_aux() : void)
  Class: Eq_53
  DataType: void
  OrigDataType: void
*/
typedef struct Globals {
	<anonymous> t04AE;	// 4AE
	<anonymous> t04F2;	// 4F2
	<anonymous> t0512;	// 512
	<anonymous> * ptr1FE8;	// 1FE8
	<anonymous> * ptr2000;	// 2000
	<anonymous> * ptr2008;	// 2008
} Eq_1;

typedef void (Eq_14)(code *);

typedef void (Eq_19)();

typedef union Eq_29 {
	int64 u0;
	uint64 u1;
} Eq_29;

typedef union Eq_30 {
	int64 u0;
	ptr64 u1;
} Eq_30;

typedef union Eq_31 {
	int64 u0;
	ptr64 u1;
} Eq_31;

typedef union Eq_34 {
	int64 u0;
	uint64 u1;
} Eq_34;

typedef union Eq_36 {
	int64 u0;
	uint64 u1;
} Eq_36;

typedef union Eq_37 {
	int64 u0;
	uint64 u1;
} Eq_37;

typedef union Eq_42 {
	bool u0;
	byte u1;
} Eq_42;

typedef void (Eq_43)(code *);

typedef void (Eq_46)();

typedef void (Eq_51)();

