// hexdump-O2_plt.c
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O2.h"

<anonymous> g_t0500 = <code>;
// 0000000000000520: void fn0000000000000520()
// Called from:
//      main
void fn0000000000000520()
{
	g_ptr11000();
}

// 0000000000000530: void fn0000000000000530()
// Called from:
//      __do_global_dtors_aux
void fn0000000000000530()
{
	g_ptr11008();
}

// 0000000000000550: void fn0000000000000550()
// Called from:
//      main
void fn0000000000000550()
{
	g_ptr11018();
}

