// hexdump-O0.h
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (FFFFFFFF code tFFFFFFFF) (7F4 code t07F4) (1FEF8 int32 dw1FEF8) (1FEFC (ptr32 code) ptr1FEFC) (1FF00 int32 dw1FF00) (1FF04 (ptr32 code) ptr1FF04) (1FF08 (ptr32 byte) ptr1FF08) (1FF0C word32 dw1FF0C) (1FF14 int32 dw1FF14) (1FF18 (ptr32 (arr (ptr32 code))) ptr1FF18) (1FF1C (ptr32 int32) ptr1FF1C) (1FF24 (ptr32 Eq_137) ptr1FF24) (1FFF0 word32 dw1FFF0) (1FFF4 (struct "Eq_16" (10 (ptr32 code) ptr0010)) t1FFF4))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_7: (fn void (word32))
	T_7 (in frame_dummy : ptr32)
	T_8 (in signature of frame_dummy : void)
Eq_11: (fn void ())
	T_11 (in __do_global_ctors_aux : ptr32)
	T_12 (in signature of __do_global_ctors_aux : void)
Eq_14: (fn void ((ptr32 Eq_16)))
	T_14 (in fn000007C0 : ptr32)
	T_15 (in signature of fn000007C0 : void)
Eq_16: (struct "Eq_16" (10 (ptr32 code) ptr0010))
	T_16 (in r30 : (ptr32 Eq_16))
	T_17 (in 0001FFF4 : ptr32)
Eq_80: (fn void ((ptr32 Eq_82)))
	T_80 (in fn000007B0 : ptr32)
	T_81 (in signature of fn000007B0 : void)
Eq_82: (struct "Eq_82" (FFFF8108 (ptr32 code) ptrFFFF8108))
	T_82 (in r30 : (ptr32 Eq_82))
	T_83 (in 00027EF8 : ptr32)
Eq_85: (fn void ())
	T_85 (in deregister_tm_clones : ptr32)
	T_86 (in signature of deregister_tm_clones : void)
Eq_108: (fn void (word32))
	T_108 (in register_tm_clones : ptr32)
	T_109 (in signature of register_tm_clones : void)
Eq_123: (struct "Eq_123" (10 byte b0010))
	T_123 (in fp + 0xFFFFFF58<32> + (r5 + 1<32>) : word32)
Eq_127: (fn void ((ptr32 Eq_129)))
	T_127 (in fn000007D0 : ptr32)
	T_128 (in signature of fn000007D0 : void)
Eq_129: (struct "Eq_129" (FFFF80E8 (ptr32 code) ptrFFFF80E8))
	T_129 (in r30 : (ptr32 Eq_129))
	T_130 (in 00027F20 : ptr32)
Eq_132: (fn void ((ptr32 Eq_134)))
	T_132 (in fn000007E0 : ptr32)
	T_133 (in signature of fn000007E0 : void)
Eq_134: (struct "Eq_134" (FFFF80EC (ptr32 code) ptrFFFF80EC))
	T_134 (in r30 : (ptr32 Eq_134))
	T_135 (in 00027F20 : ptr32)
Eq_137: (struct "Eq_137" (FFFFFFFC (ptr32 code) ptrFFFFFFFC))
	T_137 (in r31_16 : (ptr32 Eq_137))
	T_139 (in Mem13[0x0001FF24<p32>:word32] : word32)
Eq_173: (fn void ())
	T_173 (in __do_global_dtors_aux : ptr32)
	T_174 (in signature of __do_global_dtors_aux : void)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in xer : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in 0001FFF0 : ptr32)
  Class: Eq_3
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_4 t0000)))
T_4: (in Mem9[0x0001FFF0<p32>:word32] : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_5: (in 0<32> : word32)
  Class: Eq_4
  DataType: word32
  OrigDataType: word32
T_6: (in g_dw1FFF0 == 0<32> : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_7: (in frame_dummy : ptr32)
  Class: Eq_7
  DataType: (ptr32 Eq_7)
  OrigDataType: (ptr32 (fn T_10 (T_2)))
T_8: (in signature of frame_dummy : void)
  Class: Eq_7
  DataType: (ptr32 Eq_7)
  OrigDataType: 
T_9: (in xer : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_10: (in frame_dummy(xer) : void)
  Class: Eq_10
  DataType: void
  OrigDataType: void
T_11: (in __do_global_ctors_aux : ptr32)
  Class: Eq_11
  DataType: (ptr32 Eq_11)
  OrigDataType: (ptr32 (fn T_13 ()))
T_12: (in signature of __do_global_ctors_aux : void)
  Class: Eq_11
  DataType: (ptr32 Eq_11)
  OrigDataType: 
T_13: (in __do_global_ctors_aux() : void)
  Class: Eq_13
  DataType: void
  OrigDataType: void
T_14: (in fn000007C0 : ptr32)
  Class: Eq_14
  DataType: (ptr32 Eq_14)
  OrigDataType: (ptr32 (fn T_18 (T_17)))
T_15: (in signature of fn000007C0 : void)
  Class: Eq_14
  DataType: (ptr32 Eq_14)
  OrigDataType: 
T_16: (in r30 : (ptr32 Eq_16))
  Class: Eq_16
  DataType: (ptr32 Eq_16)
  OrigDataType: (ptr32 (struct (10 T_164 t0010)))
T_17: (in 0001FFF4 : ptr32)
  Class: Eq_16
  DataType: (ptr32 Eq_16)
  OrigDataType: ptr32
T_18: (in fn000007C0(&g_t1FFF4) : void)
  Class: Eq_18
  DataType: void
  OrigDataType: void
T_19: (in 0001FF00 : ptr32)
  Class: Eq_19
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_20 t0000)))
T_20: (in Mem12[0x0001FF00<p32>:word32] : word32)
  Class: Eq_20
  DataType: int32
  OrigDataType: word32
T_21: (in 0001FEF8 : ptr32)
  Class: Eq_21
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_22 t0000)))
T_22: (in Mem12[0x0001FEF8<p32>:word32] : word32)
  Class: Eq_20
  DataType: int32
  OrigDataType: word32
T_23: (in g_dw1FF00 == g_dw1FEF8 : bool)
  Class: Eq_23
  DataType: bool
  OrigDataType: bool
T_24: (in r9_17 : (ptr32 code))
  Class: Eq_24
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_25: (in 0001FEFC : ptr32)
  Class: Eq_25
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_26 t0000)))
T_26: (in Mem12[0x0001FEFC<p32>:word32] : word32)
  Class: Eq_24
  DataType: (ptr32 code)
  OrigDataType: word32
T_27: (in 0<32> : word32)
  Class: Eq_24
  DataType: (ptr32 code)
  OrigDataType: word32
T_28: (in r9_17 == null : bool)
  Class: Eq_28
  DataType: bool
  OrigDataType: bool
T_29: (in xer : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_30: (in 0001FF00 : ptr32)
  Class: Eq_30
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_31 t0000)))
T_31: (in Mem12[0x0001FF00<p32>:word32] : word32)
  Class: Eq_20
  DataType: int32
  OrigDataType: int32
T_32: (in 0001FEF8 : ptr32)
  Class: Eq_32
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_33 t0000)))
T_33: (in Mem12[0x0001FEF8<p32>:word32] : word32)
  Class: Eq_20
  DataType: int32
  OrigDataType: int32
T_34: (in g_dw1FF00 - g_dw1FEF8 : word32)
  Class: Eq_34
  DataType: int32
  OrigDataType: int32
T_35: (in 3<32> : word32)
  Class: Eq_35
  DataType: word32
  OrigDataType: word32
T_36: (in g_dw1FF00 - g_dw1FEF8 >> 3<32> : word32)
  Class: Eq_36
  DataType: int32
  OrigDataType: int32
T_37: (in (g_dw1FF00 - g_dw1FEF8 >> 3<32>) + xer : word32)
  Class: Eq_37
  DataType: int32
  OrigDataType: int32
T_38: (in 0<32> : word32)
  Class: Eq_37
  DataType: int32
  OrigDataType: word32
T_39: (in (g_dw1FF00 - g_dw1FEF8 >> 3<32>) + xer == 0<32> : bool)
  Class: Eq_39
  DataType: bool
  OrigDataType: bool
T_40: (in r9_23 : (ptr32 code))
  Class: Eq_40
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_41: (in 0001FF04 : ptr32)
  Class: Eq_41
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_42 t0000)))
T_42: (in Mem12[0x0001FF04<p32>:word32] : word32)
  Class: Eq_40
  DataType: (ptr32 code)
  OrigDataType: word32
T_43: (in 0<32> : word32)
  Class: Eq_40
  DataType: (ptr32 code)
  OrigDataType: word32
T_44: (in r9_23 == null : bool)
  Class: Eq_44
  DataType: bool
  OrigDataType: bool
T_45: (in r9_29 : word32)
  Class: Eq_45
  DataType: word32
  OrigDataType: word32
T_46: (in r27_16 : (ptr32 byte))
  Class: Eq_46
  DataType: (ptr32 byte)
  OrigDataType: (ptr32 (struct (0 T_51 t0000)))
T_47: (in 0001FF08 : ptr32)
  Class: Eq_47
  DataType: (ptr32 (ptr32 byte))
  OrigDataType: (ptr32 (struct (0 T_48 t0000)))
T_48: (in Mem13[0x0001FF08<p32>:word32] : word32)
  Class: Eq_46
  DataType: (ptr32 byte)
  OrigDataType: word32
T_49: (in 0<32> : word32)
  Class: Eq_49
  DataType: word32
  OrigDataType: word32
T_50: (in r27_16 + 0<32> : word32)
  Class: Eq_50
  DataType: word32
  OrigDataType: word32
T_51: (in Mem13[r27_16 + 0<32>:byte] : byte)
  Class: Eq_51
  DataType: byte
  OrigDataType: byte
T_52: (in CONVERT(Mem13[r27_16 + 0<32>:byte], byte, word32) : word32)
  Class: Eq_52
  DataType: word32
  OrigDataType: word32
T_53: (in 0<32> : word32)
  Class: Eq_52
  DataType: word32
  OrigDataType: word32
T_54: (in (word32) *r27_16 != 0<32> : bool)
  Class: Eq_54
  DataType: bool
  OrigDataType: bool
T_55: (in 0001FF0C : ptr32)
  Class: Eq_55
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_56 t0000)))
T_56: (in Mem13[0x0001FF0C<p32>:word32] : word32)
  Class: Eq_56
  DataType: word32
  OrigDataType: word32
T_57: (in 0<32> : word32)
  Class: Eq_56
  DataType: word32
  OrigDataType: word32
T_58: (in g_dw1FF0C == 0<32> : bool)
  Class: Eq_58
  DataType: bool
  OrigDataType: bool
T_59: (in r31_35 : (ptr32 int32))
  Class: Eq_59
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_65 t0000)))
T_60: (in 0001FF1C : ptr32)
  Class: Eq_60
  DataType: (ptr32 (ptr32 int32))
  OrigDataType: (ptr32 (struct (0 T_61 t0000)))
T_61: (in Mem25[0x0001FF1C<p32>:word32] : word32)
  Class: Eq_59
  DataType: (ptr32 int32)
  OrigDataType: word32
T_62: (in r28_36 : (arr (ptr32 code)))
  Class: Eq_62
  DataType: (ptr32 (arr (ptr32 code)))
  OrigDataType: (ptr32 (struct (0 (arr T_176) a0000)))
T_63: (in 0001FF18 : ptr32)
  Class: Eq_63
  DataType: (ptr32 (ptr32 (arr (ptr32 code))))
  OrigDataType: (ptr32 (struct (0 T_64 t0000)))
T_64: (in Mem25[0x0001FF18<p32>:word32] : word32)
  Class: Eq_62
  DataType: (ptr32 (arr (ptr32 code)))
  OrigDataType: word32
T_65: (in r9_39 : int32)
  Class: Eq_65
  DataType: int32
  OrigDataType: int32
T_66: (in 0<32> : word32)
  Class: Eq_66
  DataType: word32
  OrigDataType: word32
T_67: (in r31_35 + 0<32> : word32)
  Class: Eq_67
  DataType: word32
  OrigDataType: word32
T_68: (in Mem25[r31_35 + 0<32>:word32] : word32)
  Class: Eq_65
  DataType: int32
  OrigDataType: word32
T_69: (in r29_40 : int32)
  Class: Eq_65
  DataType: int32
  OrigDataType: int32
T_70: (in 0001FF14 : ptr32)
  Class: Eq_70
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_71 t0000)))
T_71: (in Mem25[0x0001FF14<p32>:word32] : word32)
  Class: Eq_71
  DataType: int32
  OrigDataType: int32
T_72: (in 0001FF18 : ptr32)
  Class: Eq_72
  DataType: (ptr32 (ptr32 (arr (ptr32 code))))
  OrigDataType: (ptr32 (struct (0 T_73 t0000)))
T_73: (in Mem25[0x0001FF18<p32>:word32] : word32)
  Class: Eq_62
  DataType: (ptr32 (arr (ptr32 code)))
  OrigDataType: int32
T_74: (in g_dw1FF14 - g_ptr1FF18 : word32)
  Class: Eq_74
  DataType: int32
  OrigDataType: int32
T_75: (in 2<32> : word32)
  Class: Eq_75
  DataType: word32
  OrigDataType: word32
T_76: (in g_dw1FF14 - g_ptr1FF18 >> 2<32> : word32)
  Class: Eq_76
  DataType: int32
  OrigDataType: int32
T_77: (in 0xFFFFFFFF<32> : word32)
  Class: Eq_77
  DataType: word32
  OrigDataType: word32
T_78: (in (g_dw1FF14 - g_ptr1FF18 >> 2<32>) + 0xFFFFFFFF<32> : word32)
  Class: Eq_65
  DataType: int32
  OrigDataType: int32
T_79: (in r9_39 >= r29_40 : bool)
  Class: Eq_79
  DataType: bool
  OrigDataType: bool
T_80: (in fn000007B0 : ptr32)
  Class: Eq_80
  DataType: (ptr32 Eq_80)
  OrigDataType: (ptr32 (fn T_84 (T_83)))
T_81: (in signature of fn000007B0 : void)
  Class: Eq_80
  DataType: (ptr32 Eq_80)
  OrigDataType: 
T_82: (in r30 : (ptr32 Eq_82))
  Class: Eq_82
  DataType: (ptr32 Eq_82)
  OrigDataType: (ptr32 (struct (FFFF8108 T_160 tFFFF8108)))
T_83: (in 00027EF8 : ptr32)
  Class: Eq_82
  DataType: (ptr32 Eq_82)
  OrigDataType: ptr32
T_84: (in fn000007B0((struct Eq_82 *) 0x27EF8<u32>) : void)
  Class: Eq_84
  DataType: void
  OrigDataType: void
T_85: (in deregister_tm_clones : ptr32)
  Class: Eq_85
  DataType: (ptr32 Eq_85)
  OrigDataType: (ptr32 (fn T_87 ()))
T_86: (in signature of deregister_tm_clones : void)
  Class: Eq_85
  DataType: (ptr32 Eq_85)
  OrigDataType: 
T_87: (in deregister_tm_clones() : void)
  Class: Eq_87
  DataType: void
  OrigDataType: void
T_88: (in 1<8> : byte)
  Class: Eq_51
  DataType: byte
  OrigDataType: byte
T_89: (in 0<32> : word32)
  Class: Eq_89
  DataType: word32
  OrigDataType: word32
T_90: (in r27_16 + 0<32> : word32)
  Class: Eq_90
  DataType: (ptr32 byte)
  OrigDataType: (ptr32 byte)
T_91: (in Mem76[r27_16 + 0<32>:byte] : byte)
  Class: Eq_51
  DataType: byte
  OrigDataType: byte
T_92: (in r9_43 : int32)
  Class: Eq_65
  DataType: int32
  OrigDataType: int32
T_93: (in 1<32> : word32)
  Class: Eq_93
  DataType: word32
  OrigDataType: word32
T_94: (in r9_39 + 1<32> : word32)
  Class: Eq_65
  DataType: int32
  OrigDataType: int32
T_95: (in 0<32> : word32)
  Class: Eq_95
  DataType: word32
  OrigDataType: word32
T_96: (in r31_35 + 0<32> : word32)
  Class: Eq_96
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_97: (in Mem46[r31_35 + 0<32>:word32] : word32)
  Class: Eq_65
  DataType: int32
  OrigDataType: word32
T_98: (in r9_48 : (ptr32 code))
  Class: Eq_98
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_99: (in 4<32> : ui32)
  Class: Eq_99
  DataType: ui32
  OrigDataType: ui32
T_100: (in r9_43 * 4<32> : word32)
  Class: Eq_100
  DataType: ui32
  OrigDataType: ui32
T_101: (in r28_36[r9_43 * 4<32>] : word32)
  Class: Eq_98
  DataType: (ptr32 code)
  OrigDataType: word32
T_102: (in r3_57 : word32)
  Class: Eq_102
  DataType: word32
  OrigDataType: word32
T_103: (in r11_59 : word32)
  Class: Eq_103
  DataType: word32
  OrigDataType: word32
T_104: (in 0<32> : word32)
  Class: Eq_104
  DataType: word32
  OrigDataType: word32
T_105: (in r31_35 + 0<32> : word32)
  Class: Eq_105
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 int32)
T_106: (in Mem46[r31_35 + 0<32>:word32] : word32)
  Class: Eq_65
  DataType: int32
  OrigDataType: int32
T_107: (in r9_39 < r29_40 : bool)
  Class: Eq_107
  DataType: bool
  OrigDataType: bool
T_108: (in register_tm_clones : ptr32)
  Class: Eq_108
  DataType: (ptr32 Eq_108)
  OrigDataType: (ptr32 (fn T_110 (T_9)))
T_109: (in signature of register_tm_clones : void)
  Class: Eq_108
  DataType: (ptr32 Eq_108)
  OrigDataType: 
T_110: (in register_tm_clones(xer) : void)
  Class: Eq_110
  DataType: void
  OrigDataType: void
T_111: (in r5 : int32)
  Class: Eq_111
  DataType: int32
  OrigDataType: int32
T_112: (in 0x41<8> : byte)
  Class: Eq_112
  DataType: byte
  OrigDataType: byte
T_113: (in fp : ptr32)
  Class: Eq_113
  DataType: ptr32
  OrigDataType: ptr32
T_114: (in 0xFFFFFF68<32> : word32)
  Class: Eq_114
  DataType: int32
  OrigDataType: int32
T_115: (in fp + 0xFFFFFF68<32> : word32)
  Class: Eq_115
  DataType: ptr32
  OrigDataType: ptr32
T_116: (in fp + 0xFFFFFF68<32> + r5 : word32)
  Class: Eq_116
  DataType: (ptr32 byte)
  OrigDataType: (ptr32 (struct (0 T_117 t0000)))
T_117: (in Mem34[fp + 0xFFFFFF68<32> + r5:byte] : byte)
  Class: Eq_112
  DataType: byte
  OrigDataType: byte
T_118: (in 0x20<8> : byte)
  Class: Eq_118
  DataType: byte
  OrigDataType: byte
T_119: (in 0xFFFFFF58<32> : word32)
  Class: Eq_119
  DataType: int32
  OrigDataType: int32
T_120: (in fp + 0xFFFFFF58<32> : word32)
  Class: Eq_120
  DataType: ptr32
  OrigDataType: ptr32
T_121: (in 1<32> : word32)
  Class: Eq_121
  DataType: word32
  OrigDataType: word32
T_122: (in r5 + 1<32> : word32)
  Class: Eq_122
  DataType: int32
  OrigDataType: int32
T_123: (in fp + 0xFFFFFF58<32> + (r5 + 1<32>) : word32)
  Class: Eq_123
  DataType: (ptr32 Eq_123)
  OrigDataType: (ptr32 (struct (10 T_126 t0010)))
T_124: (in 16<i32> : int32)
  Class: Eq_124
  DataType: int32
  OrigDataType: int32
T_125: (in fp + 0xFFFFFF58<32> + (r5 + 1<32>) + 16<i32> : word32)
  Class: Eq_125
  DataType: ptr32
  OrigDataType: ptr32
T_126: (in Mem40[fp + 0xFFFFFF58<32> + (r5 + 1<32>) + 16<i32>:byte] : byte)
  Class: Eq_118
  DataType: byte
  OrigDataType: byte
T_127: (in fn000007D0 : ptr32)
  Class: Eq_127
  DataType: (ptr32 Eq_127)
  OrigDataType: (ptr32 (fn T_131 (T_130)))
T_128: (in signature of fn000007D0 : void)
  Class: Eq_127
  DataType: (ptr32 Eq_127)
  OrigDataType: 
T_129: (in r30 : (ptr32 Eq_129))
  Class: Eq_129
  DataType: (ptr32 Eq_129)
  OrigDataType: (ptr32 (struct (FFFF80E8 T_168 tFFFF80E8)))
T_130: (in 00027F20 : ptr32)
  Class: Eq_129
  DataType: (ptr32 Eq_129)
  OrigDataType: ptr32
T_131: (in fn000007D0((struct Eq_129 *) 0x27F20<u32>) : void)
  Class: Eq_131
  DataType: void
  OrigDataType: void
T_132: (in fn000007E0 : ptr32)
  Class: Eq_132
  DataType: (ptr32 Eq_132)
  OrigDataType: (ptr32 (fn T_136 (T_135)))
T_133: (in signature of fn000007E0 : void)
  Class: Eq_132
  DataType: (ptr32 Eq_132)
  OrigDataType: 
T_134: (in r30 : (ptr32 Eq_134))
  Class: Eq_134
  DataType: (ptr32 Eq_134)
  OrigDataType: (ptr32 (struct (FFFF80EC T_172 tFFFF80EC)))
T_135: (in 00027F20 : ptr32)
  Class: Eq_134
  DataType: (ptr32 Eq_134)
  OrigDataType: ptr32
T_136: (in fn000007E0((struct Eq_134 *) 0x27F20<u32>) : void)
  Class: Eq_136
  DataType: void
  OrigDataType: void
T_137: (in r31_16 : (ptr32 Eq_137))
  Class: Eq_137
  DataType: (ptr32 Eq_137)
  OrigDataType: (ptr32 (struct (FFFFFFFC T_143 tFFFFFFFC)))
T_138: (in 0001FF24 : ptr32)
  Class: Eq_138
  DataType: (ptr32 (ptr32 Eq_137))
  OrigDataType: (ptr32 (struct (0 T_139 t0000)))
T_139: (in Mem13[0x0001FF24<p32>:word32] : word32)
  Class: Eq_137
  DataType: (ptr32 Eq_137)
  OrigDataType: word32
T_140: (in r9_17 : (ptr32 code))
  Class: Eq_140
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_141: (in -4<i32> : int32)
  Class: Eq_141
  DataType: int32
  OrigDataType: int32
T_142: (in r31_16 + -4<i32> : word32)
  Class: Eq_142
  DataType: word32
  OrigDataType: word32
T_143: (in Mem13[r31_16 + -4<i32>:word32] : word32)
  Class: Eq_140
  DataType: (ptr32 code)
  OrigDataType: word32
T_144: (in 0xFFFFFFFF<32> : word32)
  Class: Eq_140
  DataType: (ptr32 code)
  OrigDataType: word32
T_145: (in r9_17 == (<anonymous> *) 0xFFFFFFFF<32> : bool)
  Class: Eq_145
  DataType: bool
  OrigDataType: bool
T_146: (in r31_19 : (ptr32 word32))
  Class: Eq_146
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct 0004 (0 word32 dw0000)))
T_147: (in 0xFFFFFFFC<32> : word32)
  Class: Eq_147
  DataType: int32
  OrigDataType: int32
T_148: (in r31_16 + 0xFFFFFFFC<32> : word32)
  Class: Eq_148
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_149: (in -4<i32> : int32)
  Class: Eq_149
  DataType: int32
  OrigDataType: int32
T_150: (in r31_16 + 0xFFFFFFFC<32> + -4<i32> : word32)
  Class: Eq_146
  DataType: (ptr32 word32)
  OrigDataType: ptr32
T_151: (in 0<i32> : int32)
  Class: Eq_151
  DataType: int32
  OrigDataType: int32
T_152: (in r31_19 + 0<i32> : word32)
  Class: Eq_152
  DataType: ptr32
  OrigDataType: ptr32
T_153: (in Mem13[r31_19 + 0<i32>:word32] : word32)
  Class: Eq_140
  DataType: (ptr32 code)
  OrigDataType: word32
T_154: (in r31_19 + -4<i32> : word32)
  Class: Eq_146
  DataType: (ptr32 word32)
  OrigDataType: ptr32
T_155: (in 0xFFFFFFFF<32> : word32)
  Class: Eq_140
  DataType: (ptr32 code)
  OrigDataType: word32
T_156: (in r9_17 != (<anonymous> *) 0xFFFFFFFF<32> : bool)
  Class: Eq_156
  DataType: bool
  OrigDataType: bool
T_157: (in r11_5 : (ptr32 code))
  Class: Eq_157
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_158: (in -32504<i32> : int32)
  Class: Eq_158
  DataType: int32
  OrigDataType: int32
T_159: (in r30 + -32504<i32> : word32)
  Class: Eq_159
  DataType: word32
  OrigDataType: word32
T_160: (in Mem0[r30 + -32504<i32>:word32] : word32)
  Class: Eq_157
  DataType: (ptr32 code)
  OrigDataType: word32
T_161: (in r11_5 : (ptr32 code))
  Class: Eq_161
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_162: (in 16<i32> : int32)
  Class: Eq_162
  DataType: int32
  OrigDataType: int32
T_163: (in r30 + 16<i32> : word32)
  Class: Eq_163
  DataType: word32
  OrigDataType: word32
T_164: (in Mem0[r30 + 16<i32>:word32] : word32)
  Class: Eq_161
  DataType: (ptr32 code)
  OrigDataType: word32
T_165: (in r11_5 : (ptr32 code))
  Class: Eq_165
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_166: (in -32536<i32> : int32)
  Class: Eq_166
  DataType: int32
  OrigDataType: int32
T_167: (in r30 + -32536<i32> : word32)
  Class: Eq_167
  DataType: word32
  OrigDataType: word32
T_168: (in Mem0[r30 + -32536<i32>:word32] : word32)
  Class: Eq_165
  DataType: (ptr32 code)
  OrigDataType: word32
T_169: (in r11_5 : (ptr32 code))
  Class: Eq_169
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_170: (in -32532<i32> : int32)
  Class: Eq_170
  DataType: int32
  OrigDataType: int32
T_171: (in r30 + -32532<i32> : word32)
  Class: Eq_171
  DataType: word32
  OrigDataType: word32
T_172: (in Mem0[r30 + -32532<i32>:word32] : word32)
  Class: Eq_169
  DataType: (ptr32 code)
  OrigDataType: word32
T_173: (in __do_global_dtors_aux : ptr32)
  Class: Eq_173
  DataType: (ptr32 Eq_173)
  OrigDataType: (ptr32 (fn T_175 ()))
T_174: (in signature of __do_global_dtors_aux : void)
  Class: Eq_173
  DataType: (ptr32 Eq_173)
  OrigDataType: 
T_175: (in __do_global_dtors_aux() : void)
  Class: Eq_175
  DataType: void
  OrigDataType: void
T_176:
  Class: Eq_176
  DataType: (ptr32 code)
  OrigDataType: (struct 0004 (0 T_101 t0000))
*/
typedef struct Eq_16;
struct Globals {
	<anonymous> tFFFFFFFF;	// FFFFFFFF
	<anonymous> t07F4;	// 7F4
	int32 dw1FEF8;	// 1FEF8
	<anonymous> * ptr1FEFC;	// 1FEFC
	int32 dw1FF00;	// 1FF00
	<anonymous> * ptr1FF04;	// 1FF04
	byte * ptr1FF08;	// 1FF08
	word32 dw1FF0C;	// 1FF0C
	int32 dw1FF14;	// 1FF14
	<anonymous> * (* ptr1FF18)[];	// 1FF18
	int32 * ptr1FF1C;	// 1FF1C
	struct Eq_137 * ptr1FF24;	// 1FF24
	word32 dw1FFF0;	// 1FFF0
	struct Eq_16 t1FFF4;	// 1FFF4
} Eq_1;

typedef void (Eq_7)(word32);

typedef void (Eq_11)();

typedef void (Eq_14)(Eq_16 *);

typedef struct Eq_16 {
	<anonymous> * ptr0010;	// 10
} Eq_16;

typedef void (Eq_80)(Eq_82 *);

typedef struct Eq_82 {
	<anonymous> * ptrFFFF8108;	// FFFF8108
} Eq_82;

typedef void (Eq_85)();

typedef void (Eq_108)(word32);

typedef struct Eq_123 {
	byte b0010;	// 10
} Eq_123;

typedef void (Eq_127)(Eq_129 *);

typedef struct Eq_129 {
	<anonymous> * ptrFFFF80E8;	// FFFF80E8
} Eq_129;

typedef void (Eq_132)(Eq_134 *);

typedef struct Eq_134 {
	<anonymous> * ptrFFFF80EC;	// FFFF80EC
} Eq_134;

typedef struct Eq_137 {
	<anonymous> * ptrFFFFFFFC;	// FFFFFFFC
} Eq_137;

typedef void (Eq_173)();

