// hexdump-Os_text.c
// Generated by decompiling hexdump-Os.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-Os.h"

// 000003E0: void main(Register word32 r30, Register word32 r31)
void main(word32 r30, word32 r31)
{
	v5->dw0000 = r30;
	v5->dw0004 = r31;
	fn00000750((struct Eq_n *) 163616);
	fn00000760((struct Eq_n *) 163616);
	_restgpr_n_x();
}

// 00000430: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (g_dw1FF00 != g_dw1FEF8)
	{
		<anonymous> * r9_n = g_ptr1FEFC;
		if (r9_n != null)
			r9_n();
	}
}

// 00000490: void register_tm_clones(Register word32 xer)
// Called from:
//      frame_dummy
void register_tm_clones(word32 xer)
{
	if ((g_dw1FF00 - g_dw1FEF8 >> 0x03) + xer != 0x00)
	{
		<anonymous> * r9_n = g_ptr1FF04;
		if (r9_n != null)
		{
			word32 r9_n;
			r9_n();
		}
	}
}

// 00000500: void __do_global_dtors_aux()
// Called from:
//      _fini
void __do_global_dtors_aux()
{
	byte * r27_n = g_ptr1FF08;
	if ((word32) *r27_n == 0x00)
	{
		if (g_dw1FF0C != 0x00)
			fn00000730((struct Eq_n *) 163576);
		int32 * r31_n = g_ptr1FF1C;
		<anonymous> * r28_n[] = g_ptr1FF18;
		int32 r9_n = *r31_n;
		int32 r29_n = (g_dw1FF14 - g_ptr1FF18 >> 0x02) + ~0x00;
		while (r9_n < r29_n)
		{
			int32 r9_n = r9_n + 0x01;
			*r31_n = r9_n;
			<anonymous> * r9_n = r28_n[r9_n];
			word32 r3_n;
			word32 r11_n;
			r9_n();
			r9_n = *r31_n;
		}
		deregister_tm_clones();
		*r27_n = 0x01;
	}
}

// 000005E0: void call___do_global_dtors_aux()
void call___do_global_dtors_aux()
{
}

// 00000600: void frame_dummy(Register word32 xer)
// Called from:
//      _init
void frame_dummy(word32 xer)
{
	register_tm_clones(xer);
}

// 00000610: void call_frame_dummy()
void call_frame_dummy()
{
}

// 0000062C: void hexdump()
void hexdump()
{
}

// 00000630: void _restgpr_n_x()
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000634: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000638: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 0000063C: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000640: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000644: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000648: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 0000064C: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000650: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000654: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000658: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 0000065C: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000660: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000664: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000668: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 0000066C: void _restgpr_n_x()
// Called from:
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000670: void _restgpr_n_x()
// Called from:
//      main
//      _restgpr_n_x
void _restgpr_n_x()
{
	_restgpr_n_x();
}

// 00000674: void _restgpr_n_x()
// Called from:
//      main
void _restgpr_n_x()
{
}

// 000006A0: void __do_global_ctors_aux()
// Called from:
//      _init
void __do_global_ctors_aux()
{
	struct Eq_n * r31_n = g_ptr1FF24;
	<anonymous> * r9_n = r31_n->ptrFFFFFFFC;
	if (r9_n != (<anonymous> *) ~0x00)
	{
		word32 * r31_n = (char *) &r31_n->ptrFFFFFFFC - 4;
		do
		{
			r9_n();
			r9_n = *r31_n;
			r31_n += -1;
		} while (r9_n != (<anonymous> *) ~0x00);
	}
}

// 00000710: void call___do_global_ctors_aux()
void call___do_global_ctors_aux()
{
}

// 00000730: void fn00000730(Register (ptr32 Eq_n) r30)
// Called from:
//      __do_global_dtors_aux
void fn00000730(struct Eq_n * r30)
{
	<anonymous> * r11_n = r30->ptrFFFF8108;
	r11_n();
}

// 00000740: void fn00000740(Register (ptr32 Eq_n) r30)
// Called from:
//      _init
void fn00000740(struct Eq_n * r30)
{
	<anonymous> * r11_n = r30->ptr0010;
	r11_n();
}

// 00000750: void fn00000750(Register (ptr32 Eq_n) r30)
// Called from:
//      main
void fn00000750(struct Eq_n * r30)
{
	<anonymous> * r11_n = r30->ptrFFFF80E8;
	r11_n();
}

// 00000760: void fn00000760(Register (ptr32 Eq_n) r30)
// Called from:
//      main
void fn00000760(struct Eq_n * r30)
{
	<anonymous> * r11_n = r30->ptrFFFF80EC;
	r11_n();
}

<anonymous> g_t0774 = <code>;
