// hexdump-O2_text.c
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O2.h"

// 000003E0: void main()
void main()
{
	fn00000710((struct Eq_n *) 163616);
	fn00000720((struct Eq_n *) 163616);
}

// 00000450: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (g_dw1FF00 != g_dw1FEF8)
	{
		<anonymous> * r9_n = g_ptr1FEFC;
		if (r9_n != null)
			r9_n();
	}
}

// 000004B0: void register_tm_clones(Register word32 xer)
// Called from:
//      frame_dummy
void register_tm_clones(word32 xer)
{
	if ((g_dw1FF00 - g_dw1FEF8 >> 0x03) + xer != 0x00)
	{
		<anonymous> * r9_n = g_ptr1FF04;
		if (r9_n != null)
		{
			word32 r9_n;
			r9_n();
		}
	}
}

// 00000520: void __do_global_dtors_aux()
// Called from:
//      _fini
void __do_global_dtors_aux()
{
	byte * r27_n = g_ptr1FF08;
	if ((word32) *r27_n == 0x00)
	{
		if (g_dw1FF0C != 0x00)
			fn000006F0((struct Eq_n *) 163576);
		int32 * r31_n = g_ptr1FF1C;
		<anonymous> * r28_n[] = g_ptr1FF18;
		int32 r9_n = *r31_n;
		int32 r29_n = (g_dw1FF14 - g_ptr1FF18 >> 0x02) + ~0x00;
		while (r9_n < r29_n)
		{
			int32 r9_n = r9_n + 0x01;
			*r31_n = r9_n;
			<anonymous> * r9_n = r28_n[r9_n];
			word32 r3_n;
			word32 r11_n;
			r9_n();
			r9_n = *r31_n;
		}
		deregister_tm_clones();
		*r27_n = 0x01;
	}
}

// 00000600: void call___do_global_dtors_aux()
void call___do_global_dtors_aux()
{
}

// 00000620: void frame_dummy(Register word32 xer)
// Called from:
//      _init
void frame_dummy(word32 xer)
{
	register_tm_clones(xer);
}

// 00000630: void call_frame_dummy()
void call_frame_dummy()
{
}

// 00000650: void hexdump()
void hexdump()
{
}

// 00000660: void __do_global_ctors_aux()
// Called from:
//      _init
void __do_global_ctors_aux()
{
	struct Eq_n * r31_n = g_ptr1FF24;
	<anonymous> * r9_n = r31_n->ptrFFFFFFFC;
	if (r9_n != (<anonymous> *) ~0x00)
	{
		word32 * r31_n = (char *) &r31_n->ptrFFFFFFFC - 4;
		do
		{
			r9_n();
			r9_n = *r31_n;
			r31_n += -1;
		} while (r9_n != (<anonymous> *) ~0x00);
	}
}

// 000006D0: void call___do_global_ctors_aux()
void call___do_global_ctors_aux()
{
}

// 000006F0: void fn000006F0(Register (ptr32 Eq_n) r30)
// Called from:
//      __do_global_dtors_aux
void fn000006F0(struct Eq_n * r30)
{
	<anonymous> * r11_n = r30->ptrFFFF8108;
	r11_n();
}

// 00000700: void fn00000700(Register (ptr32 Eq_n) r30)
// Called from:
//      _init
void fn00000700(struct Eq_n * r30)
{
	<anonymous> * r11_n = r30->ptr0010;
	r11_n();
}

// 00000710: void fn00000710(Register (ptr32 Eq_n) r30)
// Called from:
//      main
void fn00000710(struct Eq_n * r30)
{
	<anonymous> * r11_n = r30->ptrFFFF80E8;
	r11_n();
}

// 00000720: void fn00000720(Register (ptr32 Eq_n) r30)
// Called from:
//      main
void fn00000720(struct Eq_n * r30)
{
	<anonymous> * r11_n = r30->ptrFFFF80EC;
	r11_n();
}

<anonymous> g_t0734 = <code>;
