// hexdump-O0_plt.c
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O0.h"

// 00000000001021E0: void fn00000000001021E0()
// Called from:
//      main
void fn00000000001021E0()
{
}

