// hexdump-O0_plt.c
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O0.h"

<anonymous> g_t02FC = <code>;
// 00000310: void fn00000310()
// Called from:
//      __do_global_dtors_aux
void fn00000310()
{
	g_ptr1100C();
}

// 00000328: void fn00000328()
// Called from:
//      main
void fn00000328()
{
	g_ptr11014();
}

// 00000334: void fn00000334()
// Called from:
//      main
void fn00000334()
{
	g_ptr11018();
}

