// hexdump-O2_plt_got.c
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O2.h"

// 0000000000001050: void fn0000000000001050()
// Called from:
//      main
void fn0000000000001050()
{
	g_ptr3FE8();
}

// 0000000000001058: void fn0000000000001058()
// Called from:
//      __do_global_dtors_aux
void fn0000000000001058()
{
	g_t3FF0();
}

