// hexdump-O2_got.c
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O2.h"

<anonymous> * g_ptr1100C = &g_t02FC;
<anonymous> * g_ptr11010 = &g_t02FC;
<anonymous> * g_ptr11014 = &g_t02FC;
<anonymous> * g_ptr11018 = &g_t07B4;
