// hexdump-O2_text.c
// Generated by decompiling hexdump-O2.so
// using Reko decompiler version 0.9.3.0.

#include "hexdump-O2.h"

// 00000340: void main()
void main()
{
	fn00000328();
	fn00000334();
}

// 00000394: void call_weak_fn(Register (ptr32 code) lr)
// Called from:
//      _init
void call_weak_fn(<anonymous> * lr)
{
	if (0x03A4 + g_dw03B0 + g_dw03B4 != 0x00)
		fn0000031C();
	else
		lr();
}

int32 g_dw03B0 = 68700;
int32 g_dw03B4 = 36;
// 000003B8: void deregister_tm_clones(Register (ptr32 code) lr)
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones(<anonymous> * lr)
{
	ptr32 r3_n = 0x03D8 + g_dw03F4;
	if (0x03CC + g_dw03F0 != 0x03C8 + g_dw03EC)
	{
		<anonymous> * r3_n = r3_n + g_dw03F8;
		if (r3_n != null)
		{
			word32 lr_n;
			r3_n();
		}
		else
			lr();
	}
	else
		lr();
}

int32 g_dw03EC = 68716;
int32 g_dw03F0 = 68712;
int32 g_dw03F4 = 68648;
int32 g_dw03F8 = 32;
// 000003FC: void register_tm_clones(Register (ptr32 code) lr)
// Called from:
//      frame_dummy
void register_tm_clones(<anonymous> * lr)
{
	Eq_n r1_n = (word32) g_t0440 + 1040 - ((word32) g_t043C + 0x040C);
	ptr32 r3_n = 0x0428 + g_dw0444;
	if ((r1_n >>u 31) + (r1_n >> 2) >> 1 != 0x00)
	{
		<anonymous> * r3_n = r3_n + g_dw0448;
		if (r3_n != null)
		{
			word32 lr_n;
			r3_n();
		}
		else
			lr();
	}
	else
		lr();
}

Eq_n g_t043C = 
	{
		68648
	};
Eq_n g_t0440 = 
	{
		68644
	};
int32 g_dw0444 = 68568;
int32 g_dw0448 = 44;
// 0000044C: void __do_global_dtors_aux(Register word32 r4, Register (ptr32 code) lr)
void __do_global_dtors_aux(word32 r4, <anonymous> * lr)
{
	ptr32 r2_n = 0x0464 + g_dw04A4;
	if ((word32) (1116 + g_dw04A0) == 0x00)
	{
		if (r2_n + g_dw04A8 != 0x00)
			fn00000310();
		deregister_tm_clones(lr);
		1180 + g_dw04B0 = (byte *) 0x01;
	}
	else
	{
		word32 ip_n;
		lr();
	}
}

int32 g_dw04A0 = 68568;
int32 g_dw04A4 = 68508;
int32 g_dw04A8 = 28;
int32 g_dw04B0 = 68504;
// 000004B4: void frame_dummy(Register (ptr32 code) lr)
void frame_dummy(<anonymous> * lr)
{
	register_tm_clones(lr);
}

// 000004B8: void hexdump()
void hexdump()
{
}

