// hexdump-O0.h
// Generated by decompiling hexdump-O0.so
// using Reko decompiler version 0.9.3.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (3F08 word32 dw3F08) (3FD8 word32 dw3FD8) (3FE0 (ptr64 code) ptr3FE0) (3FE8 (ptr64 code) ptr3FE8) (3FF0 Eq_16 t3FF0) (3FF8 word32 dw3FF8) (4024 byte b4024) (4028 ui32 dw4028))
	globals_t (in globals : (ptr64 (struct "Globals")))
Eq_7: (fn void ())
	T_7 (in frame_dummy : ptr64)
	T_8 (in signature of frame_dummy : void)
Eq_10: (fn void ())
	T_10 (in __do_global_ctors_aux : ptr64)
	T_11 (in signature of __do_global_ctors_aux : void)
Eq_16: (union "Eq_16" (word32 u0) ((ptr64 code) u1))
	T_16 (in Mem0[0x0000000000003FF0<p64>:word64] : word64)
	T_71 (in Mem9[0x0000000000003FF0<p64>:word32] : word32)
Eq_36: (union "Eq_36" (int64 u0) (ptr64 u1))
	T_36 (in 0000000000004024 : ptr64)
Eq_37: (union "Eq_37" (int64 u0) (ptr64 u1))
	T_37 (in 0000000000004024 : ptr64)
Eq_106: (fn void ())
	T_106 (in fn0000000000001058 : ptr64)
	T_107 (in signature of fn0000000000001058 : void)
Eq_109: (fn void ())
	T_109 (in deregister_tm_clones : ptr64)
	T_110 (in signature of deregister_tm_clones : void)
Eq_134: (fn void ())
	T_134 (in register_tm_clones : ptr64)
	T_135 (in signature of register_tm_clones : void)
Eq_148: (struct "Eq_148" (FFFFFF5C word32 dwFFFFFF5C) (FFFFFF60 word32 dwFFFFFF60) (FFFFFF64 word32 dwFFFFFF64) (FFFFFF68 word32 dwFFFFFF68) (FFFFFF6C word32 dwFFFFFF6C) (FFFFFF78 word32 dwFFFFFF78) (FFFFFF7C word32 dwFFFFFF7C) (FFFFFFF0 word32 dwFFFFFFF0) (FFFFFFF4 word32 dwFFFFFFF4) (FFFFFFF8 word32 dwFFFFFFF8) (FFFFFFFC word32 dwFFFFFFFC))
	T_148 (in ebp_15 : (ptr32 Eq_148))
	T_149 (in SLICE(rbp_9, word32, 0) : word32)
Eq_256: (struct "Eq_256" (FFFFFFE8 word32 dwFFFFFFE8) (FFFFFFEC word32 dwFFFFFFEC))
	T_256 (in ebp_19 : (ptr32 Eq_256))
	T_262 (in SLICE(CONVERT(SLICE(fp - 8<i64>, word32, 0), word32, uint64), word32, 0) : word32)
Eq_271: (fn Eq_285 (uint64))
	T_271 (in strlen : ptr64)
	T_272 (in signature of strlen : void)
Eq_285: size_t
	T_285 (in strlen((uint64) (word32) (uint64) *(word32) (uint64) ebp_19->dwFFFFFFE8) : size_t)
Eq_286: (fn void ())
	T_286 (in fn0000000000001050 : ptr64)
	T_287 (in signature of fn0000000000001050 : void)
Eq_300: (struct "Eq_300" (FFFFFFFC word32 dwFFFFFFFC))
	T_300 (in ebx_33 : (ptr32 Eq_300))
	T_301 (in SLICE(rbx_20, word32, 0) : word32)
Eq_312: (fn void ())
	T_312 (in __do_global_dtors_aux : ptr64)
	T_313 (in signature of __do_global_dtors_aux : void)
// Type Variables ////////////
globals_t: (in globals : (ptr64 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr64 Eq_1)
  OrigDataType: (ptr64 (struct "Globals"))
T_2: (in rax_6 : (ptr64 code))
  Class: Eq_2
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_3: (in 0000000000003FE0 : ptr64)
  Class: Eq_3
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_4 t0000)))
T_4: (in Mem0[0x0000000000003FE0<p64>:word64] : word64)
  Class: Eq_2
  DataType: (ptr64 code)
  OrigDataType: word64
T_5: (in 0<64> : word64)
  Class: Eq_2
  DataType: (ptr64 code)
  OrigDataType: word64
T_6: (in rax_6 == null : bool)
  Class: Eq_6
  DataType: bool
  OrigDataType: bool
T_7: (in frame_dummy : ptr64)
  Class: Eq_7
  DataType: (ptr64 Eq_7)
  OrigDataType: (ptr64 (fn T_9 ()))
T_8: (in signature of frame_dummy : void)
  Class: Eq_7
  DataType: (ptr64 Eq_7)
  OrigDataType: 
T_9: (in frame_dummy() : void)
  Class: Eq_9
  DataType: void
  OrigDataType: void
T_10: (in __do_global_ctors_aux : ptr64)
  Class: Eq_10
  DataType: (ptr64 Eq_10)
  OrigDataType: (ptr64 (fn T_12 ()))
T_11: (in signature of __do_global_ctors_aux : void)
  Class: Eq_10
  DataType: (ptr64 Eq_10)
  OrigDataType: 
T_12: (in __do_global_ctors_aux() : void)
  Class: Eq_12
  DataType: void
  OrigDataType: void
T_13: (in 0000000000003FE8 : ptr64)
  Class: Eq_13
  DataType: (ptr64 (ptr64 code))
  OrigDataType: (ptr64 (struct (0 T_14 t0000)))
T_14: (in Mem0[0x0000000000003FE8<p64>:word64] : word64)
  Class: Eq_14
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_15: (in 0000000000003FF0 : ptr64)
  Class: Eq_15
  DataType: (ptr64 Eq_16)
  OrigDataType: (ptr64 (struct (0 T_16 t0000)))
T_16: (in Mem0[0x0000000000003FF0<p64>:word64] : word64)
  Class: Eq_16
  DataType: Eq_16
  OrigDataType: (ptr64 code)
T_17: (in 0000000000004024 : ptr64)
  Class: Eq_17
  DataType: ptr64
  OrigDataType: ptr64
T_18: (in SLICE(0x0000000000004024<p64>, word32, 0) : word32)
  Class: Eq_18
  DataType: word32
  OrigDataType: word32
T_19: (in CONVERT(SLICE(0x0000000000004024<p64>, word32, 0), word32, uint64) : uint64)
  Class: Eq_19
  DataType: uint64
  OrigDataType: uint64
T_20: (in SLICE(CONVERT(SLICE(0x0000000000004024<p64>, word32, 0), word32, uint64), word32, 0) : word32)
  Class: Eq_20
  DataType: word32
  OrigDataType: word32
T_21: (in 0000000000004024 : ptr64)
  Class: Eq_21
  DataType: ptr64
  OrigDataType: ptr64
T_22: (in SLICE(0x0000000000004024<p64>, word32, 0) : word32)
  Class: Eq_22
  DataType: word32
  OrigDataType: word32
T_23: (in CONVERT(SLICE(0x0000000000004024<p64>, word32, 0), word32, uint64) : uint64)
  Class: Eq_23
  DataType: uint64
  OrigDataType: uint64
T_24: (in SLICE(CONVERT(SLICE(0x0000000000004024<p64>, word32, 0), word32, uint64), word32, 0) : word32)
  Class: Eq_20
  DataType: word32
  OrigDataType: word32
T_25: (in (word32) (uint64) (word32) 0x4024<u64> == (word32) ((uint64) ((word32) 0x4024<u64>)) : bool)
  Class: Eq_25
  DataType: bool
  OrigDataType: bool
T_26: (in eax_15 : word32)
  Class: Eq_26
  DataType: word32
  OrigDataType: word32
T_27: (in 0000000000003FD8 : ptr64)
  Class: Eq_27
  DataType: (ptr64 word32)
  OrigDataType: (ptr64 (struct (0 T_28 t0000)))
T_28: (in Mem0[0x0000000000003FD8<p64>:word32] : word32)
  Class: Eq_28
  DataType: word32
  OrigDataType: word32
T_29: (in CONVERT(Mem0[0x0000000000003FD8<p64>:word32], word32, uint64) : uint64)
  Class: Eq_29
  DataType: uint64
  OrigDataType: uint64
T_30: (in SLICE(CONVERT(Mem0[0x0000000000003FD8<p64>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_26
  DataType: word32
  OrigDataType: word32
T_31: (in 0<32> : word32)
  Class: Eq_26
  DataType: word32
  OrigDataType: word32
T_32: (in eax_15 == 0<32> : bool)
  Class: Eq_32
  DataType: bool
  OrigDataType: bool
T_33: (in rax_20 : (ptr64 code))
  Class: Eq_33
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_34: (in CONVERT(eax_15, word32, uint64) : uint64)
  Class: Eq_33
  DataType: (ptr64 code)
  OrigDataType: uint64
T_35: (in esi_12 : uint32)
  Class: Eq_35
  DataType: uint32
  OrigDataType: uint32
T_36: (in 0000000000004024 : ptr64)
  Class: Eq_36
  DataType: int64
  OrigDataType: (union (int64 u0) (ptr64 u1))
T_37: (in 0000000000004024 : ptr64)
  Class: Eq_37
  DataType: int64
  OrigDataType: (union (int64 u1) (ptr64 u0))
T_38: (in 0x4024<u64> - 0x4024<u64> : ptr64)
  Class: Eq_38
  DataType: int64
  OrigDataType: int64
T_39: (in SLICE(0x0000000000004024<p64> - 0x0000000000004024<p64>, word32, 0) : word32)
  Class: Eq_39
  DataType: word32
  OrigDataType: word32
T_40: (in CONVERT(SLICE(0x0000000000004024<p64> - 0x0000000000004024<p64>, word32, 0), word32, uint64) : uint64)
  Class: Eq_40
  DataType: uint64
  OrigDataType: uint64
T_41: (in SLICE(CONVERT(SLICE(0x0000000000004024<p64> - 0x0000000000004024<p64>, word32, 0), word32, uint64), word32, 0) : word32)
  Class: Eq_35
  DataType: uint32
  OrigDataType: word32
T_42: (in 0x1F<32> : word32)
  Class: Eq_42
  DataType: word32
  OrigDataType: word32
T_43: (in esi_12 >> 0x1F<32> : word32)
  Class: Eq_43
  DataType: uint32
  OrigDataType: uint32
T_44: (in CONVERT(esi_12, word32, uint64) : uint64)
  Class: Eq_44
  DataType: uint64
  OrigDataType: uint64
T_45: (in SLICE(CONVERT(esi_12, word32, uint64), word32, 0) : word32)
  Class: Eq_45
  DataType: int32
  OrigDataType: int32
T_46: (in 2<32> : word32)
  Class: Eq_46
  DataType: word32
  OrigDataType: word32
T_47: (in (word32) (uint64) esi_12 >> 2<32> : word32)
  Class: Eq_47
  DataType: int32
  OrigDataType: int32
T_48: (in (esi_12 >> 0x1F<32>) + ((word32) ((uint64) esi_12) >> 2<32>) : word32)
  Class: Eq_48
  DataType: uint32
  OrigDataType: uint32
T_49: (in CONVERT((esi_12 >>u 0x1F<32>) + (SLICE(CONVERT(esi_12, word32, uint64), word32, 0) >> 2<32>), word32, uint64) : uint64)
  Class: Eq_49
  DataType: uint64
  OrigDataType: uint64
T_50: (in SLICE(CONVERT((esi_12 >>u 0x1F<32>) + (SLICE(CONVERT(esi_12, word32, uint64), word32, 0) >> 2<32>), word32, uint64), word32, 0) : word32)
  Class: Eq_50
  DataType: int32
  OrigDataType: int32
T_51: (in 1<32> : word32)
  Class: Eq_51
  DataType: word32
  OrigDataType: word32
T_52: (in (word32) (uint64) ((esi_12 >> 0x1F<32>) + ((word32) ((uint64) esi_12) >> 2<32>)) >> 1<32> : word32)
  Class: Eq_52
  DataType: int32
  OrigDataType: int32
T_53: (in CONVERT(SLICE(CONVERT((esi_12 >>u 0x1F<32>) + (SLICE(CONVERT(esi_12, word32, uint64), word32, 0) >> 2<32>), word32, uint64), word32, 0) >> 1<32>, word32, uint64) : uint64)
  Class: Eq_53
  DataType: uint64
  OrigDataType: uint64
T_54: (in SLICE(CONVERT(SLICE(CONVERT((esi_12 >>u 0x1F<32>) + (SLICE(CONVERT(esi_12, word32, uint64), word32, 0) >> 2<32>), word32, uint64), word32, 0) >> 1<32>, word32, uint64), word32, 0) : word32)
  Class: Eq_54
  DataType: word32
  OrigDataType: word32
T_55: (in 0<32> : word32)
  Class: Eq_54
  DataType: word32
  OrigDataType: word32
T_56: (in (word32) (uint64) ((word32) (uint64) ((esi_12 >> 0x1F<32>) + ((word32) ((uint64) esi_12) >> 2<32>)) >> 1<32>) == 0<32> : bool)
  Class: Eq_56
  DataType: bool
  OrigDataType: bool
T_57: (in eax_33 : word32)
  Class: Eq_57
  DataType: word32
  OrigDataType: word32
T_58: (in 0000000000003FF8 : ptr64)
  Class: Eq_58
  DataType: (ptr64 word32)
  OrigDataType: (ptr64 (struct (0 T_59 t0000)))
T_59: (in Mem0[0x0000000000003FF8<p64>:word32] : word32)
  Class: Eq_59
  DataType: word32
  OrigDataType: word32
T_60: (in CONVERT(Mem0[0x0000000000003FF8<p64>:word32], word32, uint64) : uint64)
  Class: Eq_60
  DataType: uint64
  OrigDataType: uint64
T_61: (in SLICE(CONVERT(Mem0[0x0000000000003FF8<p64>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_57
  DataType: word32
  OrigDataType: word32
T_62: (in 0<32> : word32)
  Class: Eq_57
  DataType: word32
  OrigDataType: word32
T_63: (in eax_33 == 0<32> : bool)
  Class: Eq_63
  DataType: bool
  OrigDataType: bool
T_64: (in rax_38 : (ptr64 code))
  Class: Eq_64
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_65: (in CONVERT(eax_33, word32, uint64) : uint64)
  Class: Eq_64
  DataType: (ptr64 code)
  OrigDataType: uint64
T_66: (in 0000000000004024 : ptr64)
  Class: Eq_66
  DataType: (ptr64 byte)
  OrigDataType: (ptr64 (struct (0 T_67 t0000)))
T_67: (in Mem0[0x0000000000004024<p64>:byte] : byte)
  Class: Eq_67
  DataType: byte
  OrigDataType: byte
T_68: (in 0<8> : byte)
  Class: Eq_67
  DataType: byte
  OrigDataType: byte
T_69: (in g_b4024 != 0<8> : bool)
  Class: Eq_69
  DataType: bool
  OrigDataType: bool
T_70: (in 0000000000003FF0 : ptr64)
  Class: Eq_70
  DataType: (ptr64 Eq_16)
  OrigDataType: (ptr64 (struct (0 T_71 t0000)))
T_71: (in Mem9[0x0000000000003FF0<p64>:word32] : word32)
  Class: Eq_16
  DataType: Eq_16
  OrigDataType: word32
T_72: (in CONVERT(Mem9[0x0000000000003FF0<p64>:word32], word32, uint64) : uint64)
  Class: Eq_72
  DataType: uint64
  OrigDataType: uint64
T_73: (in SLICE(CONVERT(Mem9[0x0000000000003FF0<p64>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_73
  DataType: word32
  OrigDataType: word32
T_74: (in 0<32> : word32)
  Class: Eq_73
  DataType: word32
  OrigDataType: word32
T_75: (in (word32) (uint64) g_t3FF0 == 0<32> : bool)
  Class: Eq_75
  DataType: bool
  OrigDataType: bool
T_76: (in eax_32 : word32)
  Class: Eq_76
  DataType: word32
  OrigDataType: word32
T_77: (in 0000000000003F10 : ptr64)
  Class: Eq_77
  DataType: ptr64
  OrigDataType: ptr64
T_78: (in SLICE(0x0000000000003F10<p64>, word32, 0) : word32)
  Class: Eq_78
  DataType: word32
  OrigDataType: word32
T_79: (in CONVERT(SLICE(0x0000000000003F10<p64>, word32, 0), word32, uint64) : uint64)
  Class: Eq_79
  DataType: uint64
  OrigDataType: uint64
T_80: (in SLICE(CONVERT(SLICE(0x0000000000003F10<p64>, word32, 0), word32, uint64), word32, 0) : word32)
  Class: Eq_76
  DataType: word32
  OrigDataType: word32
T_81: (in rbx_45 : uint64)
  Class: Eq_81
  DataType: uint64
  OrigDataType: uint64
T_82: (in 0000000000003F14 : ptr64)
  Class: Eq_82
  DataType: ptr64
  OrigDataType: ptr64
T_83: (in SLICE(0x0000000000003F14<p64>, word32, 0) : word32)
  Class: Eq_83
  DataType: word32
  OrigDataType: word32
T_84: (in CONVERT(SLICE(0x0000000000003F14<p64>, word32, 0), word32, uint64) : uint64)
  Class: Eq_84
  DataType: uint64
  OrigDataType: uint64
T_85: (in SLICE(CONVERT(SLICE(0x0000000000003F14<p64>, word32, 0), word32, uint64), word32, 0) : word32)
  Class: Eq_85
  DataType: word32
  OrigDataType: word32
T_86: (in (word32) (uint64) (word32) 0x3F14<u64> - eax_32 : word32)
  Class: Eq_86
  DataType: word32
  OrigDataType: word32
T_87: (in CONVERT(SLICE(CONVERT(SLICE(0x0000000000003F14<p64>, word32, 0), word32, uint64), word32, 0) - eax_32, word32, uint64) : uint64)
  Class: Eq_87
  DataType: uint64
  OrigDataType: uint64
T_88: (in SLICE(CONVERT(SLICE(CONVERT(SLICE(0x0000000000003F14<p64>, word32, 0), word32, uint64), word32, 0) - eax_32, word32, uint64), word32, 0) : word32)
  Class: Eq_88
  DataType: int32
  OrigDataType: int32
T_89: (in 2<32> : word32)
  Class: Eq_89
  DataType: word32
  OrigDataType: word32
T_90: (in (word32) (uint64) ((word32) (uint64) (word32) 0x3F14<u64> - eax_32) >> 2<32> : word32)
  Class: Eq_90
  DataType: int32
  OrigDataType: int32
T_91: (in CONVERT(SLICE(CONVERT(SLICE(CONVERT(SLICE(0x0000000000003F14<p64>, word32, 0), word32, uint64), word32, 0) - eax_32, word32, uint64), word32, 0) >> 2<32>, word32, uint64) : uint64)
  Class: Eq_91
  DataType: uint64
  OrigDataType: uint64
T_92: (in SLICE(CONVERT(SLICE(CONVERT(SLICE(CONVERT(SLICE(0x0000000000003F14<p64>, word32, 0), word32, uint64), word32, 0) - eax_32, word32, uint64), word32, 0) >> 2<32>, word32, uint64), word32, 0) : word32)
  Class: Eq_92
  DataType: word32
  OrigDataType: word32
T_93: (in 1<32> : word32)
  Class: Eq_93
  DataType: word32
  OrigDataType: word32
T_94: (in (word32) (uint64) ((word32) (uint64) ((word32) (uint64) (word32) 0x3F14<u64> - eax_32) >> 2<32>) - 1<32> : word32)
  Class: Eq_94
  DataType: word32
  OrigDataType: word32
T_95: (in CONVERT(SLICE(CONVERT(SLICE(CONVERT(SLICE(CONVERT(SLICE(0x0000000000003F14<p64>, word32, 0), word32, uint64), word32, 0) - eax_32, word32, uint64), word32, 0) >> 2<32>, word32, uint64), word32, 0) - 1<32>, word32, uint64) : uint64)
  Class: Eq_81
  DataType: uint64
  OrigDataType: uint64
T_96: (in r12d_90 : (arr word32))
  Class: Eq_96
  DataType: (ptr32 (arr word32))
  OrigDataType: (ptr32 (struct (0 (arr T_315) a0000)))
T_97: (in CONVERT(eax_32, word32, uint64) : uint64)
  Class: Eq_97
  DataType: uint64
  OrigDataType: uint64
T_98: (in SLICE(CONVERT(eax_32, word32, uint64), word32, 0) : word32)
  Class: Eq_96
  DataType: (ptr32 (arr word32))
  OrigDataType: word32
T_99: (in eax_46 : up32)
  Class: Eq_99
  DataType: up32
  OrigDataType: up32
T_100: (in 0000000000004028 : ptr64)
  Class: Eq_100
  DataType: (ptr64 ui32)
  OrigDataType: (ptr64 (struct (0 T_101 t0000)))
T_101: (in Mem20[0x0000000000004028<p64>:word32] : word32)
  Class: Eq_101
  DataType: ui32
  OrigDataType: word32
T_102: (in CONVERT(Mem20[0x0000000000004028<p64>:word32], word32, uint64) : uint64)
  Class: Eq_102
  DataType: uint64
  OrigDataType: uint64
T_103: (in SLICE(CONVERT(Mem20[0x0000000000004028<p64>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_99
  DataType: up32
  OrigDataType: word32
T_104: (in SLICE(rbx_45, word32, 0) : word32)
  Class: Eq_99
  DataType: up32
  OrigDataType: up32
T_105: (in eax_46 >= (word32) rbx_45 : bool)
  Class: Eq_105
  DataType: bool
  OrigDataType: bool
T_106: (in fn0000000000001058 : ptr64)
  Class: Eq_106
  DataType: (ptr64 Eq_106)
  OrigDataType: (ptr64 (fn T_108 ()))
T_107: (in signature of fn0000000000001058 : void)
  Class: Eq_106
  DataType: (ptr64 Eq_106)
  OrigDataType: 
T_108: (in fn0000000000001058() : void)
  Class: Eq_108
  DataType: void
  OrigDataType: void
T_109: (in deregister_tm_clones : ptr64)
  Class: Eq_109
  DataType: (ptr64 Eq_109)
  OrigDataType: (ptr64 (fn T_111 ()))
T_110: (in signature of deregister_tm_clones : void)
  Class: Eq_109
  DataType: (ptr64 Eq_109)
  OrigDataType: 
T_111: (in deregister_tm_clones() : void)
  Class: Eq_111
  DataType: void
  OrigDataType: void
T_112: (in 1<8> : byte)
  Class: Eq_67
  DataType: byte
  OrigDataType: byte
T_113: (in 0000000000004024 : ptr64)
  Class: Eq_113
  DataType: (ptr64 byte)
  OrigDataType: (ptr64 (struct (0 T_114 t0000)))
T_114: (in Mem87[0x0000000000004024<p64>:byte] : byte)
  Class: Eq_67
  DataType: byte
  OrigDataType: byte
T_115: (in eax_53 : ui32)
  Class: Eq_101
  DataType: ui32
  OrigDataType: ui32
T_116: (in 1<32> : word32)
  Class: Eq_116
  DataType: up32
  OrigDataType: up32
T_117: (in eax_46 + 1<32> : word32)
  Class: Eq_117
  DataType: up32
  OrigDataType: up32
T_118: (in CONVERT(eax_46 + 1<32>, word32, uint64) : uint64)
  Class: Eq_118
  DataType: uint64
  OrigDataType: uint64
T_119: (in SLICE(CONVERT(eax_46 + 1<32>, word32, uint64), word32, 0) : word32)
  Class: Eq_101
  DataType: ui32
  OrigDataType: word32
T_120: (in 0000000000004028 : ptr64)
  Class: Eq_120
  DataType: (ptr64 ui32)
  OrigDataType: (ptr64 (struct (0 T_121 t0000)))
T_121: (in Mem55[0x0000000000004028<p64>:word32] : word32)
  Class: Eq_101
  DataType: ui32
  OrigDataType: word32
T_122: (in rax_58 : (ptr64 code))
  Class: Eq_122
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_123: (in 4<32> : word32)
  Class: Eq_123
  DataType: ui32
  OrigDataType: ui32
T_124: (in eax_53 * 4<32> : word32)
  Class: Eq_124
  DataType: ui32
  OrigDataType: ui32
T_125: (in r12d_90[eax_53 * 4<32>] : word32)
  Class: Eq_125
  DataType: word32
  OrigDataType: word32
T_126: (in CONVERT(r12d_90[eax_53 * 4<32>], word32, uint64) : uint64)
  Class: Eq_122
  DataType: (ptr64 code)
  OrigDataType: uint64
T_127: (in rdi_66 : word64)
  Class: Eq_127
  DataType: word64
  OrigDataType: word64
T_128: (in 0000000000004028 : ptr64)
  Class: Eq_128
  DataType: (ptr64 ui32)
  OrigDataType: (ptr64 (struct (0 T_129 t0000)))
T_129: (in Mem55[0x0000000000004028<p64>:word32] : word32)
  Class: Eq_101
  DataType: ui32
  OrigDataType: word32
T_130: (in CONVERT(Mem55[0x0000000000004028<p64>:word32], word32, uint64) : uint64)
  Class: Eq_130
  DataType: uint64
  OrigDataType: uint64
T_131: (in SLICE(CONVERT(Mem55[0x0000000000004028<p64>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_99
  DataType: up32
  OrigDataType: word32
T_132: (in SLICE(rbx_45, word32, 0) : word32)
  Class: Eq_99
  DataType: up32
  OrigDataType: up32
T_133: (in eax_46 < (word32) rbx_45 : bool)
  Class: Eq_133
  DataType: bool
  OrigDataType: bool
T_134: (in register_tm_clones : ptr64)
  Class: Eq_134
  DataType: (ptr64 Eq_134)
  OrigDataType: (ptr64 (fn T_136 ()))
T_135: (in signature of register_tm_clones : void)
  Class: Eq_134
  DataType: (ptr64 Eq_134)
  OrigDataType: 
T_136: (in register_tm_clones() : void)
  Class: Eq_136
  DataType: void
  OrigDataType: void
T_137: (in ecx : word32)
  Class: Eq_137
  DataType: word32
  OrigDataType: word32
T_138: (in edx : word32)
  Class: Eq_138
  DataType: word32
  OrigDataType: word32
T_139: (in esi : word32)
  Class: Eq_139
  DataType: word32
  OrigDataType: word32
T_140: (in edi : word32)
  Class: Eq_140
  DataType: word32
  OrigDataType: word32
T_141: (in r8d : word32)
  Class: Eq_141
  DataType: word32
  OrigDataType: word32
T_142: (in rbp_9 : uint64)
  Class: Eq_142
  DataType: uint64
  OrigDataType: uint64
T_143: (in fp : ptr64)
  Class: Eq_143
  DataType: ptr64
  OrigDataType: ptr64
T_144: (in 8<i64> : int64)
  Class: Eq_144
  DataType: int64
  OrigDataType: int64
T_145: (in fp - 8<i64> : word64)
  Class: Eq_145
  DataType: ptr64
  OrigDataType: ptr64
T_146: (in SLICE(fp - 8<i64>, word32, 0) : word32)
  Class: Eq_146
  DataType: word32
  OrigDataType: word32
T_147: (in CONVERT(SLICE(fp - 8<i64>, word32, 0), word32, uint64) : uint64)
  Class: Eq_142
  DataType: uint64
  OrigDataType: uint64
T_148: (in ebp_15 : (ptr32 Eq_148))
  Class: Eq_148
  DataType: (ptr32 Eq_148)
  OrigDataType: (ptr32 (struct (FFFFFF5C T_161 tFFFFFF5C) (FFFFFF60 T_158 tFFFFFF60) (FFFFFF64 T_138 tFFFFFF64) (FFFFFF68 T_139 tFFFFFF68) (FFFFFF6C T_163 tFFFFFF6C) (FFFFFF78 T_179 tFFFFFF78) (FFFFFF7C T_187 tFFFFFF7C) (FFFFFFF0 T_214 tFFFFFFF0) (FFFFFFF4 T_203 tFFFFFFF4) (FFFFFFF8 T_198 tFFFFFFF8) (FFFFFFFC T_171 tFFFFFFFC)))
T_149: (in SLICE(rbp_9, word32, 0) : word32)
  Class: Eq_148
  DataType: (ptr32 Eq_148)
  OrigDataType: word32
T_150: (in -152<i32> : int32)
  Class: Eq_150
  DataType: int32
  OrigDataType: int32
T_151: (in ebp_15 + -152<i32> : word32)
  Class: Eq_151
  DataType: word32
  OrigDataType: word32
T_152: (in Mem16[ebp_15 + -152<i32>:word32] : word32)
  Class: Eq_139
  DataType: word32
  OrigDataType: word32
T_153: (in -156<i32> : int32)
  Class: Eq_153
  DataType: int32
  OrigDataType: int32
T_154: (in ebp_15 + -156<i32> : word32)
  Class: Eq_154
  DataType: ptr32
  OrigDataType: ptr32
T_155: (in Mem18[ebp_15 + -156<i32>:word32] : word32)
  Class: Eq_138
  DataType: word32
  OrigDataType: word32
T_156: (in -160<i32> : int32)
  Class: Eq_156
  DataType: int32
  OrigDataType: int32
T_157: (in ebp_15 + -160<i32> : word32)
  Class: Eq_157
  DataType: ptr32
  OrigDataType: ptr32
T_158: (in Mem20[ebp_15 + -160<i32>:word32] : word32)
  Class: Eq_137
  DataType: word32
  OrigDataType: word32
T_159: (in -164<i32> : int32)
  Class: Eq_159
  DataType: int32
  OrigDataType: int32
T_160: (in ebp_15 + -164<i32> : word32)
  Class: Eq_160
  DataType: ptr32
  OrigDataType: ptr32
T_161: (in Mem22[ebp_15 + -164<i32>:word32] : word32)
  Class: Eq_141
  DataType: word32
  OrigDataType: word32
T_162: (in rdi : word64)
  Class: Eq_162
  DataType: word64
  OrigDataType: word64
T_163: (in SLICE(rdi, word32, 0) : word32)
  Class: Eq_163
  DataType: word32
  OrigDataType: word32
T_164: (in -148<i32> : int32)
  Class: Eq_164
  DataType: int32
  OrigDataType: int32
T_165: (in ebp_15 + -148<i32> : word32)
  Class: Eq_165
  DataType: ptr32
  OrigDataType: ptr32
T_166: (in Mem24[ebp_15 + -148<i32>:word32] : word32)
  Class: Eq_163
  DataType: word32
  OrigDataType: word32
T_167: (in -148<i32> : int32)
  Class: Eq_167
  DataType: int32
  OrigDataType: int32
T_168: (in ebp_15 + -148<i32> : word32)
  Class: Eq_168
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_169: (in Mem24[ebp_15 + -148<i32>:word32] : word32)
  Class: Eq_163
  DataType: word32
  OrigDataType: word32
T_170: (in CONVERT(Mem24[ebp_15 + -148<i32>:word32], word32, uint64) : uint64)
  Class: Eq_170
  DataType: uint64
  OrigDataType: uint64
T_171: (in SLICE(CONVERT(Mem24[ebp_15 + -148<i32>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_171
  DataType: word32
  OrigDataType: word32
T_172: (in -4<i32> : int32)
  Class: Eq_172
  DataType: int32
  OrigDataType: int32
T_173: (in ebp_15 + -4<i32> : word32)
  Class: Eq_173
  DataType: ptr32
  OrigDataType: ptr32
T_174: (in Mem28[ebp_15 + -4<i32>:word32] : word32)
  Class: Eq_171
  DataType: word32
  OrigDataType: word32
T_175: (in -4<i32> : int32)
  Class: Eq_175
  DataType: int32
  OrigDataType: int32
T_176: (in ebp_15 + -4<i32> : word32)
  Class: Eq_176
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_177: (in Mem28[ebp_15 + -4<i32>:word32] : word32)
  Class: Eq_171
  DataType: word32
  OrigDataType: word32
T_178: (in CONVERT(Mem28[ebp_15 + -4<i32>:word32], word32, uint64) : uint64)
  Class: Eq_178
  DataType: uint64
  OrigDataType: uint64
T_179: (in SLICE(CONVERT(Mem28[ebp_15 + -4<i32>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_179
  DataType: word32
  OrigDataType: word32
T_180: (in -136<i32> : int32)
  Class: Eq_180
  DataType: int32
  OrigDataType: int32
T_181: (in ebp_15 + -136<i32> : word32)
  Class: Eq_181
  DataType: ptr32
  OrigDataType: ptr32
T_182: (in Mem32[ebp_15 + -136<i32>:word32] : word32)
  Class: Eq_179
  DataType: word32
  OrigDataType: word32
T_183: (in -152<i32> : int32)
  Class: Eq_183
  DataType: int32
  OrigDataType: int32
T_184: (in ebp_15 + -152<i32> : word32)
  Class: Eq_184
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_185: (in Mem32[ebp_15 + -152<i32>:word32] : word32)
  Class: Eq_139
  DataType: word32
  OrigDataType: word32
T_186: (in CONVERT(Mem32[ebp_15 + -152<i32>:word32], word32, uint64) : uint64)
  Class: Eq_186
  DataType: uint64
  OrigDataType: uint64
T_187: (in SLICE(CONVERT(Mem32[ebp_15 + -152<i32>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_187
  DataType: word32
  OrigDataType: word32
T_188: (in -132<i32> : int32)
  Class: Eq_188
  DataType: int32
  OrigDataType: int32
T_189: (in ebp_15 + -132<i32> : word32)
  Class: Eq_189
  DataType: ptr32
  OrigDataType: ptr32
T_190: (in Mem36[ebp_15 + -132<i32>:word32] : word32)
  Class: Eq_187
  DataType: word32
  OrigDataType: word32
T_191: (in -136<i32> : int32)
  Class: Eq_191
  DataType: int32
  OrigDataType: int32
T_192: (in ebp_15 + -136<i32> : word32)
  Class: Eq_192
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_193: (in Mem36[ebp_15 + -136<i32>:word32] : word32)
  Class: Eq_179
  DataType: word32
  OrigDataType: word32
T_194: (in CONVERT(Mem36[ebp_15 + -136<i32>:word32], word32, uint64) : uint64)
  Class: Eq_194
  DataType: uint64
  OrigDataType: uint64
T_195: (in SLICE(CONVERT(Mem36[ebp_15 + -136<i32>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_195
  DataType: word32
  OrigDataType: word32
T_196: (in -8<i32> : int32)
  Class: Eq_196
  DataType: int32
  OrigDataType: int32
T_197: (in ebp_15 + -8<i32> : word32)
  Class: Eq_197
  DataType: ptr32
  OrigDataType: ptr32
T_198: (in Mem40[ebp_15 + -8<i32>:word32] : word32)
  Class: Eq_195
  DataType: word32
  OrigDataType: word32
T_199: (in -132<i32> : int32)
  Class: Eq_199
  DataType: int32
  OrigDataType: int32
T_200: (in ebp_15 + -132<i32> : word32)
  Class: Eq_200
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_201: (in Mem40[ebp_15 + -132<i32>:word32] : word32)
  Class: Eq_187
  DataType: word32
  OrigDataType: word32
T_202: (in CONVERT(Mem40[ebp_15 + -132<i32>:word32], word32, uint64) : uint64)
  Class: Eq_202
  DataType: uint64
  OrigDataType: uint64
T_203: (in SLICE(CONVERT(Mem40[ebp_15 + -132<i32>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_203
  DataType: word32
  OrigDataType: word32
T_204: (in -12<i32> : int32)
  Class: Eq_204
  DataType: int32
  OrigDataType: int32
T_205: (in ebp_15 + -12<i32> : word32)
  Class: Eq_205
  DataType: ptr32
  OrigDataType: ptr32
T_206: (in Mem44[ebp_15 + -12<i32>:word32] : word32)
  Class: Eq_203
  DataType: word32
  OrigDataType: word32
T_207: (in -12<i32> : int32)
  Class: Eq_207
  DataType: int32
  OrigDataType: int32
T_208: (in ebp_15 + -12<i32> : word32)
  Class: Eq_208
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_209: (in Mem44[ebp_15 + -12<i32>:word32] : word32)
  Class: Eq_203
  DataType: word32
  OrigDataType: word32
T_210: (in CONVERT(Mem44[ebp_15 + -12<i32>:word32], word32, uint64) : uint64)
  Class: Eq_210
  DataType: uint64
  OrigDataType: uint64
T_211: (in SLICE(CONVERT(Mem44[ebp_15 + -12<i32>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_211
  DataType: word32
  OrigDataType: word32
T_212: (in -16<i32> : int32)
  Class: Eq_212
  DataType: int32
  OrigDataType: int32
T_213: (in ebp_15 + -16<i32> : word32)
  Class: Eq_213
  DataType: ptr32
  OrigDataType: ptr32
T_214: (in Mem48[ebp_15 + -16<i32>:word32] : word32)
  Class: Eq_211
  DataType: word32
  OrigDataType: word32
T_215: (in 0x41<8> : byte)
  Class: Eq_215
  DataType: byte
  OrigDataType: byte
T_216: (in -156<i32> : int32)
  Class: Eq_216
  DataType: int32
  OrigDataType: int32
T_217: (in ebp_15 + -156<i32> : word32)
  Class: Eq_217
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_218: (in Mem48[ebp_15 + -156<i32>:word32] : word32)
  Class: Eq_138
  DataType: word32
  OrigDataType: word32
T_219: (in 0x80<64> : word64)
  Class: Eq_219
  DataType: uint64
  OrigDataType: uint64
T_220: (in rbp_9 - 0x80<64> : word64)
  Class: Eq_220
  DataType: uint64
  OrigDataType: uint64
T_221: (in SLICE(rbp_9 - 0x80<64>, word32, 0) : word32)
  Class: Eq_221
  DataType: word32
  OrigDataType: word32
T_222: (in ebp_15->dwFFFFFF64 + (word32) (rbp_9 - 0x80<64>) : word32)
  Class: Eq_222
  DataType: word32
  OrigDataType: word32
T_223: (in CONVERT(Mem48[ebp_15 + -156<i32>:word32] + SLICE(rbp_9 - 0x80<64>, word32, 0), word32, uint64) : uint64)
  Class: Eq_223
  DataType: uint64
  OrigDataType: uint64
T_224: (in SLICE(CONVERT(Mem48[ebp_15 + -156<i32>:word32] + SLICE(rbp_9 - 0x80<64>, word32, 0), word32, uint64), word32, 0) : word32)
  Class: Eq_224
  DataType: (ptr32 byte)
  OrigDataType: (ptr32 (struct (0 T_227 t0000)))
T_225: (in 0<32> : word32)
  Class: Eq_225
  DataType: word32
  OrigDataType: word32
T_226: (in SLICE(CONVERT(Mem48[ebp_15 + -156<i32>:word32] + SLICE(rbp_9 - 0x80<64>, word32, 0), word32, uint64), word32, 0) + 0<32> : word32)
  Class: Eq_226
  DataType: word32
  OrigDataType: word32
T_227: (in Mem58[SLICE(CONVERT(Mem48[ebp_15 + -156<i32>:word32] + SLICE(rbp_9 - 0x80<64>, word32, 0), word32, uint64), word32, 0) + 0<32>:byte] : byte)
  Class: Eq_215
  DataType: byte
  OrigDataType: byte
T_228: (in 0x20<8> : byte)
  Class: Eq_228
  DataType: byte
  OrigDataType: byte
T_229: (in 0x80<32> : word32)
  Class: Eq_229
  DataType: ui32
  OrigDataType: ui32
T_230: (in ebp_15 - 0x80<32> : word32)
  Class: Eq_230
  DataType: ptr32
  OrigDataType: ptr32
T_231: (in -156<i32> : int32)
  Class: Eq_231
  DataType: int32
  OrigDataType: int32
T_232: (in ebp_15 + -156<i32> : word32)
  Class: Eq_232
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_233: (in Mem58[ebp_15 + -156<i32>:word32] : word32)
  Class: Eq_138
  DataType: word32
  OrigDataType: word32
T_234: (in CONVERT(Mem58[ebp_15 + -156<i32>:word32], word32, uint64) : uint64)
  Class: Eq_234
  DataType: uint64
  OrigDataType: uint64
T_235: (in SLICE(CONVERT(Mem58[ebp_15 + -156<i32>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_235
  DataType: word32
  OrigDataType: word32
T_236: (in 1<32> : word32)
  Class: Eq_236
  DataType: word32
  OrigDataType: word32
T_237: (in (word32) (uint64) ebp_15->dwFFFFFF64 + 1<32> : word32)
  Class: Eq_237
  DataType: word32
  OrigDataType: word32
T_238: (in CONVERT(SLICE(CONVERT(Mem58[ebp_15 + -156<i32>:word32], word32, uint64), word32, 0) + 1<32>, word32, uint64) : uint64)
  Class: Eq_238
  DataType: uint64
  OrigDataType: uint64
T_239: (in SLICE(CONVERT(SLICE(CONVERT(Mem58[ebp_15 + -156<i32>:word32], word32, uint64), word32, 0) + 1<32>, word32, uint64), word32, 0) : word32)
  Class: Eq_239
  DataType: int32
  OrigDataType: int32
T_240: (in ebp_15 - 0x80<32> + (word32) ((uint64) ((word32) ((uint64) ebp_15->dwFFFFFF64) + 1<32>)) : word32)
  Class: Eq_240
  DataType: (ptr32 byte)
  OrigDataType: (ptr32 (struct (0 T_241 t0000)))
T_241: (in Mem65[ebp_15 - 0x80<32> + SLICE(CONVERT(SLICE(CONVERT(Mem58[ebp_15 + -156<i32>:word32], word32, uint64), word32, 0) + 1<32>, word32, uint64), word32, 0):byte] : byte)
  Class: Eq_228
  DataType: byte
  OrigDataType: byte
T_242: (in -132<i32> : int32)
  Class: Eq_242
  DataType: int32
  OrigDataType: int32
T_243: (in ebp_15 + -132<i32> : word32)
  Class: Eq_243
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_244: (in Mem65[ebp_15 + -132<i32>:word32] : word32)
  Class: Eq_187
  DataType: word32
  OrigDataType: word32
T_245: (in -12<i32> : int32)
  Class: Eq_245
  DataType: int32
  OrigDataType: int32
T_246: (in ebp_15 + -12<i32> : word32)
  Class: Eq_246
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_247: (in Mem65[ebp_15 + -12<i32>:word32] : word32)
  Class: Eq_203
  DataType: word32
  OrigDataType: word32
T_248: (in ebp_15->dwFFFFFF7C - ebp_15->dwFFFFFFF4 : word32)
  Class: Eq_248
  DataType: word32
  OrigDataType: word32
T_249: (in CONVERT(Mem65[ebp_15 + -132<i32>:word32] - Mem65[ebp_15 + -12<i32>:word32], word32, uint64) : uint64)
  Class: Eq_249
  DataType: uint64
  OrigDataType: uint64
T_250: (in SLICE(CONVERT(Mem65[ebp_15 + -132<i32>:word32] - Mem65[ebp_15 + -12<i32>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_187
  DataType: word32
  OrigDataType: word32
T_251: (in -132<i32> : int32)
  Class: Eq_251
  DataType: int32
  OrigDataType: int32
T_252: (in ebp_15 + -132<i32> : word32)
  Class: Eq_252
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_253: (in Mem76[ebp_15 + -132<i32>:word32] : word32)
  Class: Eq_187
  DataType: word32
  OrigDataType: word32
T_254: (in esi : word32)
  Class: Eq_254
  DataType: word32
  OrigDataType: word32
T_255: (in edi : word32)
  Class: Eq_255
  DataType: word32
  OrigDataType: word32
T_256: (in ebp_19 : (ptr32 Eq_256))
  Class: Eq_256
  DataType: (ptr32 Eq_256)
  OrigDataType: (ptr32 (struct (FFFFFFE8 T_267 tFFFFFFE8) (FFFFFFEC T_265 tFFFFFFEC)))
T_257: (in fp : ptr64)
  Class: Eq_257
  DataType: ptr64
  OrigDataType: ptr64
T_258: (in 8<i64> : int64)
  Class: Eq_258
  DataType: int64
  OrigDataType: int64
T_259: (in fp - 8<i64> : word64)
  Class: Eq_259
  DataType: ptr64
  OrigDataType: ptr64
T_260: (in SLICE(fp - 8<i64>, word32, 0) : word32)
  Class: Eq_260
  DataType: word32
  OrigDataType: word32
T_261: (in CONVERT(SLICE(fp - 8<i64>, word32, 0), word32, uint64) : uint64)
  Class: Eq_261
  DataType: uint64
  OrigDataType: uint64
T_262: (in SLICE(CONVERT(SLICE(fp - 8<i64>, word32, 0), word32, uint64), word32, 0) : word32)
  Class: Eq_256
  DataType: (ptr32 Eq_256)
  OrigDataType: word32
T_263: (in -20<i32> : int32)
  Class: Eq_263
  DataType: int32
  OrigDataType: int32
T_264: (in ebp_19 + -20<i32> : word32)
  Class: Eq_264
  DataType: word32
  OrigDataType: word32
T_265: (in Mem20[ebp_19 + -20<i32>:word32] : word32)
  Class: Eq_255
  DataType: word32
  OrigDataType: word32
T_266: (in rsi : word64)
  Class: Eq_266
  DataType: word64
  OrigDataType: word64
T_267: (in SLICE(rsi, word32, 0) : word32)
  Class: Eq_267
  DataType: word32
  OrigDataType: word32
T_268: (in -24<i32> : int32)
  Class: Eq_268
  DataType: int32
  OrigDataType: int32
T_269: (in ebp_19 + -24<i32> : word32)
  Class: Eq_269
  DataType: ptr32
  OrigDataType: ptr32
T_270: (in Mem24[ebp_19 + -24<i32>:word32] : word32)
  Class: Eq_267
  DataType: word32
  OrigDataType: word32
T_271: (in strlen : ptr64)
  Class: Eq_271
  DataType: (ptr64 Eq_271)
  OrigDataType: (ptr64 (fn T_285 (T_284)))
T_272: (in signature of strlen : void)
  Class: Eq_271
  DataType: (ptr64 Eq_271)
  OrigDataType: 
T_273: (in rdi : (ptr64 char))
  Class: Eq_273
  DataType: uint64
  OrigDataType: 
T_274: (in -24<i32> : int32)
  Class: Eq_274
  DataType: int32
  OrigDataType: int32
T_275: (in ebp_19 + -24<i32> : word32)
  Class: Eq_275
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 word32)
T_276: (in Mem24[ebp_19 + -24<i32>:word32] : word32)
  Class: Eq_267
  DataType: word32
  OrigDataType: word32
T_277: (in CONVERT(Mem24[ebp_19 + -24<i32>:word32], word32, uint64) : uint64)
  Class: Eq_277
  DataType: uint64
  OrigDataType: uint64
T_278: (in SLICE(CONVERT(Mem24[ebp_19 + -24<i32>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_278
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_281 t0000)))
T_279: (in 0<32> : word32)
  Class: Eq_279
  DataType: word32
  OrigDataType: word32
T_280: (in SLICE(CONVERT(Mem24[ebp_19 + -24<i32>:word32], word32, uint64), word32, 0) + 0<32> : word32)
  Class: Eq_280
  DataType: word32
  OrigDataType: word32
T_281: (in Mem24[SLICE(CONVERT(Mem24[ebp_19 + -24<i32>:word32], word32, uint64), word32, 0) + 0<32>:word32] : word32)
  Class: Eq_281
  DataType: word32
  OrigDataType: word32
T_282: (in CONVERT(Mem24[SLICE(CONVERT(Mem24[ebp_19 + -24<i32>:word32], word32, uint64), word32, 0) + 0<32>:word32], word32, uint64) : uint64)
  Class: Eq_282
  DataType: uint64
  OrigDataType: uint64
T_283: (in SLICE(CONVERT(Mem24[SLICE(CONVERT(Mem24[ebp_19 + -24<i32>:word32], word32, uint64), word32, 0) + 0<32>:word32], word32, uint64), word32, 0) : word32)
  Class: Eq_283
  DataType: word32
  OrigDataType: word32
T_284: (in CONVERT(SLICE(CONVERT(Mem24[SLICE(CONVERT(Mem24[ebp_19 + -24<i32>:word32], word32, uint64), word32, 0) + 0<32>:word32], word32, uint64), word32, 0), word32, uint64) : uint64)
  Class: Eq_273
  DataType: uint64
  OrigDataType: uint64
T_285: (in strlen((uint64) (word32) (uint64) *(word32) (uint64) ebp_19->dwFFFFFFE8) : size_t)
  Class: Eq_285
  DataType: Eq_285
  OrigDataType: size_t
T_286: (in fn0000000000001050 : ptr64)
  Class: Eq_286
  DataType: (ptr64 Eq_286)
  OrigDataType: (ptr64 (fn T_288 ()))
T_287: (in signature of fn0000000000001050 : void)
  Class: Eq_286
  DataType: (ptr64 Eq_286)
  OrigDataType: 
T_288: (in fn0000000000001050() : void)
  Class: Eq_288
  DataType: void
  OrigDataType: void
T_289: (in rax_26 : (ptr64 code))
  Class: Eq_289
  DataType: (ptr64 code)
  OrigDataType: (ptr64 code)
T_290: (in 0000000000003F08 : ptr64)
  Class: Eq_290
  DataType: (ptr64 word32)
  OrigDataType: (ptr64 (struct (0 T_291 t0000)))
T_291: (in Mem0[0x0000000000003F08<p64>:word32] : word32)
  Class: Eq_291
  DataType: word32
  OrigDataType: word32
T_292: (in CONVERT(Mem0[0x0000000000003F08<p64>:word32], word32, uint64) : uint64)
  Class: Eq_289
  DataType: (ptr64 code)
  OrigDataType: uint64
T_293: (in SLICE(rax_26, word32, 0) : word32)
  Class: Eq_293
  DataType: word32
  OrigDataType: word32
T_294: (in 0xFFFFFFFF<32> : word32)
  Class: Eq_293
  DataType: word32
  OrigDataType: word32
T_295: (in (word32) rax_26 == 0xFFFFFFFF<32> : bool)
  Class: Eq_295
  DataType: bool
  OrigDataType: bool
T_296: (in rbx_20 : uint64)
  Class: Eq_296
  DataType: uint64
  OrigDataType: uint64
T_297: (in 0000000000003F08 : ptr64)
  Class: Eq_297
  DataType: ptr64
  OrigDataType: ptr64
T_298: (in SLICE(0x0000000000003F08<p64>, word32, 0) : word32)
  Class: Eq_298
  DataType: word32
  OrigDataType: word32
T_299: (in CONVERT(SLICE(0x0000000000003F08<p64>, word32, 0), word32, uint64) : uint64)
  Class: Eq_296
  DataType: uint64
  OrigDataType: uint64
T_300: (in ebx_33 : (ptr32 Eq_300))
  Class: Eq_300
  DataType: (ptr32 Eq_300)
  OrigDataType: (ptr32 (struct (FFFFFFFC T_304 tFFFFFFFC)))
T_301: (in SLICE(rbx_20, word32, 0) : word32)
  Class: Eq_300
  DataType: (ptr32 Eq_300)
  OrigDataType: word32
T_302: (in -4<i32> : int32)
  Class: Eq_302
  DataType: int32
  OrigDataType: int32
T_303: (in ebx_33 + -4<i32> : word32)
  Class: Eq_303
  DataType: word32
  OrigDataType: word32
T_304: (in Mem18[ebx_33 + -4<i32>:word32] : word32)
  Class: Eq_304
  DataType: word32
  OrigDataType: word32
T_305: (in CONVERT(Mem18[ebx_33 + -4<i32>:word32], word32, uint64) : uint64)
  Class: Eq_289
  DataType: (ptr64 code)
  OrigDataType: uint64
T_306: (in 4<32> : word32)
  Class: Eq_306
  DataType: ui32
  OrigDataType: ui32
T_307: (in ebx_33 - 4<32> : word32)
  Class: Eq_307
  DataType: ptr32
  OrigDataType: ptr32
T_308: (in CONVERT(ebx_33 - 4<32>, word32, uint64) : uint64)
  Class: Eq_296
  DataType: uint64
  OrigDataType: uint64
T_309: (in SLICE(rax_26, word32, 0) : word32)
  Class: Eq_309
  DataType: word32
  OrigDataType: word32
T_310: (in 0xFFFFFFFF<32> : word32)
  Class: Eq_309
  DataType: word32
  OrigDataType: word32
T_311: (in (word32) rax_26 != 0xFFFFFFFF<32> : bool)
  Class: Eq_311
  DataType: bool
  OrigDataType: bool
T_312: (in __do_global_dtors_aux : ptr64)
  Class: Eq_312
  DataType: (ptr64 Eq_312)
  OrigDataType: (ptr64 (fn T_314 ()))
T_313: (in signature of __do_global_dtors_aux : void)
  Class: Eq_312
  DataType: (ptr64 Eq_312)
  OrigDataType: 
T_314: (in __do_global_dtors_aux() : void)
  Class: Eq_314
  DataType: void
  OrigDataType: void
T_315:
  Class: Eq_315
  DataType: word32
  OrigDataType: (struct 0004 (0 T_125 t0000))
*/
typedef struct Globals {
	word32 dw3F08;	// 3F08
	word32 dw3FD8;	// 3FD8
	<anonymous> * ptr3FE0;	// 3FE0
	<anonymous> * ptr3FE8;	// 3FE8
	Eq_16 t3FF0;	// 3FF0
	word32 dw3FF8;	// 3FF8
	byte b4024;	// 4024
	ui32 dw4028;	// 4028
} Eq_1;

typedef void (Eq_7)();

typedef void (Eq_10)();

typedef union Eq_16 {
	word32 u0;
	<anonymous> * u1;
} Eq_16;

typedef union Eq_36 {
	int64 u0;
	ptr64 u1;
} Eq_36;

typedef union Eq_37 {
	int64 u0;
	ptr64 u1;
} Eq_37;

typedef void (Eq_106)();

typedef void (Eq_109)();

typedef void (Eq_134)();

typedef struct Eq_148 {
	word32 dwFFFFFF5C;	// FFFFFF5C
	word32 dwFFFFFF60;	// FFFFFF60
	word32 dwFFFFFF64;	// FFFFFF64
	word32 dwFFFFFF68;	// FFFFFF68
	word32 dwFFFFFF6C;	// FFFFFF6C
	word32 dwFFFFFF78;	// FFFFFF78
	word32 dwFFFFFF7C;	// FFFFFF7C
	word32 dwFFFFFFF0;	// FFFFFFF0
	word32 dwFFFFFFF4;	// FFFFFFF4
	word32 dwFFFFFFF8;	// FFFFFFF8
	word32 dwFFFFFFFC;	// FFFFFFFC
} Eq_148;

typedef struct Eq_256 {
	word32 dwFFFFFFE8;	// FFFFFFE8
	word32 dwFFFFFFEC;	// FFFFFFEC
} Eq_256;

typedef size_t (Eq_271)(uint64);

typedef size_t Eq_285;

typedef void (Eq_286)();

typedef struct Eq_300 {
	word32 dwFFFFFFFC;	// FFFFFFFC
} Eq_300;

typedef void (Eq_312)();

